// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: SecondaryFirebaseOptions.currentPlatform,
/// );
/// ```
class SecondaryFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'SecondaryFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'SecondaryFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiFWoBLFYV6EuI10plgd0km5fKtpo2FYY',
    appId: '1:790005513258:web:f0c7ba174e75ea7c2cd753',
    messagingSenderId: '790005513258',
    projectId: 'bayanatz-knowticed',
    authDomain: 'bayanatz-knowticed.firebaseapp.com',
    storageBucket: 'bayanatz-knowticed.appspot.com',
    measurementId: 'G-NST210SGV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXe7x6lqLz9ouQmefeW8KJAJjPmquLefU',
    appId: '1:790005513258:android:9d7eb0c9ceb4c29d2cd753',
    messagingSenderId: '790005513258',
    projectId: 'bayanatz-knowticed',
    storageBucket: 'bayanatz-knowticed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkgOanXbedTqDqjHKJ_NvAA5iJUvxC-Q',
    appId: '1:790005513258:ios:6ea9e37027ad38002cd753',
    messagingSenderId: '790005513258',
    projectId: 'bayanatz-knowticed',
    storageBucket: 'bayanatz-knowticed.appspot.com',
    iosBundleId: 'com.example.twoFirebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvkgOanXbedTqDqjHKJ_NvAA5iJUvxC-Q',
    appId: '1:790005513258:ios:6ea9e37027ad38002cd753',
    messagingSenderId: '790005513258',
    projectId: 'bayanatz-knowticed',
    storageBucket: 'bayanatz-knowticed.appspot.com',
    iosBundleId: 'com.example.twoFirebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiFWoBLFYV6EuI10plgd0km5fKtpo2FYY',
    appId: '1:790005513258:web:8e78ef5157011e142cd753',
    messagingSenderId: '790005513258',
    projectId: 'bayanatz-knowticed',
    authDomain: 'bayanatz-knowticed.firebaseapp.com',
    storageBucket: 'bayanatz-knowticed.appspot.com',
    measurementId: 'G-83KF673L98',
  );
}
