/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_10.dart
/// Purpose: Country reference data, part 10 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart10 = <Country>[
  Country(
    name: "Turks and Caicos Islands",
    nameTranslations: {
      "sk": "Turks a Caicos",
      "se": "Turks ja Caicos-sullot",
      "pl": "Turks i Caicos",
      "no": "Turks- og Caicosøyene",
      "ja": "タークス・カイコス諸島",
      "it": "Isole Turks e Caicos",
      "zh": "特克斯和凯科斯群岛",
      "nl": "Turks- en Caicoseilanden",
      "de": "Turks- und Caicosinseln",
      "fr": "Îles Turques-et-Caïques",
      "es": "Islas Turcas y Caicos",
      "en": "Turks & Caicos Islands",
      "pt_BR": "Ilhas Turks e Caicos",
      "sr-Cyrl": "Туркс и Кајкос",
      "sr-Latn": "Turks i Kajkos",
      "zh_TW": "土克斯及開科斯群島",
      "tr": "Turks ve Caicos Adaları",
      "ro": "Insulele Turks și Caicos",
      "ar": "جزر توركس وكايكوس",
      "fa": "جزایر تورکس و کایکوس",
      "yue": "特克斯同凯科斯群岛"
    },
    flag: "🇹🇨",
    code: "TC",
    dialCode: "1649",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Tuvalu",
    nameTranslations: {
      "sk": "Tuvalu",
      "se": "Tuvalu",
      "pl": "Tuvalu",
      "no": "Tuvalu",
      "ja": "ツバル",
      "it": "Tuvalu",
      "zh": "图瓦卢",
      "nl": "Tuvalu",
      "de": "Tuvalu",
      "fr": "Tuvalu",
      "es": "Tuvalu",
      "en": "Tuvalu",
      "pt_BR": "Tuvalu",
      "sr-Cyrl": "Тувалу",
      "sr-Latn": "Tuvalu",
      "zh_TW": "圖瓦盧",
      "tr": "Tuvalu",
      "ro": "Tuvalu",
      "ar": "توفالو",
      "fa": "تووالو",
      "yue": "圖瓦盧"
    },
    flag: "🇹🇻",
    code: "TV",
    dialCode: "688",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Uganda",
    nameTranslations: {
      "sk": "Uganda",
      "se": "Uganda",
      "pl": "Uganda",
      "no": "Uganda",
      "ja": "ウガンダ",
      "it": "Uganda",
      "zh": "乌干达",
      "nl": "Oeganda",
      "de": "Uganda",
      "fr": "Ouganda",
      "es": "Uganda",
      "en": "Uganda",
      "pt_BR": "Uganda",
      "sr-Cyrl": "Уганда",
      "sr-Latn": "Uganda",
      "zh_TW": "烏干達",
      "tr": "Uganda",
      "ro": "Uganda",
      "ar": "أوغندا",
      "fa": "اوگاندا",
      "yue": "烏干達"
    },
    flag: "🇺🇬",
    code: "UG",
    dialCode: "256",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Ukraine",
    nameTranslations: {
      "sk": "Ukrajina",
      "se": "Ukraina",
      "pl": "Ukraina",
      "no": "Ukraina",
      "ja": "ウクライナ",
      "it": "Ucraina",
      "zh": "乌克兰",
      "nl": "Oekraïne",
      "de": "Ukraine",
      "fr": "Ukraine",
      "es": "Ucrania",
      "en": "Ukraine",
      "pt_BR": "Ucrânia",
      "sr-Cyrl": "Украјина",
      "sr-Latn": "Ukrajina",
      "zh_TW": "烏克蘭",
      "tr": "Ukrayna",
      "ro": "Ucraína",
      "ar": "أوكرانيا",
      "fa": "اوکراین",
      "yue": "烏克蘭"
    },
    flag: "🇺🇦",
    code: "UA",
    dialCode: "380",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "United Arab Emirates",
    nameTranslations: {
      "sk": "Spojené arabské emiráty",
      "se": "Ovttastuvvan Arábaemiráhtat",
      "pl": "Zjednoczone Emiraty Arabskie",
      "no": "De forente arabiske emirater",
      "ja": "アラブ首長国連邦",
      "it": "Emirati Arabi Uniti",
      "zh": "阿拉伯联合酋长国",
      "nl": "Verenigde Arabische Emiraten",
      "de": "Vereinigte Arabische Emirate",
      "fr": "Émirats arabes unis",
      "es": "Emiratos Árabes Unidos",
      "en": "United Arab Emirates",
      "pt_BR": "Emirados Árabes Unidos",
      "sr-Cyrl": "Уједињени Арапски Емирати",
      "sr-Latn": "Ujedinjeni Arapski Emirati",
      "zh_TW": "阿拉伯聯合大公國",
      "tr": "Birleşik Arap Emirlikleri",
      "ro": "Emiratele Arabe Unite",
      "ar": "الإمارات العربية المتحدة",
      "fa": "امارات متحده عربی",
      "yue": "阿拉伯聯合酋長國"
    },
    flag: "🇦🇪",
    code: "AE",
    dialCode: "971",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "United Kingdom",
    nameTranslations: {
      "sk": "Spojené kráľovstvo",
      "se": "Stuorra-Británnia",
      "pl": "Wielka Brytania",
      "no": "Storbritannia",
      "ja": "イギリス",
      "it": "Regno Unito",
      "zh": "英国",
      "nl": "Verenigd Koninkrijk",
      "de": "Vereinigtes Königreich",
      "fr": "Royaume-Uni",
      "es": "Reino Unido",
      "en": "United Kingdom",
      "pt_BR": "Reino Unido",
      "sr-Cyrl": "Уједињено Краљевство",
      "sr-Latn": "Ujedinjeno Kraljevstvo",
      "zh_TW": "英國",
      "tr": "Büyük Britanya ve Kuzey İrlanda Birleşik Krallığ",
      "ro": "Regatul Unit al Marii Britanii și Irlandei de Nord",
      "ar": "المملكة المتحدة",
      "fa": "بریتانیا",
      "yue": "大不列顛及北愛爾蘭聯合王國"
    },
    flag: "🇬🇧",
    code: "GB",
    dialCode: "44",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "United States",
    nameTranslations: {
      "sk": "Spojené štáty",
      "se": "Amerihká ovttastuvvan stáhtat",
      "pl": "Stany Zjednoczone",
      "no": "USA",
      "ja": "アメリカ合衆国",
      "it": "Stati Uniti",
      "zh": "美国",
      "nl": "Verenigde Staten",
      "de": "Vereinigte Staaten",
      "fr": "États-Unis",
      "es": "Estados Unidos",
      "en": "United States",
      "pt_BR": "Estados Unidos",
      "sr-Cyrl": "Сједињене Америчке Државе",
      "sr-Latn": "Sjedinjene Američke Države",
      "zh_TW": "美國",
      "tr": "Amerika Birleşik Devletleri",
      "ro": "Statele Unite ale Americii",
      "ar": "الولايات المتحدة",
      "fa": "ایالات متحده آمریکا",
      "yue": "美利堅郃眾囯"
    },
    flag: "🇺🇸",
    code: "US",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Uruguay",
    nameTranslations: {
      "sk": "Uruguaj",
      "se": "Uruguay",
      "pl": "Urugwaj",
      "no": "Uruguay",
      "ja": "ウルグアイ",
      "it": "Uruguay",
      "zh": "乌拉圭",
      "nl": "Uruguay",
      "de": "Uruguay",
      "fr": "Uruguay",
      "es": "Uruguay",
      "en": "Uruguay",
      "pt_BR": "Uruguai",
      "sr-Cyrl": "Уругвај",
      "sr-Latn": "Urugvaj",
      "zh_TW": "烏拉圭",
      "tr": "Uruguay",
      "ro": "Uruguay",
      "ar": "الأوروغواي",
      "fa": "اروگوئه",
      "yue": "烏拉圭"
    },
    flag: "🇺🇾",
    code: "UY",
    dialCode: "598",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Uzbekistan",
    nameTranslations: {
      "sk": "Uzbekistan",
      "se": "Usbekistan",
      "pl": "Uzbekistan",
      "no": "Usbekistan",
      "ja": "ウズベキスタン",
      "it": "Uzbekistan",
      "zh": "乌兹别克斯坦",
      "nl": "Oezbekistan",
      "de": "Usbekistan",
      "fr": "Ouzbékistan",
      "es": "Uzbekistán",
      "en": "Uzbekistan",
      "pt_BR": "Uzbequistão",
      "sr-Cyrl": "Узбекистан",
      "sr-Latn": "Uzbekistan",
      "zh_TW": "烏玆別克",
      "tr": "Özbekistan",
      "ro": "Uzbekistan",
      "ar": "أوزبكستان",
      "fa": "ازبکستان",
      "yue": "月即別"
    },
    flag: "🇺🇿",
    code: "UZ",
    dialCode: "998",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Vanuatu",
    nameTranslations: {
      "sk": "Vanuatu",
      "se": "Vanuatu",
      "pl": "Vanuatu",
      "no": "Vanuatu",
      "ja": "バヌアツ",
      "it": "Vanuatu",
      "zh": "瓦努阿图",
      "nl": "Vanuatu",
      "de": "Vanuatu",
      "fr": "Vanuatu",
      "es": "Vanuatu",
      "en": "Vanuatu",
      "pt_BR": "Vanuatu",
      "sr-Cyrl": "Вануату",
      "sr-Latn": "Vanuatu",
      "zh_TW": "瓦努阿圖",
      "tr": "Vanuatu",
      "ro": "Vanuatu",
      "ar": "فانواتو",
      "fa": "وانواتو",
      "yue": "瓦努阿圖"
    },
    flag: "🇻🇺",
    code: "VU",
    dialCode: "678",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Venezuela, Bolivarian Republic of Venezuela",
    nameTranslations: {
      "sk": "Venezuela",
      "se": "Venezuela",
      "pl": "Wenezuela",
      "no": "Venezuela",
      "ja": "ベネズエラ",
      "it": "Venezuela",
      "zh": "委内瑞拉",
      "nl": "Venezuela",
      "de": "Venezuela",
      "fr": "Venezuela",
      "es": "Venezuela",
      "en": "Venezuela",
      "pt_BR": "Venezuela",
      "sr-Cyrl": "Венецуела",
      "sr-Latn": "Venecuela",
      "zh_TW": "委內瑞拉",
      "tr": "Venezuela",
      "ro": "Venezuela",
      "ar": "فنزويلا",
      "fa": "ونزوئلا",
      "yue": "委內瑞拉（玻利瓦爾共和國）"
    },
    flag: "🇻🇪",
    code: "VE",
    dialCode: "58",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Vietnam",
    nameTranslations: {
      "sk": "Vietnam",
      "se": "Vietnam",
      "pl": "Wietnam",
      "no": "Vietnam",
      "ja": "ベトナム",
      "it": "Vietnam",
      "zh": "越南",
      "nl": "Vietnam",
      "de": "Vietnam",
      "fr": "Vietnam",
      "es": "Vietnam",
      "en": "Vietnam",
      "pt_BR": "Vietnã",
      "sr-Cyrl": "Вијетнам",
      "sr-Latn": "Vijetnam",
      "zh_TW": "越南",
      "tr": "Vietnam",
      "ro": "Vietnam",
      "ar": "فيتنام",
      "fa": "ویتنام",
      "yue": "越南"
    },
    flag: "🇻🇳",
    code: "VN",
    dialCode: "84",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Virgin Islands, British",
    nameTranslations: {
      "sk": "Britské Panenské ostrovy",
      "se": "Brittania Virgin-sullot",
      "pl": "Brytyjskie Wyspy Dziewicze",
      "no": "De britiske jomfruøyene",
      "ja": "英領ヴァージン諸島",
      "it": "Isole Vergini Britanniche",
      "zh": "英属维尔京群岛",
      "nl": "Britse Maagdeneilanden",
      "de": "Britische Jungferninseln",
      "fr": "Îles Vierges britanniques",
      "es": "Islas Vírgenes Británicas",
      "en": "British Virgin Islands",
      "pt_BR": "Ilhas Virgens Britânicas",
      "sr-Cyrl": "Британска Девичанска Острва",
      "sr-Latn": "Britanska Devičanska Ostrva",
      "zh_TW": "英屬維京群島",
      "tr": "Britanya Virjin Adaları",
      "ro": "Insulele Virgine Britanice",
      "ar": "جزر العذراء البريطانية",
      "fa": "جزایر ویرجین بریتانیا",
      "yue": "維爾京群島（英國）"
    },
    flag: "🇻🇬",
    code: "VG",
    dialCode: "1284",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Virgin Islands, U.S.",
    nameTranslations: {
      "sk": "Americké Panenské ostrovy",
      "se": "AOS Virgin-sullot",
      "pl": "Wyspy Dziewicze Stanów Zjednoczonych",
      "no": "De amerikanske jomfruøyene",
      "ja": "米領ヴァージン諸島",
      "it": "Isole Vergini Americane",
      "zh": "美属维尔京群岛",
      "nl": "Amerikaanse Maagdeneilanden",
      "de": "Amerikanische Jungferninseln",
      "fr": "Îles Vierges des États-Unis",
      "es": "Islas Vírgenes de EE. UU.",
      "en": "U.S. Virgin Islands",
      "pt_BR": "Ilhas Virgens Americanas",
      "sr-Cyrl": "Амепичка Девичанска Острва",
      "sr-Latn": "Američka Devičanska Ostrva",
      "zh_TW": "美屬維京群島",
      "tr": "Amerika Birleşik Devletleri Virjin Adaları",
      "ro": "Insulele Virgine Americane",
      "ar": "جزر العذراء الأمريكية",
      "fa": "جزایر ویرجین ایالات متحده آمریکا",
      "yue": "維爾京群島（美國）"
    },
    flag: "🇻🇮",
    code: "VI",
    dialCode: "1340",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Wallis and Futuna",
    nameTranslations: {
      "sk": "Wallis a Futuna",
      "se": "Wallis ja Futuna",
      "pl": "Wallis i Futuna",
      "no": "Wallis og Futuna",
      "ja": "ウォリス・フツナ",
      "it": "Wallis e Futuna",
      "zh": "瓦利斯和富图纳",
      "nl": "Wallis en Futuna",
      "de": "Wallis und Futuna",
      "fr": "Wallis-et-Futuna",
      "es": "Wallis y Futuna",
      "en": "Wallis & Futuna",
      "pt_BR": "Wallis e Futuna",
      "sr-Cyrl": "Валис и Футуна",
      "sr-Latn": "Valis i Futuna",
      "zh_TW": "瓦利斯和富圖那",
      "tr": "Wallis ve Futuna",
      "ro": "Wallis și Futuna",
      "ar": "والس وفوتونا",
      "fa": "والیس و فوتونا",
      "yue": "瓦利斯同富图纳"
    },
    flag: "🇼🇫",
    code: "WF",
    dialCode: "681",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Yemen",
    nameTranslations: {
      "sk": "Jemen",
      "se": "Jemen",
      "pl": "Jemen",
      "no": "Jemen",
      "ja": "イエメン",
      "it": "Yemen",
      "zh": "也门",
      "nl": "Jemen",
      "de": "Jemen",
      "fr": "Yémen",
      "es": "Yemen",
      "en": "Yemen",
      "pt_BR": "Iémen",
      "sr-Cyrl": "Јемен",
      "sr-Latn": "Jemen",
      "zh_TW": "葉門",
      "tr": "Yemen",
      "ro": "Yemen",
      "ar": "اليمن",
      "fa": "یمن",
      "yue": "也門"
    },
    flag: "🇾🇪",
    code: "YE",
    dialCode: "967",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Zambia",
    nameTranslations: {
      "sk": "Zambia",
      "se": "Zambia",
      "pl": "Zambia",
      "no": "Zambia",
      "ja": "ザンビア",
      "it": "Zambia",
      "zh": "赞比亚",
      "nl": "Zambia",
      "de": "Sambia",
      "fr": "Zambie",
      "es": "Zambia",
      "en": "Zambia",
      "pt_BR": "Zâmbia",
      "sr-Cyrl": "Замбија",
      "sr-Latn": "Zambija",
      "zh_TW": "贊比亞",
      "tr": "Zambiya",
      "ro": "Zambia",
      "ar": "زامبيا",
      "fa": "زامبیا",
      "yue": "贊比亞"
    },
    flag: "🇿🇲",
    code: "ZM",
    dialCode: "260",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
      name: "Zimbabwe",
      nameTranslations: {
        "sk": "Zimbabwe",
        "se": "Zimbabwe",
        "pl": "Zimbabwe",
        "no": "Zimbabwe",
        "ja": "ジンバブエ",
        "it": "Zimbabwe",
        "zh": "津巴布韦",
        "nl": "Zimbabwe",
        "de": "Simbabwe",
        "fr": "Zimbabwe",
        "es": "Zimbabue",
        "en": "Zimbabwe",
        "pt_BR": "Zimbábue",
        "sr-Cyrl": "Зимбабве",
        "sr-Latn": "Zimbabve",
        "zh_TW": "辛巴威",
        "tr": "Zimbabve",
        "ro": "Zimbabwe",
        "ar": "زيمبابوي",
        "fa": "زیمبابوه",
        "yue": "津巴布韋"
      },
      flag: "🇿🇼",
      code: "ZW",
      dialCode: "263",
      minLength: 9,
      maxLength: 9)
];
