/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_7.dart
/// Purpose: Country reference data, part 7 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart7 = <Country>[
  Country(
    name: "Namibia",
    nameTranslations: {
      "sk": "Namíbia",
      "se": "Namibia",
      "pl": "Namibia",
      "no": "Namibia",
      "ja": "ナミビア",
      "it": "Namibia",
      "zh": "纳米比亚",
      "nl": "Namibië",
      "de": "Namibia",
      "fr": "Namibie",
      "es": "Namibia",
      "en": "Namibia",
      "pt_BR": "Namibia",
      "sr-Cyrl": "Намибија",
      "sr-Latn": "Namibija",
      "zh_TW": "納米比亞",
      "tr": "Namibya",
      "ro": "Namibia",
      "ar": "ناميبيا",
      "fa": "نامیبیا",
      "yue": "納米比亞"
    },
    flag: "🇳🇦",
    code: "NA",
    dialCode: "264",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Nauru",
    nameTranslations: {
      "sk": "Nauru",
      "se": "Nauru",
      "pl": "Nauru",
      "no": "Nauru",
      "ja": "ナウル",
      "it": "Nauru",
      "zh": "瑙鲁",
      "nl": "Nauru",
      "de": "Nauru",
      "fr": "Nauru",
      "es": "Nauru",
      "en": "Nauru",
      "pt_BR": "Nauru",
      "sr-Cyrl": "Науру",
      "sr-Latn": "Nauru",
      "zh_TW": "諾魯",
      "tr": "Nauru",
      "ro": "Nauru",
      "ar": "ناورو",
      "fa": "نائورو",
      "yue": "瑙魯"
    },
    flag: "🇳🇷",
    code: "NR",
    dialCode: "674",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Nepal",
    nameTranslations: {
      "sk": "Nepál",
      "se": "Nepal",
      "pl": "Nepal",
      "no": "Nepal",
      "ja": "ネパール",
      "it": "Nepal",
      "zh": "尼泊尔",
      "nl": "Nepal",
      "de": "Nepal",
      "fr": "Népal",
      "es": "Nepal",
      "en": "Nepal",
      "pt_BR": "Nepal",
      "sr-Cyrl": "Непал",
      "sr-Latn": "Nepal",
      "zh_TW": "尼泊爾",
      "tr": "Nepal",
      "ro": "Nepal",
      "ar": "نيبال",
      "fa": "نپال",
      "yue": "尼泊爾"
    },
    flag: "🇳🇵",
    code: "NP",
    dialCode: "977",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Netherlands",
    nameTranslations: {
      "sk": "Holandsko",
      "se": "Vuolleeatnamat",
      "pl": "Holandia",
      "no": "Nederland",
      "ja": "オランダ",
      "it": "Paesi Bassi",
      "zh": "荷兰",
      "nl": "Nederland",
      "de": "Niederlande",
      "fr": "Pays-Bas",
      "es": "Países Bajos",
      "en": "Netherlands",
      "pt_BR": "Países Baixos",
      "sr-Cyrl": "Холандија",
      "sr-Latn": "Holandija",
      "zh_TW": "荷蘭",
      "tr": "Hollanda",
      "ro": "Olanda",
      "ar": "هولندا",
      "fa": "هلند",
      "yue": "荷蘭"
    },
    flag: "🇳🇱",
    code: "NL",
    dialCode: "31",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "New Caledonia",
    nameTranslations: {
      "sk": "Nová Kaledónia",
      "se": "Ođđa-Kaledonia",
      "pl": "Nowa Kaledonia",
      "no": "Ny-Caledonia",
      "ja": "ニューカレドニア",
      "it": "Nuova Caledonia",
      "zh": "新喀里多尼亚",
      "nl": "Nieuw-Caledonië",
      "de": "Neukaledonien",
      "fr": "Nouvelle-Calédonie",
      "es": "Nueva Caledonia",
      "en": "New Caledonia",
      "pt_BR": "Nova Caledônia",
      "sr-Cyrl": "Нова Каледонија",
      "sr-Latn": "Nova Kaledonija",
      "zh_TW": "新喀里多尼亞",
      "tr": "Yeni Kaledonya",
      "ro": "Noua Caledonie",
      "ar": "كاليدونيا الجديدة",
      "fa": "کالدونیای جدید",
      "yue": "新喀里多尼亚"
    },
    flag: "🇳🇨",
    code: "NC",
    dialCode: "687",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "New Zealand",
    nameTranslations: {
      "sk": "Nový Zéland",
      "se": "Ođđa-Selánda",
      "pl": "Nowa Zelandia",
      "no": "New Zealand",
      "ja": "ニュージーランド",
      "it": "Nuova Zelanda",
      "zh": "新西兰",
      "nl": "Nieuw-Zeeland",
      "de": "Neuseeland",
      "fr": "Nouvelle-Zélande",
      "es": "Nueva Zelanda",
      "en": "New Zealand",
      "pt_BR": "Nova Zelândia",
      "sr-Cyrl": "Нови Зеланд",
      "sr-Latn": "Novi Zeland",
      "zh_TW": "紐西蘭",
      "tr": "Yeni Zelanda",
      "ro": "Noua Zeelandă",
      "ar": "نيوزيلندا",
      "fa": "نیوزلند",
      "yue": "紐西蘭"
    },
    flag: "🇳🇿",
    code: "NZ",
    dialCode: "64",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Nicaragua",
    nameTranslations: {
      "sk": "Nikaragua",
      "se": "Nicaragua",
      "pl": "Nikaragua",
      "no": "Nicaragua",
      "ja": "ニカラグア",
      "it": "Nicaragua",
      "zh": "尼加拉瓜",
      "nl": "Nicaragua",
      "de": "Nicaragua",
      "fr": "Nicaragua",
      "es": "Nicaragua",
      "en": "Nicaragua",
      "pt_BR": "Nicarágua",
      "sr-Cyrl": "Никарагва",
      "sr-Latn": "Nikaragva",
      "zh_TW": "尼加拉瓜",
      "tr": "Nikaragua",
      "ro": "Nicaragua",
      "ar": "نيكاراغوا",
      "fa": "نیکاراگوئه",
      "yue": "尼加拉瓜"
    },
    flag: "🇳🇮",
    code: "NI",
    dialCode: "505",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Niger",
    nameTranslations: {
      "sk": "Niger",
      "se": "Niger",
      "pl": "Niger",
      "no": "Niger",
      "ja": "ニジェール",
      "it": "Niger",
      "zh": "尼日尔",
      "nl": "Niger",
      "de": "Niger",
      "fr": "Niger",
      "es": "Níger",
      "en": "Niger",
      "pt_BR": "Níger",
      "sr-Cyrl": "Нигер",
      "sr-Latn": "Niger",
      "zh_TW": "尼日爾",
      "tr": "Nijer",
      "ro": "Niger",
      "ar": "النيجر",
      "fa": "نیجر",
      "yue": "尼日爾"
    },
    flag: "🇳🇪",
    code: "NE",
    dialCode: "227",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Nigeria",
    nameTranslations: {
      "sk": "Nigéria",
      "se": "Nigeria",
      "pl": "Nigeria",
      "no": "Nigeria",
      "ja": "ナイジェリア",
      "it": "Nigeria",
      "zh": "尼日利亚",
      "nl": "Nigeria",
      "de": "Nigeria",
      "fr": "Nigéria",
      "es": "Nigeria",
      "en": "Nigeria",
      "pt_BR": "Nigéria",
      "sr-Cyrl": "Нигерија",
      "sr-Latn": "Nigerija",
      "zh_TW": "奈及利亞",
      "tr": "Nijerya",
      "ro": "Nigeria",
      "ar": "نيجيريا",
      "fa": "نیجریه",
      "yue": "尼日利亞"
    },
    flag: "🇳🇬",
    code: "NG",
    dialCode: "234",
    minLength: 10,
    maxLength: 11,
  ),
  Country(
    name: "Niue",
    nameTranslations: {
      "sk": "Niue",
      "se": "Niue",
      "pl": "Niue",
      "no": "Niue",
      "ja": "ニウエ",
      "it": "Niue",
      "zh": "纽埃",
      "nl": "Niue",
      "de": "Niue",
      "fr": "Niue",
      "es": "Niue",
      "en": "Niue",
      "pt_BR": "Niue",
      "sr-Cyrl": "Нијуе",
      "sr-Latn": "Nijue",
      "zh_TW": "紐埃",
      "tr": "Niue",
      "ro": "Niue",
      "ar": "نييوي",
      "fa": "نیووی",
      "yue": "紐埃"
    },
    flag: "🇳🇺",
    code: "NU",
    dialCode: "683",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: "Norfolk Island",
    nameTranslations: {
      "sk": "Norfolk",
      "se": "Norfolksullot",
      "pl": "Norfolk",
      "no": "Norfolkøya",
      "ja": "ノーフォーク島",
      "it": "Isola Norfolk",
      "zh": "诺福克岛",
      "nl": "Norfolk",
      "de": "Norfolkinsel",
      "fr": "Île Norfolk",
      "es": "Isla Norfolk",
      "en": "Norfolk Island",
      "pt_BR": "Ilha Norfolk",
      "sr-Cyrl": "Острво Норфок",
      "sr-Latn": "Ostrvo Norfok",
      "zh_TW": "諾福克島",
      "tr": "Norfolk Adası",
      "ro": "Insulele Norfolk",
      "ar": "جزيرة نورفولك",
      "fa": "جزیره نورفک",
      "yue": "诺福克岛"
    },
    flag: "🇳🇫",
    code: "NF",
    dialCode: "672",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Northern Mariana Islands",
    nameTranslations: {
      "sk": "Severné Mariány",
      "se": "Davvi-Mariánat",
      "pl": "Mariany Północne",
      "no": "Nord-Marianene",
      "ja": "北マリアナ諸島",
      "it": "Isole Marianne settentrionali",
      "zh": "北马里亚纳群岛",
      "nl": "Noordelijke Marianen",
      "de": "Nördliche Marianen",
      "fr": "Îles Mariannes du Nord",
      "es": "Islas Marianas del Norte",
      "en": "Northern Mariana Islands",
      "pt_BR": "Ilhas Marianas do Norte",
      "sr-Cyrl": "Северна Маријанска Острва",
      "sr-Latn": "Severna Marijanska Ostrva",
      "zh_TW": "北馬利安納群島",
      "tr": "Kuzey Mariana Adaları",
      "ro": "Insulelor Mariane de Nord",
      "ar": "جزر ماريانا الشمالية",
      "fa": "جزایر ماریانای شمالی",
      "yue": "北馬里亞納群島"
    },
    flag: "🇲🇵",
    code: "MP",
    dialCode: "1670",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Norway",
    nameTranslations: {
      "sk": "Nórsko",
      "se": "Norga",
      "pl": "Norwegia",
      "no": "Norge",
      "ja": "ノルウェー",
      "it": "Norvegia",
      "zh": "挪威",
      "nl": "Noorwegen",
      "de": "Norwegen",
      "fr": "Norvège",
      "es": "Noruega",
      "en": "Norway",
      "pt_BR": "Noruega",
      "sr-Cyrl": "Норвешка",
      "sr-Latn": "Norveška",
      "zh_TW": "挪威",
      "tr": "Norveç",
      "ro": "Norvegia",
      "ar": "النرويج",
      "fa": "نروژ",
      "yue": "挪威"
    },
    flag: "🇳🇴",
    code: "NO",
    dialCode: "47",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Oman",
    nameTranslations: {
      "sk": "Omán",
      "se": "Oman",
      "pl": "Oman",
      "no": "Oman",
      "ja": "オマーン",
      "it": "Oman",
      "zh": "阿曼",
      "nl": "Oman",
      "de": "Oman",
      "fr": "Oman",
      "es": "Omán",
      "en": "Oman",
      "pt_BR": "Omã",
      "sr-Cyrl": "Оман",
      "sr-Latn": "Oman",
      "zh_TW": "阿曼",
      "tr": "Umman",
      "ro": "Oman",
      "ar": "عمان",
      "fa": "عمان",
      "yue": "阿曼"
    },
    flag: "🇴🇲",
    code: "OM",
    dialCode: "968",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Pakistan",
    nameTranslations: {
      "sk": "Pakistan",
      "se": "Pakistan",
      "pl": "Pakistan",
      "no": "Pakistan",
      "ja": "パキスタン",
      "it": "Pakistan",
      "zh": "巴基斯坦",
      "nl": "Pakistan",
      "de": "Pakistan",
      "fr": "Pakistan",
      "es": "Pakistán",
      "en": "Pakistan",
      "pt_BR": "Paquistão",
      "sr-Cyrl": "Пакистан",
      "sr-Latn": "Pakistan",
      "zh_TW": "巴基斯坦",
      "tr": "Pakistan",
      "ro": "Pakistan",
      "ar": "باكستان",
      "fa": "پاکستان",
      "yue": "巴基斯坦"
    },
    flag: "🇵🇰",
    code: "PK",
    dialCode: "92",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Palau",
    nameTranslations: {
      "sk": "Palau",
      "se": "Palau",
      "pl": "Palau",
      "no": "Palau",
      "ja": "パラオ",
      "it": "Palau",
      "zh": "帕劳",
      "nl": "Palau",
      "de": "Palau",
      "fr": "Palaos",
      "es": "Palaos",
      "en": "Palau",
      "pt_BR": "Palau",
      "sr-Cyrl": "Палау",
      "sr-Latn": "Palau",
      "zh_TW": "帛琉",
      "tr": "Palau",
      "ro": "Palau",
      "ar": "بالاو",
      "fa": "پالائو",
      "yue": "帕劳"
    },
    flag: "🇵🇼",
    code: "PW",
    dialCode: "680",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Palestinian Territory, Occupied",
    nameTranslations: {
      "sk": "Palestínske územia",
      "se": "Palestina",
      "pl": "Terytoria Palestyńskie",
      "no": "Det palestinske området",
      "ja": "パレスチナ自治区",
      "it": "Territori palestinesi",
      "zh": "巴勒斯坦领土",
      "nl": "Palestijnse gebieden",
      "de": "Palästinensische Autonomiegebiete",
      "fr": "Territoires palestiniens",
      "es": "Territorios Palestinos",
      "en": "Palestinian Territories",
      "pt_BR": "Territórios Palestinos",
      "sr-Cyrl": "Палестина",
      "sr-Latn": "Palestina",
      "zh_TW": "巴勒斯坦",
      "tr": "Filistin",
      "ro": "Palestina",
      "ar": "فلسطين",
      "fa": "فلسطین",
      "yue": "巴勒斯坦，国"
    },
    flag: "🇵🇸",
    code: "PS",
    dialCode: "970",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Panama",
    nameTranslations: {
      "sk": "Panama",
      "se": "Panama",
      "pl": "Panama",
      "no": "Panama",
      "ja": "パナマ",
      "it": "Panamá",
      "zh": "巴拿马",
      "nl": "Panama",
      "de": "Panama",
      "fr": "Panama",
      "es": "Panamá",
      "en": "Panama",
      "pt_BR": "Panamá",
      "sr-Cyrl": "Панама",
      "sr-Latn": "Panama",
      "zh_TW": "巴拿馬",
      "tr": "Panama",
      "ro": "Panama",
      "ar": "بنما",
      "fa": "پاناما",
      "yue": "巴拿馬"
    },
    flag: "🇵🇦",
    code: "PA",
    dialCode: "507",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Papua New Guinea",
    nameTranslations: {
      "sk": "Papua-Nová Guinea",
      "se": "Papua-Ođđa-Guinea",
      "pl": "Papua-Nowa Gwinea",
      "no": "Papua Ny-Guinea",
      "ja": "パプアニューギニア",
      "it": "Papua Nuova Guinea",
      "zh": "巴布亚新几内亚",
      "nl": "Papoea-Nieuw-Guinea",
      "de": "Papua-Neuguinea",
      "fr": "Papouasie-Nouvelle-Guinée",
      "es": "Papúa Nueva Guinea",
      "en": "Papua New Guinea",
      "pt_BR": "Papua Nova Guiné",
      "sr-Cyrl": "Папуа Нова Гвинеја",
      "sr-Latn": "Papua Nova Gvineja",
      "zh_TW": "巴布亞新幾內亞",
      "tr": "Papua Yeni Gine",
      "ro": "Papua Noua Guinee",
      "ar": "بابوا غينيا الجديدة",
      "fa": "پاپوآ گینه نو",
      "yue": "巴布亚新几内亚"
    },
    flag: "🇵🇬",
    code: "PG",
    dialCode: "675",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Paraguay",
    nameTranslations: {
      "sk": "Paraguaj",
      "se": "Paraguay",
      "pl": "Paragwaj",
      "no": "Paraguay",
      "ja": "パラグアイ",
      "it": "Paraguay",
      "zh": "巴拉圭",
      "nl": "Paraguay",
      "de": "Paraguay",
      "fr": "Paraguay",
      "es": "Paraguay",
      "en": "Paraguay",
      "pt_BR": "Paraguai",
      "sr-Cyrl": "Парагвај",
      "sr-Latn": "Paragvaj",
      "zh_TW": "巴拉圭",
      "tr": "Paraguay",
      "ro": "Paraguay",
      "ar": "باراغواي",
      "fa": "پاراگوئه",
      "yue": "巴拉圭"
    },
    flag: "🇵🇾",
    code: "PY",
    dialCode: "595",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Peru",
    nameTranslations: {
      "sk": "Peru",
      "se": "Peru",
      "pl": "Peru",
      "no": "Peru",
      "ja": "ペルー",
      "it": "Perù",
      "zh": "秘鲁",
      "nl": "Peru",
      "de": "Peru",
      "fr": "Pérou",
      "es": "Perú",
      "en": "Peru",
      "pt_BR": "Peru",
      "sr-Cyrl": "Перу",
      "sr-Latn": "Peru",
      "zh_TW": "秘鲁",
      "tr": "Peru",
      "ro": "Peru",
      "ar": "بيرو",
      "fa": "پرو",
      "yue": "秘魯"
    },
    flag: "🇵🇪",
    code: "PE",
    dialCode: "51",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Philippines",
    nameTranslations: {
      "sk": "Filipíny",
      "se": "Filippiinnat",
      "pl": "Filipiny",
      "no": "Filippinene",
      "ja": "フィリピン",
      "it": "Filippine",
      "zh": "菲律宾",
      "nl": "Filipijnen",
      "de": "Philippinen",
      "fr": "Philippines",
      "es": "Filipinas",
      "en": "Philippines",
      "pt_BR": "Filipinas",
      "sr-Cyrl": "Филипини",
      "sr-Latn": "Filipini",
      "zh_TW": "菲律賓",
      "tr": "Filipinler",
      "ro": "Filipine",
      "ar": "الفلبين",
      "fa": "فیلیپین",
      "yue": "菲律賓"
    },
    flag: "🇵🇭",
    code: "PH",
    dialCode: "63",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Pitcairn",
    nameTranslations: {
      "sk": "Pitcairnove ostrovy",
      "se": "Pitcairn",
      "pl": "Pitcairn",
      "no": "Pitcairnøyene",
      "ja": "ピトケアン諸島",
      "it": "Isole Pitcairn",
      "zh": "皮特凯恩群岛",
      "nl": "Pitcairneilanden",
      "de": "Pitcairninseln",
      "fr": "Îles Pitcairn",
      "es": "Islas Pitcairn",
      "en": "Pitcairn Islands",
      "pt_BR": "Ilhas Pitcairn",
      "sr-Cyrl": "Острва Питкерн",
      "sr-Latn": "Ostrva Pitkern",
      "zh_TW": "皮特肯群島",
      "tr": "Pitcairn Adaları",
      "ro": "Insulele Pitcairn",
      "ar": "جزر بيتكيرن",
      "fa": "جزایر پیت‌کرن",
      "yue": "皮特凱恩"
    },
    flag: "🇵🇳",
    code: "PN",
    dialCode: "64",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Poland",
    nameTranslations: {
      "sk": "Poľsko",
      "se": "Polen",
      "pl": "Polska",
      "no": "Polen",
      "ja": "ポーランド",
      "it": "Polonia",
      "zh": "波兰",
      "nl": "Polen",
      "de": "Polen",
      "fr": "Pologne",
      "es": "Polonia",
      "en": "Poland",
      "pt_BR": "Polônia",
      "sr-Cyrl": "Пољска",
      "sr-Latn": "Poljska",
      "zh_TW": "波蘭",
      "tr": "Polonya",
      "ro": "Polonia",
      "ar": "بولندا",
      "fa": "لهستان",
      "yue": "波蘭"
    },
    flag: "🇵🇱",
    code: "PL",
    dialCode: "48",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Portugal",
    nameTranslations: {
      "sk": "Portugalsko",
      "se": "Portugála",
      "pl": "Portugalia",
      "no": "Portugal",
      "ja": "ポルトガル",
      "it": "Portogallo",
      "zh": "葡萄牙",
      "nl": "Portugal",
      "de": "Portugal",
      "fr": "Portugal",
      "es": "Portugal",
      "en": "Portugal",
      "pt_BR": "Portugal",
      "sr-Cyrl": "Португалија",
      "sr-Latn": "Portugalija",
      "zh_TW": "葡萄牙",
      "tr": "Portekiz",
      "ro": "Portugalia",
      "ar": "البرتغال",
      "fa": "پرتغال",
      "yue": "葡萄牙"
    },
    flag: "🇵🇹",
    code: "PT",
    dialCode: "351",
    minLength: 9,
    maxLength: 9,
  ),
];
