/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_5.dart
/// Purpose: Country reference data, part 5 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart5 = <Country>[
  Country(
    name: "Indonesia",
    nameTranslations: {
      "sk": "Indonézia",
      "se": "Indonesia",
      "pl": "Indonezja",
      "no": "Indonesia",
      "ja": "インドネシア",
      "it": "Indonesia",
      "zh": "印度尼西亚",
      "nl": "Indonesië",
      "de": "Indonesien",
      "fr": "Indonésie",
      "es": "Indonesia",
      "en": "Indonesia",
      "pt_BR": "Indonésia",
      "sr-Cyrl": "Индонезија",
      "sr-Latn": "Indonezija",
      "zh_TW": "印尼",
      "tr": "Endonezya",
      "ro": "Indonezia",
      "ar": "إندونيسيا",
      "fa": "اندونزی",
      "yue": "印尼"
    },
    flag: "🇮🇩",
    code: "ID",
    dialCode: "62",
    minLength: 10,
    maxLength: 13,
  ),
  Country(
    name: "Iran, Islamic Republic of Persian Gulf",
    nameTranslations: {
      "sk": "Irán",
      "se": "Iran",
      "pl": "Iran",
      "no": "Iran",
      "ja": "イラン",
      "it": "Iran",
      "zh": "伊朗",
      "nl": "Iran",
      "de": "Iran",
      "fr": "Iran",
      "es": "Irán",
      "en": "Iran",
      "pt_BR": "Irã",
      "sr-Cyrl": "Иран",
      "sr-Latn": "Iran",
      "zh_TW": "伊朗",
      "tr": "İran",
      "ro": "Iran",
      "ar": "إيران",
      "fa": "ایران",
      "yue": "伊朗"
    },
    flag: "🇮🇷",
    code: "IR",
    dialCode: "98",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Iraq",
    nameTranslations: {
      "sk": "Irak",
      "se": "Irak",
      "pl": "Irak",
      "no": "Irak",
      "ja": "イラク",
      "it": "Iraq",
      "zh": "伊拉克",
      "nl": "Irak",
      "de": "Irak",
      "fr": "Irak",
      "es": "Irak",
      "en": "Iraq",
      "pt_BR": "Iraque",
      "sr-Cyrl": "Ирак",
      "sr-Latn": "Irak",
      "zh_TW": "伊拉克",
      "tr": "Irak",
      "ro": "Irak",
      "ar": "العراق",
      "fa": "عراق",
      "yue": "伊拉克"
    },
    flag: "🇮🇶",
    code: "IQ",
    dialCode: "964",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Ireland",
    nameTranslations: {
      "sk": "Írsko",
      "se": "Irlánda",
      "pl": "Irlandia",
      "no": "Irland",
      "ja": "アイルランド",
      "it": "Irlanda",
      "zh": "爱尔兰",
      "nl": "Ierland",
      "de": "Irland",
      "fr": "Irlande",
      "es": "Irlanda",
      "en": "Ireland",
      "pt_BR": "Irlanda",
      "sr-Cyrl": "Ирска",
      "sr-Latn": "Irska",
      "zh_TW": "愛爾蘭",
      "tr": "İrlanda",
      "ro": "Irlanda",
      "ar": "أيرلندا",
      "fa": "ایرلند",
      "yue": "愛爾蘭"
    },
    flag: "🇮🇪",
    code: "IE",
    dialCode: "353",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "Isle of Man",
    nameTranslations: {
      "sk": "Ostrov Man",
      "se": "Mann-sullot",
      "pl": "Wyspa Man",
      "no": "Man",
      "ja": "マン島",
      "it": "Isola di Man",
      "zh": "马恩岛",
      "nl": "Isle of Man",
      "de": "Isle of Man",
      "fr": "Île de Man",
      "es": "Isla de Man",
      "en": "Isle of Man",
      "pt_BR": "Ilha de Man",
      "sr-Cyrl": "Острво Мен",
      "sr-Latn": "Ostrvo Men",
      "zh_TW": "曼島",
      "tr": "Man Adası",
      "ro": "Insula Man",
      "ar": "جزيرة مان",
      "fa": "جزیره مان",
      "yue": "马伊岛"
    },
    flag: "🇮🇲",
    code: "IM",
    dialCode: "44",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Israel",
    nameTranslations: {
      "sk": "Izrael",
      "se": "Israel",
      "pl": "Izrael",
      "no": "Israel",
      "ja": "イスラエル",
      "it": "Israele",
      "zh": "以色列",
      "nl": "Israël",
      "de": "Israel",
      "fr": "Israël",
      "es": "Israel",
      "en": "Israel",
      "pt_BR": "Israel",
      "sr-Cyrl": "Израел",
      "sr-Latn": "Izrael",
      "zh_TW": "以色列",
      "tr": "İsrail",
      "ro": "Israel",
      "ar": "إسرائيل",
      "fa": "إسرائيل",
      "yue": "以色列"
    },
    flag: "🇮🇱",
    code: "IL",
    dialCode: "972",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Campione d'Italia",
    nameTranslations: {
      "sk": "Taliansko",
      "se": "Itália",
      "pl": "Włochy",
      "no": "Italia",
      "ja": "イタリア",
      "it": "Italia",
      "zh": "意大利",
      "nl": "Italië",
      "de": "Italien",
      "fr": "Italie",
      "es": "Italia",
      "en": "Italy",
      "pt_BR": "Itália",
      "sr-Cyrl": "Италија",
      "sr-Latn": "Italija",
      "zh_TW": "義大利",
      "tr": "İtalya",
      "ro": "Italia",
      "ar": "إيطاليا",
      "fa": "ایتالیا",
      "yue": "意大利"
    },
    flag: "🇮🇹",
    code: "IT",
    dialCode: "41",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: "Jamaica",
    nameTranslations: {
      "sk": "Jamajka",
      "se": "Jamaica",
      "pl": "Jamajka",
      "no": "Jamaica",
      "ja": "ジャマイカ",
      "it": "Giamaica",
      "zh": "牙买加",
      "nl": "Jamaica",
      "de": "Jamaika",
      "fr": "Jamaïque",
      "es": "Jamaica",
      "en": "Jamaica",
      "pt_BR": "Jamaica",
      "sr-Cyrl": "Јамајка",
      "sr-Latn": "Jamajka",
      "zh_TW": "牙買加",
      "tr": "Jamaika",
      "ro": "Jamaica",
      "ar": "جامايكا",
      "fa": "جامائیکا",
      "yue": "牙買加"
    },
    flag: "🇯🇲",
    code: "JM",
    dialCode: "1876",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Japan",
    nameTranslations: {
      "sk": "Japonsko",
      "se": "Japána",
      "pl": "Japonia",
      "no": "Japan",
      "ja": "日本",
      "it": "Giappone",
      "zh": "日本",
      "nl": "Japan",
      "de": "Japan",
      "fr": "Japon",
      "es": "Japón",
      "en": "Japan",
      "pt_BR": "Japão",
      "sr-Cyrl": "Јапан",
      "sr-Latn": "Japan",
      "zh_TW": "日本",
      "tr": "Japonya",
      "ro": "Japonia",
      "ar": "اليابان",
      "fa": "ژاپن",
      "yue": "日本"
    },
    flag: "🇯🇵",
    code: "JP",
    dialCode: "81",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Jersey",
    nameTranslations: {
      "sk": "Jersey",
      "se": "Jersey",
      "pl": "Jersey",
      "no": "Jersey",
      "ja": "ジャージー",
      "it": "Jersey",
      "zh": "泽西岛",
      "nl": "Jersey",
      "de": "Jersey",
      "fr": "Jersey",
      "es": "Jersey",
      "en": "Jersey",
      "pt_BR": "Jersey",
      "sr-Cyrl": "Џерзи",
      "sr-Latn": "Džerzi",
      "zh_TW": "澤西",
      "tr": "Jersey",
      "ro": "Jersey",
      "ar": "جيرزي",
      "fa": "جرزی",
      "yue": "澤西"
    },
    flag: "🇯🇪",
    code: "JE",
    dialCode: "44",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Jordan",
    nameTranslations: {
      "sk": "Jordánsko",
      "se": "Jordánia",
      "pl": "Jordania",
      "no": "Jordan",
      "ja": "ヨルダン",
      "it": "Giordania",
      "zh": "约旦",
      "nl": "Jordanië",
      "de": "Jordanien",
      "fr": "Jordanie",
      "es": "Jordania",
      "en": "Jordan",
      "pt_BR": "Jordânia",
      "sr-Cyrl": "Јордан",
      "sr-Latn": "Jordan",
      "zh_TW": "約旦",
      "tr": "Mavera-i Ürdün",
      "ro": "Iordania",
      "ar": "الأردن",
      "fa": "اردن",
      "yue": "約旦"
    },
    flag: "🇯🇴",
    code: "JO",
    dialCode: "962",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Kazakhstan",
    nameTranslations: {
      "sk": "Kazachstan",
      "se": "Kasakstan",
      "pl": "Kazachstan",
      "no": "Kasakhstan",
      "ja": "カザフスタン",
      "it": "Kazakistan",
      "zh": "哈萨克斯坦",
      "nl": "Kazachstan",
      "de": "Kasachstan",
      "fr": "Kazakhstan",
      "es": "Kazajistán",
      "en": "Kazakhstan",
      "pt_BR": "Cazaquistão",
      "sr-Cyrl": "Казахстан",
      "sr-Latn": "Kazahstan",
      "zh_TW": "哈薩克",
      "tr": "Kazakistan",
      "ro": "Kazahstan",
      "ar": "كازاخستان",
      "fa": "قزاقستان",
      "yue": "哈薩克斯坦"
    },
    flag: "🇰🇿",
    code: "KZ",
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Kenya",
    nameTranslations: {
      "sk": "Keňa",
      "se": "Kenia",
      "pl": "Kenia",
      "no": "Kenya",
      "ja": "ケニア",
      "it": "Kenya",
      "zh": "肯尼亚",
      "nl": "Kenia",
      "de": "Kenia",
      "fr": "Kenya",
      "es": "Kenia",
      "en": "Kenya",
      "pt_BR": "Quênia",
      "sr-Cyrl": "Кенија",
      "sr-Latn": "Kenija",
      "zh_TW": "肯亞",
      "tr": "Kenya",
      "ro": "Kenya",
      "ar": "كينيا",
      "fa": "كنيا",
      "yue": "肯雅"
    },
    flag: "🇰🇪",
    code: "KE",
    dialCode: "254",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Kiribati",
    nameTranslations: {
      "sk": "Kiribati",
      "se": "Kiribati",
      "pl": "Kiribati",
      "no": "Kiribati",
      "ja": "キリバス",
      "it": "Kiribati",
      "zh": "基里巴斯",
      "nl": "Kiribati",
      "de": "Kiribati",
      "fr": "Kiribati",
      "es": "Kiribati",
      "en": "Kiribati",
      "pt_BR": "Kiribati",
      "sr-Cyrl": "Кирибати",
      "sr-Latn": "Kiribati",
      "zh_TW": "吉里巴斯",
      "tr": "Kiribati",
      "ro": "Kiribati",
      "ar": "كيريباتي",
      "fa": "کیریباتی",
      "yue": "基里巴斯"
    },
    flag: "🇰🇮",
    code: "KI",
    dialCode: "686",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Korea, Democratic People's Republic of Korea",
    nameTranslations: {
      "sk": "Severná Kórea",
      "se": "Davvi-Korea",
      "pl": "Korea Północna",
      "no": "Nord-Korea",
      "ja": "北朝鮮",
      "it": "Corea del Nord",
      "zh": "朝鲜",
      "nl": "Noord-Korea",
      "de": "Nordkorea",
      "fr": "Corée du Nord",
      "es": "Corea del Norte",
      "en": "North Korea",
      "pt_BR": "Coreia do Norte",
      "sr-Cyrl": "Северна Кореја",
      "sr-Latn": "Severna Koreja",
      "zh_TW": "北韓",
      "tr": "Kuzey Kore",
      "ro": "Coreea de Nord",
      "ar": "كوريا الشمالية",
      "fa": "کره شمالی",
      "yue": "朝鮮（朝鮮民主主義人民共咊囯）"
    },
    flag: "🇰🇵",
    code: "KP",
    dialCode: "850",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Korea, Republic of South Korea",
    nameTranslations: {
      "sk": "Južná Kórea",
      "se": "Mátta-Korea",
      "pl": "Korea Południowa",
      "no": "Sør-Korea",
      "ja": "韓国",
      "it": "Corea del Sud",
      "zh": "韩国",
      "nl": "Zuid-Korea",
      "de": "Südkorea",
      "fr": "Corée du Sud",
      "es": "Corea del Sur",
      "en": "South Korea",
      "pt_BR": "Coreia do Sul",
      "sr-Cyrl": "Јужна Кореја",
      "sr-Latn": "Južna Koreja",
      "zh_TW": "南韓",
      "tr": "Güney Kore",
      "ro": "Coreea de Sud",
      "ar": "كوريا الجنوبية",
      "fa": "کره جنوبی",
      "yue": "韓國（大韓民國）"
    },
    flag: "🇰🇷",
    code: "KR",
    dialCode: "82",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Kuwait",
    nameTranslations: {
      "sk": "Kuvajt",
      "se": "Kuwait",
      "pl": "Kuwejt",
      "no": "Kuwait",
      "ja": "クウェート",
      "it": "Kuwait",
      "zh": "科威特",
      "nl": "Koeweit",
      "de": "Kuwait",
      "fr": "Koweït",
      "es": "Kuwait",
      "en": "Kuwait",
      "pt_BR": "Kuwait",
      "sr-Cyrl": "Кувајт",
      "sr-Latn": "Kuvajt",
      "zh_TW": "科威特",
      "tr": "Kuveyt",
      "ro": "Kuweit",
      "ar": "الكويت",
      "fa": "کویت",
      "yue": "科威特"
    },
    flag: "🇰🇼",
    code: "KW",
    dialCode: "965",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Kyrgyzstan",
    nameTranslations: {
      "sk": "Kirgizsko",
      "se": "Kirgisistan",
      "pl": "Kirgistan",
      "no": "Kirgisistan",
      "ja": "キルギス",
      "it": "Kirghizistan",
      "zh": "吉尔吉斯斯坦",
      "nl": "Kirgizië",
      "de": "Kirgisistan",
      "fr": "Kirghizistan",
      "es": "Kirguistán",
      "en": "Kyrgyzstan",
      "pt_BR": "Quirguistão",
      "sr-Cyrl": "Киргистан",
      "sr-Latn": "Kirgistan",
      "zh_TW": "吉爾吉斯",
      "tr": "Kırgızistan",
      "ro": "Kîrgîzstan",
      "ar": "قيرغيزستان",
      "fa": "قرقیزستان",
      "yue": "吉爾吉斯斯坦"
    },
    flag: "🇰🇬",
    code: "KG",
    dialCode: "996",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Laos",
    nameTranslations: {
      "sk": "Laos",
      "se": "Laos",
      "pl": "Laos",
      "no": "Laos",
      "ja": "ラオス",
      "it": "Laos",
      "zh": "老挝",
      "nl": "Laos",
      "de": "Laos",
      "fr": "Laos",
      "es": "Laos",
      "en": "Laos",
      "pt_BR": "Laos",
      "sr-Cyrl": "Лаос",
      "sr-Latn": "Laos",
      "zh_TW": "寮國",
      "tr": "Laos",
      "ro": "Laos",
      "ar": "لاوس",
      "fa": "لائوس",
      "yue": "老撾人民民主共和國"
    },
    flag: "🇱🇦",
    code: "LA",
    dialCode: "856",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Latvia",
    nameTranslations: {
      "sk": "Lotyšsko",
      "se": "Látvia",
      "pl": "Łotwa",
      "no": "Latvia",
      "ja": "ラトビア",
      "it": "Lettonia",
      "zh": "拉脱维亚",
      "nl": "Letland",
      "de": "Lettland",
      "fr": "Lettonie",
      "es": "Letonia",
      "en": "Latvia",
      "pt_BR": "Letônia",
      "sr-Cyrl": "Летонија",
      "sr-Latn": "Letonija",
      "zh_TW": "拉托維亞",
      "tr": "Letonya",
      "ro": "Letonia",
      "ar": "لاتفيا",
      "fa": "لتونی",
      "yue": "拉脫維亞"
    },
    flag: "🇱🇻",
    code: "LV",
    dialCode: "371",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Lebanon",
    nameTranslations: {
      "sk": "Libanon",
      "se": "Libanon",
      "pl": "Liban",
      "no": "Libanon",
      "ja": "レバノン",
      "it": "Libano",
      "zh": "黎巴嫩",
      "nl": "Libanon",
      "de": "Libanon",
      "fr": "Liban",
      "es": "Líbano",
      "en": "Lebanon",
      "pt_BR": "Líbano",
      "sr-Cyrl": "Либан",
      "sr-Latn": "Liban",
      "zh_TW": "黎巴嫩",
      "tr": "Lübnan",
      "ro": "Liban",
      "ar": "لبنان",
      "fa": "لبنان",
      "yue": "黎巴嫩"
    },
    flag: "🇱🇧",
    code: "LB",
    dialCode: "961",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Lesotho",
    nameTranslations: {
      "sk": "Lesotho",
      "se": "Lesotho",
      "pl": "Lesotho",
      "no": "Lesotho",
      "ja": "レソト",
      "it": "Lesotho",
      "zh": "莱索托",
      "nl": "Lesotho",
      "de": "Lesotho",
      "fr": "Lesotho",
      "es": "Lesoto",
      "en": "Lesotho",
      "pt_BR": "Lesoto",
      "sr-Cyrl": "Лесото",
      "sr-Latn": "Lesoto",
      "zh_TW": "賴索托",
      "tr": "Lesotho",
      "ro": "Lesotho",
      "ar": "ليسوتو",
      "fa": "لسوتو",
      "yue": "萊索托"
    },
    flag: "🇱🇸",
    code: "LS",
    dialCode: "266",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Liberia",
    nameTranslations: {
      "sk": "Libéria",
      "se": "Liberia",
      "pl": "Liberia",
      "no": "Liberia",
      "ja": "リベリア",
      "it": "Liberia",
      "zh": "利比里亚",
      "nl": "Liberia",
      "de": "Liberia",
      "fr": "Libéria",
      "es": "Liberia",
      "en": "Liberia",
      "pt_BR": "Libéria",
      "sr-Cyrl": "Либерија",
      "sr-Latn": "Liberija",
      "zh_TW": "賴比瑞亞",
      "tr": "Liberya",
      "ro": "Liberia",
      "ar": "ليبيريا",
      "fa": "لیبریا",
      "yue": "利比里亞"
    },
    flag: "🇱🇷",
    code: "LR",
    dialCode: "231",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Libyan Arab Jamahiriya",
    nameTranslations: {
      "sk": "Líbya",
      "se": "Libya",
      "pl": "Libia",
      "no": "Libya",
      "ja": "リビア",
      "it": "Libia",
      "zh": "利比亚",
      "nl": "Libië",
      "de": "Libyen",
      "fr": "Libye",
      "es": "Libia",
      "en": "Libya",
      "pt_BR": "Líbia",
      "sr-Cyrl": "Либија",
      "sr-Latn": "Libija",
      "zh_TW": "利比亞",
      "tr": "Libya",
      "ro": "Libia",
      "ar": "ليبيا",
      "fa": "لیبی",
      "yue": "利比亞"
    },
    flag: "🇱🇾",
    code: "LY",
    dialCode: "218",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Liechtenstein",
    nameTranslations: {
      "sk": "Lichtenštajnsko",
      "se": "Liechtenstein",
      "pl": "Liechtenstein",
      "no": "Liechtenstein",
      "ja": "リヒテンシュタイン",
      "it": "Liechtenstein",
      "zh": "列支敦士登",
      "nl": "Liechtenstein",
      "de": "Liechtenstein",
      "fr": "Liechtenstein",
      "es": "Liechtenstein",
      "en": "Liechtenstein",
      "pt_BR": "Liechtenstein",
      "sr-Cyrl": "Лихтенштајн",
      "sr-Latn": "Lihtenštajn",
      "zh_TW": "列支敦斯登",
      "tr": "Lihtenştayn",
      "ro": "Liechtenstein",
      "ar": "ليختنشتاين",
      "fa": "لیختن‌اشتاین",
      "yue": "列支敦士登"
    },
    flag: "🇱🇮",
    code: "LI",
    dialCode: "423",
    minLength: 9,
    maxLength: 9,
  ),
];
