/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_4.dart
/// Purpose: Country reference data, part 4 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart4 = <Country>[
  Country(
    name: "French Southern Territories",
    nameTranslations: {
      "sk": "Francúzske južné a antarktické územia",
      "se": "French Southern Territories",
      "pl": "Francuskie Terytoria Południowe i Antarktyczne",
      "no": "De franske sørterritorier",
      "ja": "仏領極南諸島",
      "it": "Terre australi francesi",
      "zh": "法属南部领地",
      "nl": "Franse Gebieden in de zuidelijke Indische Oceaan",
      "de": "Französische Süd- und Antarktisgebiete",
      "fr": "Terres australes françaises",
      "es": "Territorios Australes Franceses",
      "en": "French Southern Territories",
      "pt_BR": "Territórios Franceses do Sul",
      "sr-Cyrl": "Француске јужне и антарктичке земље",
      "sr-Latn": "Francuske južne i antarktičke zemlje",
      "zh_TW": "法屬南部屬地",
      "tr": "Fransız Güney ve Antarktika Toprakları",
      "ro": "Teritoriile australe și antarctice franceze",
      "ar": "أراض فرنسية جنوبية وأنتارتيكية",
      "fa": "سرزمین‌های جنوبی فرانسه",
      "yue": "法國南部領土"
    },
    flag: "🇹🇫",
    code: "TF",
    dialCode: "262",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Gabon",
    nameTranslations: {
      "sk": "Gabon",
      "se": "Gabon",
      "pl": "Gabon",
      "no": "Gabon",
      "ja": "ガボン",
      "it": "Gabon",
      "zh": "加蓬",
      "nl": "Gabon",
      "de": "Gabun",
      "fr": "Gabon",
      "es": "Gabón",
      "en": "Gabon",
      "pt_BR": "Gabão",
      "sr-Cyrl": "Габон",
      "sr-Latn": "Gabon",
      "zh_TW": "加彭",
      "tr": "Gabon",
      "ro": "Gabon",
      "ar": "الغابون",
      "fa": "گابن",
      "yue": "加蓬"
    },
    flag: "🇬🇦",
    code: "GA",
    dialCode: "241",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Gambia",
    nameTranslations: {
      "sk": "Gambia",
      "se": "Gámbia",
      "pl": "Gambia",
      "no": "Gambia",
      "ja": "ガンビア",
      "it": "Gambia",
      "zh": "冈比亚",
      "nl": "Gambia",
      "de": "Gambia",
      "fr": "Gambie",
      "es": "Gambia",
      "en": "Gambia",
      "pt_BR": "Gâmbia",
      "sr-Cyrl": "Гамбија",
      "sr-Latn": "Gambija",
      "zh_TW": "岡比亞",
      "tr": "Gambiya",
      "ro": "Gambia",
      "ar": "غامبيا",
      "fa": "گامبیا",
      "yue": "岡比亞"
    },
    flag: "🇬🇲",
    code: "GM",
    dialCode: "220",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Georgia",
    nameTranslations: {
      "sk": "Gruzínsko",
      "se": "Georgia",
      "pl": "Gruzja",
      "no": "Georgia",
      "ja": "ジョージア",
      "it": "Georgia",
      "zh": "格鲁吉亚",
      "nl": "Georgië",
      "de": "Georgien",
      "fr": "Géorgie",
      "es": "Georgia",
      "en": "Georgia",
      "pt_BR": "Georgia",
      "sr-Cyrl": "Грузија",
      "sr-Latn": "Gruzija",
      "zh_TW": "喬治亞",
      "tr": "Gürcistan",
      "ro": "Georgia",
      "ar": "جورجيا",
      "fa": "گرجستان",
      "yue": "格魯吉亞"
    },
    flag: "🇬🇪",
    code: "GE",
    dialCode: "995",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: "Germany",
    nameTranslations: {
      "sk": "Nemecko",
      "se": "Duiska",
      "pl": "Niemcy",
      "no": "Tyskland",
      "ja": "ドイツ",
      "it": "Germania",
      "zh": "德国",
      "nl": "Duitsland",
      "de": "Deutschland",
      "fr": "Allemagne",
      "es": "Alemania",
      "en": "Germany",
      "pt_BR": "Alemanha",
      "sr-Cyrl": "Немачка",
      "sr-Latn": "Nemačka",
      "zh_TW": "德國",
      "tr": "Almanya",
      "ro": "Germania",
      "ar": "ألمانيا",
      "fa": "آلمان",
      "yue": "德國"
    },
    flag: "🇩🇪",
    code: "DE",
    dialCode: "49",
    minLength: 9,
    maxLength: 13,
  ),
  Country(
    name: "Ghana",
    nameTranslations: {
      "sk": "Ghana",
      "se": "Ghana",
      "pl": "Ghana",
      "no": "Ghana",
      "ja": "ガーナ",
      "it": "Ghana",
      "zh": "加纳",
      "nl": "Ghana",
      "de": "Ghana",
      "fr": "Ghana",
      "es": "Ghana",
      "en": "Ghana",
      "pt_BR": "Gana",
      "sr-Cyrl": "Гана",
      "sr-Latn": "Gana",
      "zh_TW": "迦納",
      "tr": "Gana",
      "ro": "Ghana",
      "ar": "غانا",
      "fa": "غنا",
      "yue": "加納"
    },
    flag: "🇬🇭",
    code: "GH",
    dialCode: "233",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Gibraltar",
    nameTranslations: {
      "sk": "Gibraltár",
      "se": "Gibraltar",
      "pl": "Gibraltar",
      "no": "Gibraltar",
      "ja": "ジブラルタル",
      "it": "Gibilterra",
      "zh": "直布罗陀",
      "nl": "Gibraltar",
      "de": "Gibraltar",
      "fr": "Gibraltar",
      "es": "Gibraltar",
      "en": "Gibraltar",
      "pt_BR": "Gibraltar",
      "sr-Cyrl": "Гибралтар",
      "sr-Latn": "Gibraltar",
      "zh_TW": "直布羅陀",
      "tr": "Cebelitarık",
      "ro": "Gibraltar",
      "ar": "جبل طارق",
      "fa": "جبل الطارق",
      "yue": "直布羅陀"
    },
    flag: "🇬🇮",
    code: "GI",
    dialCode: "350",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Greece",
    nameTranslations: {
      "sk": "Grécko",
      "se": "Greika",
      "pl": "Grecja",
      "no": "Hellas",
      "ja": "ギリシャ",
      "it": "Grecia",
      "zh": "希腊",
      "nl": "Griekenland",
      "de": "Griechenland",
      "fr": "Grèce",
      "es": "Grecia",
      "en": "Greece",
      "pt_BR": "Grécia",
      "sr-Cyrl": "Грчка",
      "sr-Latn": "Grčka",
      "zh_TW": "希臘",
      "tr": "Yunanistan",
      "ro": "Grecia",
      "ar": "اليونان",
      "fa": "یونان",
      "yue": "希臘"
    },
    flag: "🇬🇷",
    code: "GR",
    dialCode: "30",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Greenland",
    nameTranslations: {
      "sk": "Grónsko",
      "se": "Kalaallit Nunaat",
      "pl": "Grenlandia",
      "no": "Grønland",
      "ja": "グリーンランド",
      "it": "Groenlandia",
      "zh": "格陵兰",
      "nl": "Groenland",
      "de": "Grönland",
      "fr": "Groenland",
      "es": "Groenlandia",
      "en": "Greenland",
      "pt_BR": "Groenlândia",
      "sr-Cyrl": "Гренланд",
      "sr-Latn": "Grenland",
      "zh_TW": "格陵蘭",
      "tr": "Grönland",
      "ro": "Groenlanda",
      "ar": "جرينلاند",
      "fa": "گرینلند",
      "yue": "格陵蘭"
    },
    flag: "🇬🇱",
    code: "GL",
    dialCode: "299",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Grenada",
    nameTranslations: {
      "sk": "Grenada",
      "se": "Grenada",
      "pl": "Grenada",
      "no": "Grenada",
      "ja": "グレナダ",
      "it": "Grenada",
      "zh": "格林纳达",
      "nl": "Grenada",
      "de": "Grenada",
      "fr": "Grenade",
      "es": "Granada",
      "en": "Grenada",
      "pt_BR": "Grenada",
      "sr-Cyrl": "Гренада",
      "sr-Latn": "Grenada",
      "zh_TW": "格林納達",
      "tr": "Grenada",
      "ro": "Grenada",
      "ar": "غرينادا",
      "fa": "گرنادا",
      "yue": "格林納達"
    },
    flag: "🇬🇩",
    code: "GD",
    dialCode: "1473",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Guadeloupe",
    nameTranslations: {
      "sk": "Guadeloupe",
      "se": "Guadeloupe",
      "pl": "Gwadelupa",
      "no": "Guadeloupe",
      "ja": "グアドループ",
      "it": "Guadalupa",
      "zh": "瓜德罗普",
      "nl": "Guadeloupe",
      "de": "Guadeloupe",
      "fr": "Guadeloupe",
      "es": "Guadalupe",
      "en": "Guadeloupe",
      "pt_BR": "Guadalupe",
      "sr-Cyrl": "Гваделуп",
      "sr-Latn": "Gvadelup",
      "zh_TW": "瓜地洛普",
      "tr": "Guadeloupe",
      "ro": "Guadelupa",
      "ar": "غوادلوب",
      "fa": "گوادلوپ",
      "yue": "瓜德罗普"
    },
    flag: "🇬🇵",
    code: "GP",
    dialCode: "590",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Guam",
    nameTranslations: {
      "sk": "Guam",
      "se": "Guam",
      "pl": "Guam",
      "no": "Guam",
      "ja": "グアム",
      "it": "Guam",
      "zh": "关岛",
      "nl": "Guam",
      "de": "Guam",
      "fr": "Guam",
      "es": "Guam",
      "en": "Guam",
      "pt_BR": "Guam",
      "sr-Cyrl": "Гвам",
      "sr-Latn": "Gvam",
      "zh_TW": "關島",
      "tr": "Guam",
      "ro": "Guam",
      "ar": "غوام",
      "fa": "گوام",
      "yue": "關島"
    },
    flag: "🇬🇺",
    code: "GU",
    dialCode: "1671",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Guatemala",
    nameTranslations: {
      "sk": "Guatemala",
      "se": "Guatemala",
      "pl": "Gwatemala",
      "no": "Guatemala",
      "ja": "グアテマラ",
      "it": "Guatemala",
      "zh": "危地马拉",
      "nl": "Guatemala",
      "de": "Guatemala",
      "fr": "Guatemala",
      "es": "Guatemala",
      "en": "Guatemala",
      "pt_BR": "Guatemala",
      "sr-Cyrl": "Гватемала",
      "sr-Latn": "Gvatemala",
      "zh_TW": "瓜地馬拉",
      "tr": "Guatemala",
      "ro": "Guatemala",
      "ar": "غواتيمالا",
      "fa": "گواتمالا",
      "yue": "危地馬拉"
    },
    flag: "🇬🇹",
    code: "GT",
    dialCode: "502",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Guernsey",
    nameTranslations: {
      "sk": "Guernsey",
      "se": "Guernsey",
      "pl": "Guernsey",
      "no": "Guernsey",
      "ja": "ガーンジー",
      "it": "Guernsey",
      "zh": "根西岛",
      "nl": "Guernsey",
      "de": "Guernsey",
      "fr": "Guernesey",
      "es": "Guernsey",
      "en": "Guernsey",
      "pt_BR": "Guernsey",
      "sr-Cyrl": "Гернзи",
      "sr-Latn": "Gernzi",
      "zh_TW": "根息島",
      "tr": "Guernsey",
      "ro": "Guernsey",
      "ar": "غيرنزي",
      "fa": "گرنزی",
      "yue": "格恩西島"
    },
    flag: "🇬🇬",
    code: "GG",
    dialCode: "44",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Guinea",
    nameTranslations: {
      "sk": "Guinea",
      "se": "Guinea",
      "pl": "Gwinea",
      "no": "Guinea",
      "ja": "ギニア",
      "it": "Guinea",
      "zh": "几内亚",
      "nl": "Guinee",
      "de": "Guinea",
      "fr": "Guinée",
      "es": "Guinea",
      "en": "Guinea",
      "pt_BR": "Guiné",
      "sr-Cyrl": "Гвинеја",
      "sr-Latn": "Gvineja",
      "zh_TW": "幾內亞",
      "tr": "Gine",
      "ro": "Guinea",
      "ar": "غينيا",
      "fa": "گینه",
      "yue": "幾內亞"
    },
    flag: "🇬🇳",
    code: "GN",
    dialCode: "224",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: "Guinea-Bissau",
    nameTranslations: {
      "sk": "Guinea-Bissau",
      "se": "Guinea-Bissau",
      "pl": "Gwinea Bissau",
      "no": "Guinea-Bissau",
      "ja": "ギニアビサウ",
      "it": "Guinea-Bissau",
      "zh": "几内亚比绍",
      "nl": "Guinee-Bissau",
      "de": "Guinea-Bissau",
      "fr": "Guinée-Bissau",
      "es": "Guinea-Bisáu",
      "en": "Guinea-Bissau",
      "pt_BR": "Guiné-bissau",
      "sr-Cyrl": "Гвинеја Бисао",
      "sr-Latn": "Gvineja Bisao",
      "zh_TW": "幾內亞比索",
      "tr": "Gine-Bissau",
      "ro": "Guineea-Bissau",
      "ar": "غينيا بيساو",
      "fa": "گینه بیسائو",
      "yue": "幾內亞比紹"
    },
    flag: "🇬🇼",
    code: "GW",
    dialCode: "245",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Guyana",
    nameTranslations: {
      "sk": "Guyana",
      "se": "Guyana",
      "pl": "Gujana",
      "no": "Guyana",
      "ja": "ガイアナ",
      "it": "Guyana",
      "zh": "圭亚那",
      "nl": "Guyana",
      "de": "Guyana",
      "fr": "Guyana",
      "es": "Guyana",
      "en": "Guyana",
      "pt_BR": "Guiana",
      "sr-Cyrl": "Гвајана",
      "sr-Latn": "Gvajana",
      "zh_TW": "蓋亞那",
      "tr": "Guyana",
      "ro": "Guyana",
      "ar": "غيانا",
      "fa": "گویان",
      "yue": "圭亞那"
    },
    flag: "🇬🇾",
    code: "GY",
    dialCode: "592",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Haiti",
    nameTranslations: {
      "sk": "Haiti",
      "se": "Haiti",
      "pl": "Haiti",
      "no": "Haiti",
      "ja": "ハイチ",
      "it": "Haiti",
      "zh": "海地",
      "nl": "Haïti",
      "de": "Haiti",
      "fr": "Haïti",
      "es": "Haití",
      "en": "Haiti",
      "pt_BR": "Haiti",
      "sr-Cyrl": "Хаити",
      "sr-Latn": "Haiti",
      "zh_TW": "海地",
      "tr": "Haiti",
      "ro": "Haiti",
      "ar": "هايتي",
      "fa": "هائیتی",
      "yue": "海地"
    },
    flag: "🇭🇹",
    code: "HT",
    dialCode: "509",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Heard Island and Mcdonald Islands",
    nameTranslations: {
      "sk": "Heardov ostrov a Macdonaldove ostrovy",
      "se": "Heard- ja McDonald-sullot",
      "pl": "Wyspy Heard i McDonalda",
      "no": "Heard- og McDonaldøyene",
      "ja": "ハード島・マクドナルド諸島",
      "it": "Isole Heard e McDonald",
      "zh": "赫德岛和麦克唐纳群岛",
      "nl": "Heard en McDonaldeilanden",
      "de": "Heard und McDonaldinseln",
      "fr": "Îles Heard et McDonald",
      "es": "Islas Heard y McDonald",
      "en": "Heard & McDonald Islands",
      "pt_BR": "Ilhas Heard e McDonald",
      "sr-Cyrl": "Острва Херд и Макдоналд",
      "sr-Latn": "Ostrva Herd i Makdonald",
      "zh_TW": "赫德暨麥當勞群島",
      "tr": "Heard Adası ve McDonald Adaları",
      "ro": "Insula Heard și Insulele McDonald",
      "ar": "جزيرة هيرد وجزر ماكدونالد",
      "fa": "جزیره هرد و جزایر مک‌دونالد",
      "yue": "赫德岛同麦克唐纳群岛"
    },
    flag: "🇭🇲",
    code: "HM",
    dialCode: "672",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Holy See (Vatican City State)",
    nameTranslations: {
      "sk": "Vatikán",
      "se": "Vatikána",
      "pl": "Watykan",
      "no": "Vatikanstaten",
      "ja": "バチカン市国",
      "it": "Città del Vaticano",
      "zh": "梵蒂冈",
      "nl": "Vaticaanstad",
      "de": "Vatikanstadt",
      "fr": "État de la Cité du Vatican",
      "es": "Ciudad del Vaticano",
      "en": "Vatican City",
      "pt_BR": "Cidade do Vaticano",
      "sr-Cyrl": "Ватикан",
      "sr-Latn": "Vatikan",
      "zh_TW": "梵蒂岡",
      "tr": "Vatikan",
      "ro": "Vatican",
      "ar": "الفاتيكان",
      "fa": "واتیکان",
      "yue": "梵蒂岡城國"
    },
    flag: "🇻🇦",
    code: "VA",
    dialCode: "379",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Honduras",
    nameTranslations: {
      "sk": "Honduras",
      "se": "Honduras",
      "pl": "Honduras",
      "no": "Honduras",
      "ja": "ホンジュラス",
      "it": "Honduras",
      "zh": "洪都拉斯",
      "nl": "Honduras",
      "de": "Honduras",
      "fr": "Honduras",
      "es": "Honduras",
      "en": "Honduras",
      "pt_BR": "Honduras",
      "sr-Cyrl": "Хондурас",
      "sr-Latn": "Honduras",
      "zh_TW": "宏都拉斯",
      "tr": "Honduras",
      "ro": "Honduras",
      "ar": "هندوراس",
      "fa": "هندوراس",
      "yue": "洪都拉斯"
    },
    flag: "🇭🇳",
    code: "HN",
    dialCode: "504",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Hong Kong",
    nameTranslations: {
      "sk": "Hongkong – OAO Číny",
      "se": "Hongkong",
      "pl": "SRA Hongkong (Chiny)",
      "no": "Hongkong S.A.R. Kina",
      "ja": "中華人民共和国香港特別行政区",
      "it": "RAS di Hong Kong",
      "zh": "中国香港特别行政区",
      "nl": "Hongkong SAR van China",
      "de": "Sonderverwaltungsregion Hongkong",
      "fr": "R.A.S. chinoise de Hong Kong",
      "es": "RAE de Hong Kong (China)",
      "en": "Hong Kong SAR China",
      "pt_BR": "RAE de Hong Kong China",
      "sr-Cyrl": "Хонг Конг",
      "sr-Latn": "Hong Kong",
      "zh_TW": "香港",
      "tr": "Hong Kong",
      "ro": "Hong Kong",
      "ar": "هونغ كونغ",
      "fa": "هنگ کنگ",
      "yue": "香港"
    },
    flag: "🇭🇰",
    code: "HK",
    dialCode: "852",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Hungary",
    nameTranslations: {
      "sk": "Maďarsko",
      "se": "Ungár",
      "pl": "Węgry",
      "no": "Ungarn",
      "ja": "ハンガリー",
      "it": "Ungheria",
      "zh": "匈牙利",
      "nl": "Hongarije",
      "de": "Ungarn",
      "fr": "Hongrie",
      "es": "Hungría",
      "en": "Hungary",
      "pt_BR": "Hungria",
      "sr-Cyrl": "Мађарска",
      "sr-Latn": "Mađarska",
      "zh_TW": "匈牙利",
      "tr": "Macaristan",
      "ro": "Ungaria",
      "ar": "المجر",
      "fa": "مجارستان",
      "yue": "匈牙利"
    },
    flag: "🇭🇺",
    code: "HU",
    dialCode: "36",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Iceland",
    nameTranslations: {
      "sk": "Island",
      "se": "Islánda",
      "pl": "Islandia",
      "no": "Island",
      "ja": "アイスランド",
      "it": "Islanda",
      "zh": "冰岛",
      "nl": "IJsland",
      "de": "Island",
      "fr": "Islande",
      "es": "Islandia",
      "en": "Iceland",
      "pt_BR": "Islândia",
      "sr-Cyrl": "Исланд",
      "sr-Latn": "Island",
      "zh_TW": "冰島",
      "tr": "İzlanda",
      "ro": "Islanda",
      "ar": "آيسلندا",
      "fa": "ایسلند",
      "yue": "冰島"
    },
    flag: "🇮🇸",
    code: "IS",
    dialCode: "354",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "India",
    nameTranslations: {
      "sk": "India",
      "se": "India",
      "pl": "Indie",
      "no": "India",
      "ja": "インド",
      "it": "India",
      "zh": "印度",
      "nl": "India",
      "de": "Indien",
      "fr": "Inde",
      "es": "India",
      "en": "India",
      "pt_BR": "Índia",
      "sr-Cyrl": "Индија",
      "sr-Latn": "Indija",
      "zh_TW": "印度",
      "tr": "Hindistan",
      "ro": "India",
      "ar": "الهند",
      "fa": "هند",
      "yue": "印度"
    },
    flag: "🇮🇳",
    code: "IN",
    dialCode: "91",
    minLength: 10,
    maxLength: 10,
  ),
];
