/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_3.dart
/// Purpose: Country reference data, part 3 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart3 = <Country>[
  Country(
    name: "Cook Islands",
    nameTranslations: {
      "sk": "Cookove ostrovy",
      "se": "Cook-sullot",
      "pl": "Wyspy Cooka",
      "no": "Cookøyene",
      "ja": "クック諸島",
      "it": "Isole Cook",
      "zh": "库克群岛",
      "nl": "Cookeilanden",
      "de": "Cookinseln",
      "fr": "Îles Cook",
      "es": "Islas Cook",
      "en": "Cook Islands",
      "pt_BR": "Ilhas Cook",
      "sr-Cyrl": "Кукова Острва",
      "sr-Latn": "Kukova Ostrva",
      "zh_TW": "庫克群島",
      "tr": "Cook Adaları",
      "ro": "Insulele Cook",
      "ar": "جزر كوك",
      "fa": "جزایر کوک",
      "yue": "庫克群島"
    },
    flag: "🇨🇰",
    code: "CK",
    dialCode: "682",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Costa Rica",
    nameTranslations: {
      "sk": "Kostarika",
      "se": "Costa Rica",
      "pl": "Kostaryka",
      "no": "Costa Rica",
      "ja": "コスタリカ",
      "it": "Costa Rica",
      "zh": "哥斯达黎加",
      "nl": "Costa Rica",
      "de": "Costa Rica",
      "fr": "Costa Rica",
      "es": "Costa Rica",
      "en": "Costa Rica",
      "pt_BR": "Costa Rica",
      "sr-Cyrl": "Коста Рика",
      "sr-Latn": "Kosta Rika",
      "zh_TW": "哥斯大黎加",
      "tr": "Kosta Rika",
      "ro": "Costa Rica",
      "ar": "كوستاريكا",
      "fa": "کاستاریکا",
      "yue": "哥斯達黎加"
    },
    flag: "🇨🇷",
    code: "CR",
    dialCode: "506",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Côte d'Ivoire",
    nameTranslations: {
      "sk": "Pobrežie Slonoviny",
      "se": "Elfenbenariddu",
      "pl": "Côte d'Ivoire",
      "no": "Elfenbenskysten",
      "ja": "コートジボワール",
      "it": "Costa d'Avorio",
      "zh": "科特迪瓦",
      "nl": "Ivoorkust",
      "de": "Côte d'Ivoire",
      "fr": "Côte d'Ivoire",
      "es": "Côte d'Ivoire",
      "en": "Côte d'Ivoire",
      "pt_BR": "Côte d'Ivoire",
      "sr-Cyrl": "Обала Слоноваче",
      "sr-Latn": "Obala Slonovače",
      "zh_TW": "象牙海岸",
      "tr": "Fildişi Kıyısı",
      "ro": "Coasta de fildeș",
      "ar": "ساحل العاج",
      "fa": "ساحل عاج",
      "yue": "科特迪瓦"
    },
    flag: "🇨🇮",
    code: "CI",
    dialCode: "225",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Croatia",
    nameTranslations: {
      "sk": "Chorvátsko",
      "se": "Kroátia",
      "pl": "Chorwacja",
      "no": "Kroatia",
      "ja": "クロアチア",
      "it": "Croazia",
      "zh": "克罗地亚",
      "nl": "Kroatië",
      "de": "Kroatien",
      "fr": "Croatie",
      "es": "Croacia",
      "en": "Croatia",
      "pt_BR": "Croácia",
      "sr-Cyrl": "Хрватска",
      "sr-Latn": "Hrvatska",
      "zh_TW": "克羅埃西亞",
      "tr": "Hırvatistan",
      "ro": "Croația",
      "ar": "كرواتيا",
      "fa": "کرواسی",
      "yue": "克羅地亞"
    },
    flag: "🇭🇷",
    code: "HR",
    dialCode: "385",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Cuba",
    nameTranslations: {
      "sk": "Kuba",
      "se": "Kuba",
      "pl": "Kuba",
      "no": "Cuba",
      "ja": "キューバ",
      "it": "Cuba",
      "zh": "古巴",
      "nl": "Cuba",
      "de": "Kuba",
      "fr": "Cuba",
      "es": "Cuba",
      "en": "Cuba",
      "pt_BR": "Cuba",
      "sr-Cyrl": "Куба",
      "sr-Latn": "Kuba",
      "zh_TW": "古巴",
      "tr": "Küba",
      "ro": "Cuba",
      "ar": "كوبا",
      "fa": "كوبا",
      "yue": "古巴"
    },
    flag: "🇨🇺",
    code: "CU",
    dialCode: "53",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Cyprus",
    nameTranslations: {
      "sk": "Cyprus",
      "se": "Kypros",
      "pl": "Cypr",
      "no": "Kypros",
      "ja": "キプロス",
      "it": "Cipro",
      "zh": "塞浦路斯",
      "nl": "Cyprus",
      "de": "Zypern",
      "fr": "Chypre",
      "es": "Chipre",
      "en": "Cyprus",
      "pt_BR": "Chipre",
      "sr-Cyrl": "Кипар",
      "sr-Latn": "Kipar",
      "zh_TW": "塞普勒斯",
      "tr": "Kıbrıs",
      "ro": "Cipru",
      "ar": "قبرص",
      "fa": "قبرس",
      "yue": "塞浦路斯"
    },
    flag: "🇨🇾",
    code: "CY",
    dialCode: "357",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Czech Republic",
    nameTranslations: {
      "sk": "Česko",
      "se": "Čeahkka",
      "pl": "Czechy",
      "no": "Tsjekkia",
      "ja": "チェコ",
      "it": "Cechia",
      "zh": "捷克",
      "nl": "Tsjechië",
      "de": "Tschechien",
      "fr": "Tchéquie",
      "es": "Chequia",
      "en": "Czechia",
      "pt_BR": "Czechia",
      "sr-Cyrl": "Чешка",
      "sr-Latn": "Češka",
      "zh_TW": "捷克",
      "tr": "Çek Cumhuriyeti",
      "ro": "Cehia",
      "ar": "جمهورية التشيك",
      "fa": "جمهوری چک",
      "yue": "捷克共和國"
    },
    flag: "🇨🇿",
    code: "CZ",
    dialCode: "420",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Denmark",
    nameTranslations: {
      "sk": "Dánsko",
      "se": "Dánmárku",
      "pl": "Dania",
      "no": "Danmark",
      "ja": "デンマーク",
      "it": "Danimarca",
      "zh": "丹麦",
      "nl": "Denemarken",
      "de": "Dänemark",
      "fr": "Danemark",
      "es": "Dinamarca",
      "en": "Denmark",
      "pt_BR": "Dinamarca",
      "sr-Cyrl": "Данска",
      "sr-Latn": "Danska",
      "zh_TW": "丹麥",
      "tr": "Danimarka",
      "ro": "Danemarca",
      "ar": "الدنمارك",
      "fa": "دانمارک",
      "yue": "丹麥"
    },
    flag: "🇩🇰",
    code: "DK",
    dialCode: "45",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Djibouti",
    nameTranslations: {
      "sk": "Džibutsko",
      "se": "Djibouti",
      "pl": "Dżibuti",
      "no": "Djibouti",
      "ja": "ジブチ",
      "it": "Gibuti",
      "zh": "吉布提",
      "nl": "Djibouti",
      "de": "Dschibuti",
      "fr": "Djibouti",
      "es": "Yibuti",
      "en": "Djibouti",
      "pt_BR": "Djibouti",
      "sr-Cyrl": "Џибути",
      "sr-Latn": "Džibuti",
      "zh_TW": "吉布地",
      "tr": "Cibuti",
      "ro": "Djibouti",
      "ar": "جيبوتي",
      "fa": "جیبوتی",
      "yue": "吉布提"
    },
    flag: "🇩🇯",
    code: "DJ",
    dialCode: "253",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Dominica",
    nameTranslations: {
      "sk": "Dominika",
      "se": "Dominica",
      "pl": "Dominika",
      "no": "Dominica",
      "ja": "ドミニカ国",
      "it": "Dominica",
      "zh": "多米尼克",
      "nl": "Dominica",
      "de": "Dominica",
      "fr": "Dominique",
      "es": "Dominica",
      "en": "Dominica",
      "pt_BR": "Dominica",
      "sr-Cyrl": "Доминика",
      "sr-Latn": "Dominika",
      "zh_TW": "多明尼加",
      "tr": "Dominika",
      "ro": "Dominica",
      "ar": "دومينيكا",
      "fa": "دومينيكا",
      "yue": "多米尼加"
    },
    flag: "🇩🇲",
    code: "DM",
    dialCode: "1767",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Dominican Republic",
    nameTranslations: {
      "sk": "Dominikánska republika",
      "se": "Dominikána dásseváldi",
      "pl": "Dominikana",
      "no": "Den dominikanske republikk",
      "ja": "ドミニカ共和国",
      "it": "Repubblica Dominicana",
      "zh": "多米尼加共和国",
      "nl": "Dominicaanse Republiek",
      "de": "Dominikanische Republik",
      "fr": "République dominicaine",
      "es": "República Dominicana",
      "en": "Dominican Republic",
      "pt_BR": "República Dominicana",
      "sr-Cyrl": "Доминиканска Република",
      "sr-Latn": "Dominikanska Republika",
      "zh_TW": "多明尼加共和國",
      "tr": "Dominik Cumhuriyeti",
      "ro": "Republica Dominicană",
      "ar": "جمهورية الدومينيكان",
      "fa": "جمهوری دومنیکن",
      "yue": "多明尼加共和國"
    },
    flag: "🇩🇴",
    code: "DO",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Ecuador",
    nameTranslations: {
      "sk": "Ekvádor",
      "se": "Ecuador",
      "pl": "Ekwador",
      "no": "Ecuador",
      "ja": "エクアドル",
      "it": "Ecuador",
      "zh": "厄瓜多尔",
      "nl": "Ecuador",
      "de": "Ecuador",
      "fr": "Équateur",
      "es": "Ecuador",
      "en": "Ecuador",
      "pt_BR": "Equador",
      "sr-Cyrl": "Еквадор",
      "sr-Latn": "Ekvador",
      "zh_TW": "厄瓜多",
      "tr": "Ekvador",
      "ro": "Ecuador",
      "ar": "الإكوادور",
      "fa": "اكوادور",
      "yue": "厄瓜多爾"
    },
    flag: "🇪🇨",
    code: "EC",
    dialCode: "593",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: "Egypt",
    nameTranslations: {
      "sk": "Egypt",
      "se": "Egypt",
      "pl": "Egipt",
      "no": "Egypt",
      "ja": "エジプト",
      "it": "Egitto",
      "zh": "埃及",
      "nl": "Egypt",
      "de": "Ägypt",
      "fr": "Égypte",
      "es": "Egipt",
      "en": "Egypt",
      "pt_BR": "Egito",
      "sr-Cyrl": "Египат",
      "sr-Latn": "Egipat",
      "zh_TW": "埃及",
      "tr": "Mısır",
      "ro": "Egipt",
      "ar": "مصر",
      "fa": "مصر",
      "yue": "埃及"
    },
    flag: "🇪🇬",
    code: "EG",
    dialCode: "20",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "El Salvador",
    nameTranslations: {
      "sk": "Salvádor",
      "se": "El Salvador",
      "pl": "Salwador",
      "no": "El Salvador",
      "ja": "エルサルバドル",
      "it": "El Salvador",
      "zh": "萨尔瓦多",
      "nl": "El Salvador",
      "de": "El Salvador",
      "fr": "Salvador",
      "es": "El Salvador",
      "en": "El Salvador",
      "pt_BR": "El Salvador",
      "sr-Cyrl": "Салвадор",
      "sr-Latn": "Salvador",
      "zh_TW": "薩爾瓦多",
      "tr": "El Salvador",
      "ro": "Salvador",
      "ar": "السلفادور",
      "fa": "ال سالوادور",
      "yue": "薩爾瓦多"
    },
    flag: "🇸🇻",
    code: "SV",
    dialCode: "503",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Equatorial Guinea",
    nameTranslations: {
      "sk": "Rovníková Guinea",
      "se": "Ekvatoriála Guinea",
      "pl": "Gwinea Równikowa",
      "no": "Ekvatorial-Guinea",
      "ja": "赤道ギニア",
      "it": "Guinea Equatoriale",
      "zh": "赤道几内亚",
      "nl": "Equatoriaal-Guinea",
      "de": "Äquatorialguinea",
      "fr": "Guinée équatoriale",
      "es": "Guinea Ecuatorial",
      "en": "Equatorial Guinea",
      "pt_BR": "Guiné Equatorial",
      "sr-Cyrl": "Екваторијална Гвинеја",
      "sr-Latn": "Ekvatorijalna Gvineja",
      "zh_TW": "赤道幾內亞",
      "tr": "Ekvator Ginesi",
      "ro": "Guineea Ecuatorială",
      "ar": "غينيا الاستوائية",
      "fa": "گینه استوایی",
      "yue": "赤道幾內亞"
    },
    flag: "🇬🇶",
    code: "GQ",
    dialCode: "240",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Eritrea",
    nameTranslations: {
      "sk": "Eritrea",
      "se": "Eritrea",
      "pl": "Erytrea",
      "no": "Eritrea",
      "ja": "エリトリア",
      "it": "Eritrea",
      "zh": "厄立特里亚",
      "nl": "Eritrea",
      "de": "Eritrea",
      "fr": "Érythrée",
      "es": "Eritrea",
      "en": "Eritrea",
      "pt_BR": "Eritreia",
      "sr-Cyrl": "Еритреја",
      "sr-Latn": "Eritreja",
      "zh_TW": "厄立特裡亞",
      "tr": "Eritre",
      "ro": "Eritreea",
      "ar": "إريتريا",
      "fa": "اریتره",
      "yue": "厄立特里亞"
    },
    flag: "🇪🇷",
    code: "ER",
    dialCode: "291",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Estonia",
    nameTranslations: {
      "sk": "Estónsko",
      "se": "Estlánda",
      "pl": "Estonia",
      "no": "Estland",
      "ja": "エストニア",
      "it": "Estonia",
      "zh": "爱沙尼亚",
      "nl": "Estland",
      "de": "Estland",
      "fr": "Estonie",
      "es": "Estonia",
      "en": "Estonia",
      "pt_BR": "Estônia",
      "sr-Cyrl": "Естонија",
      "sr-Latn": "Estonija",
      "zh_TW": "愛沙尼亞",
      "tr": "Estonya",
      "ro": "Estonia",
      "ar": "إستونيا",
      "fa": "استونی",
      "yue": "愛沙尼亞"
    },
    flag: "🇪🇪",
    code: "EE",
    dialCode: "372",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Ethiopia",
    nameTranslations: {
      "sk": "Etiópia",
      "se": "Etiopia",
      "pl": "Etiopia",
      "no": "Etiopia",
      "ja": "エチオピア",
      "it": "Etiopia",
      "zh": "埃塞俄比亚",
      "nl": "Ethiopië",
      "de": "Äthiopien",
      "fr": "Éthiopie",
      "es": "Etiopía",
      "en": "Ethiopia",
      "pt_BR": "Etiópia",
      "sr-Cyrl": "Етиопија",
      "sr-Latn": "Etiopija",
      "zh_TW": "伊索比亞",
      "tr": "Etiyopya",
      "ro": "Etiopia",
      "ar": "إثيوبيا",
      "fa": "اتیوپی",
      "yue": "埃塞俄比亞"
    },
    flag: "🇪🇹",
    code: "ET",
    dialCode: "251",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Falkland Islands (Malvinas)",
    nameTranslations: {
      "sk": "Falklandy",
      "se": "Falklandsullot",
      "pl": "Falklandy",
      "no": "Falklandsøyene",
      "ja": "フォークランド諸島",
      "it": "Isole Falkland",
      "zh": "福克兰群岛",
      "nl": "Falklandeilanden",
      "de": "Falklandinseln",
      "fr": "Îles Malouines",
      "es": "Islas Malvinas",
      "en": "Falkland Islands",
      "pt_BR": "Ilhas Falkland",
      "sr-Cyrl": "Фокландска Острва",
      "sr-Latn": "Foklandska Ostrva",
      "zh_TW": "福克蘭群島",
      "tr": "Falkland Adaları",
      "ro": "Insulele Falklands",
      "ar": "جزر فوكلاند",
      "fa": "جزایر فالکلند",
      "yue": "福克蘭群島（馬爾維納斯群島）"
    },
    flag: "🇫🇰",
    code: "FK",
    dialCode: "500",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Faroe Islands",
    nameTranslations: {
      "sk": "Faerské ostrovy",
      "se": "Fearsullot",
      "pl": "Wyspy Owcze",
      "no": "Færøyene",
      "ja": "フェロー諸島",
      "it": "Isole Fær Øer",
      "zh": "法罗群岛",
      "nl": "Faeröer",
      "de": "Färöer",
      "fr": "Îles Féroé",
      "es": "Islas Feroe",
      "en": "Faroe Islands",
      "pt_BR": "ilhas Faroe",
      "sr-Cyrl": "Фарска Острва",
      "sr-Latn": "Farska Ostrva",
      "zh_TW": "法羅群島",
      "tr": "Faroe Adaları",
      "ro": "Insulele Feroe",
      "ar": "جزر فارو",
      "fa": "جزایر فارو",
      "yue": "法羅群島"
    },
    flag: "🇫🇴",
    code: "FO",
    dialCode: "298",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Fiji",
    nameTranslations: {
      "sk": "Fidži",
      "se": "Fijisullot",
      "pl": "Fidżi",
      "no": "Fiji",
      "ja": "フィジー",
      "it": "Figi",
      "zh": "斐济",
      "nl": "Fiji",
      "de": "Fidschi",
      "fr": "Fidji",
      "es": "Fiyi",
      "en": "Fiji",
      "pt_BR": "Fiji",
      "sr-Cyrl": "Фиџи",
      "sr-Latn": "Fidži",
      "zh_TW": "斐濟",
      "tr": "Fiji",
      "ro": "Fiji",
      "ar": "فيجي",
      "fa": "فيجي",
      "yue": "斐濟"
    },
    flag: "🇫🇯",
    code: "FJ",
    dialCode: "679",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Finland",
    nameTranslations: {
      "sk": "Fínsko",
      "se": "Suopma",
      "pl": "Finlandia",
      "no": "Finland",
      "ja": "フィンランド",
      "it": "Finlandia",
      "zh": "芬兰",
      "nl": "Finland",
      "de": "Finnland",
      "fr": "Finlande",
      "es": "Finlandia",
      "en": "Finland",
      "pt_BR": "Finlândia",
      "sr-Cyrl": "Финска",
      "sr-Latn": "Finska",
      "zh_TW": "芬蘭",
      "tr": "Finlandiya",
      "ro": "Finlanda",
      "ar": "فنلندا",
      "fa": "فنلاند",
      "yue": "芬蘭"
    },
    flag: "🇫🇮",
    code: "FI",
    dialCode: "358",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "France",
    nameTranslations: {
      "sk": "Francúzsko",
      "se": "Frankriika",
      "pl": "Francja",
      "no": "Frankrike",
      "ja": "フランス",
      "it": "Francia",
      "zh": "法国",
      "nl": "Frankrijk",
      "de": "Frankreich",
      "fr": "France",
      "es": "Francia",
      "en": "France",
      "pt_BR": "França",
      "sr-Cyrl": "Француска",
      "sr-Latn": "Francuska",
      "zh_TW": "法國",
      "tr": "Fransa",
      "ro": "Franța",
      "ar": "فرنسا",
      "fa": "فرانسه",
      "yue": "法國"
    },
    flag: "🇫🇷",
    code: "FR",
    dialCode: "33",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "French Guiana",
    nameTranslations: {
      "sk": "Francúzska Guyana",
      "se": "Frankriikka Guayana",
      "pl": "Gujana Francuska",
      "no": "Fransk Guyana",
      "ja": "仏領ギアナ",
      "it": "Guyana francese",
      "zh": "法属圭亚那",
      "nl": "Frans-Guyana",
      "de": "Französisch-Guayana",
      "fr": "Guyane française",
      "es": "Guayana Francesa",
      "en": "French Guiana",
      "pt_BR": "Guiana Francesa",
      "sr-Cyrl": "Француска Гвајана",
      "sr-Latn": "Francuska Gvajana",
      "zh_TW": "法屬蓋亞那",
      "tr": "Fransız Guyanası",
      "ro": "Guiana Franceză",
      "ar": "غويانا الفرنسية",
      "fa": "گویان فرانسه",
      "yue": "法屬圭亞那"
    },
    flag: "🇬🇫",
    code: "GF",
    dialCode: "594",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "French Polynesia",
    nameTranslations: {
      "sk": "Francúzska Polynézia",
      "se": "Frankriikka Polynesia",
      "pl": "Polinezja Francuska",
      "no": "Fransk Polynesia",
      "ja": "仏領ポリネシア",
      "it": "Polinesia francese",
      "zh": "法属波利尼西亚",
      "nl": "Frans-Polynesië",
      "de": "Französisch-Polynesien",
      "fr": "Polynésie française",
      "es": "Polinesia Francesa",
      "en": "French Polynesia",
      "pt_BR": "Polinésia Francesa",
      "sr-Cyrl": "Француска Полинезија",
      "sr-Latn": "Francuska Polinezija",
      "zh_TW": "法屬玻里尼西亞",
      "tr": "Fransız Polinezyası",
      "ro": "Polinezia Franceză",
      "ar": "بولينزيا الفرنسية",
      "fa": "پلی‌نزی فرانسه",
      "yue": "法屬波利尼西亞"
    },
    flag: "🇵🇫",
    code: "PF",
    dialCode: "689",
    minLength: 6,
    maxLength: 6,
  ),
];
