/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_8.dart
/// Purpose: Country reference data, part 8 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart8 = <Country>[
  Country(
    name: "Puerto Rico",
    nameTranslations: {
      "sk": "Portoriko",
      "se": "Puerto Rico",
      "pl": "Portoryko",
      "no": "Puerto Rico",
      "ja": "プエルトリコ",
      "it": "Portorico",
      "zh": "波多黎各",
      "nl": "Puerto Rico",
      "de": "Puerto Rico",
      "fr": "Porto Rico",
      "es": "Puerto Rico",
      "en": "Puerto Rico",
      "pt_BR": "Porto Rico",
      "sr-Cyrl": "Порто Рико",
      "sr-Latn": "Porto Riko",
      "zh_TW": "波多黎各",
      "tr": "Porto Riko",
      "ro": "Puerto Rico",
      "ar": "بورتوريكو",
      "fa": "پورتوریکو",
      "yue": "波多黎各"
    },
    flag: "🇵🇷",
    code: "PR",
    dialCode: "1939",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Qatar",
    nameTranslations: {
      "sk": "Katar",
      "se": "Qatar",
      "pl": "Katar",
      "no": "Qatar",
      "ja": "カタール",
      "it": "Qatar",
      "zh": "卡塔尔",
      "nl": "Qatar",
      "de": "Katar",
      "fr": "Qatar",
      "es": "Catar",
      "en": "Qatar",
      "pt_BR": "Catar",
      "sr-Cyrl": "Катар",
      "sr-Latn": "Katar",
      "zh_TW": "卡達",
      "tr": "Katar",
      "ro": "Qatar",
      "ar": "قطر",
      "fa": "قطر",
      "yue": "卡塔爾"
    },
    flag: "🇶🇦",
    code: "QA",
    dialCode: "974",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Romania",
    nameTranslations: {
      "sk": "Rumunsko",
      "se": "Románia",
      "pl": "Rumunia",
      "no": "Romania",
      "ja": "ルーマニア",
      "it": "Romania",
      "zh": "罗马尼亚",
      "nl": "Roemenië",
      "de": "Rumänien",
      "fr": "Roumanie",
      "es": "Rumanía",
      "en": "Romania",
      "pt_BR": "Romênia",
      "sr-Cyrl": "Румунија",
      "sr-Latn": "Rumunija",
      "zh_TW": "羅馬尼亞",
      "tr": "Romanya",
      "ro": "România",
      "ar": "رومانيا",
      "fa": "رومانی",
      "yue": "羅馬尼亞"
    },
    flag: "🇷🇴",
    code: "RO",
    dialCode: "40",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Russia",
    nameTranslations: {
      "sk": "Rusko",
      "se": "Ruošša",
      "pl": "Rosja",
      "no": "Russland",
      "ja": "ロシア",
      "it": "Russia",
      "zh": "俄罗斯",
      "nl": "Rusland",
      "de": "Russland",
      "fr": "Russie",
      "es": "Rusia",
      "en": "Russia",
      "pt_BR": "Rússia",
      "sr-Cyrl": "Русија",
      "sr-Latn": "Rusija",
      "zh_TW": "俄羅斯",
      "tr": "Rusya",
      "ro": "Rusia",
      "ar": "روسيا",
      "fa": "روسیه",
      "yue": "俄儸斯聯邦"
    },
    flag: "🇷🇺",
    code: "RU",
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Rwanda",
    nameTranslations: {
      "sk": "Rwanda",
      "se": "Rwanda",
      "pl": "Rwanda",
      "no": "Rwanda",
      "ja": "ルワンダ",
      "it": "Ruanda",
      "zh": "卢旺达",
      "nl": "Rwanda",
      "de": "Ruanda",
      "fr": "Rwanda",
      "es": "Ruanda",
      "en": "Rwanda",
      "pt_BR": "Ruanda",
      "sr-Cyrl": "Руанда",
      "sr-Latn": "Ruanda",
      "zh_TW": "盧安達",
      "tr": "Ruanda",
      "ro": "Rwanda",
      "ar": "رواندا",
      "fa": "رواندا",
      "yue": "盧旺達"
    },
    flag: "🇷🇼",
    code: "RW",
    dialCode: "250",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Reunion",
    nameTranslations: {
      "sk": "Réunion",
      "se": "Réunion",
      "pl": "Reunion",
      "no": "Réunion",
      "ja": "レユニオン",
      "it": "Riunione",
      "zh": "留尼汪",
      "nl": "Réunion",
      "de": "Réunion",
      "fr": "La Réunion",
      "es": "Reunión",
      "en": "Réunion",
      "pt_BR": "Reunião",
      "sr-Cyrl": "Реинион",
      "sr-Latn": "Reinion",
      "zh_TW": "留尼旺",
      "tr": "La Réunion",
      "ro": "La Réunion",
      "ar": "لا ريونيون",
      "fa": "رئونیون",
      "yue": "留尼汪"
    },
    flag: "🇷🇪",
    code: "RE",
    dialCode: "262",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Saint Barthelemy",
    nameTranslations: {
      "sk": "Svätý Bartolomej",
      "se": "Saint Barthélemy",
      "pl": "Saint-Barthélemy",
      "no": "Saint-Barthélemy",
      "ja": "サン・バルテルミー",
      "it": "Saint-Barthélemy",
      "zh": "圣巴泰勒米",
      "nl": "Saint-Barthélemy",
      "de": "St. Barthélemy",
      "fr": "Saint-Barthélemy",
      "es": "San Bartolomé",
      "en": "St. Barthélemy",
      "pt_BR": "São Bartolomeu",
      "sr-Cyrl": "Сент Бартелеми",
      "sr-Latn": "Sent Bartelemi",
      "zh_TW": "聖巴瑟米",
      "tr": "Saint Barthélemy",
      "ro": "Saint Barthélemy",
      "ar": "سان بارتيلمي",
      "fa": "سن بارتلمی",
      "yue": "聖巴泰勒米"
    },
    flag: "🇧🇱",
    code: "BL",
    dialCode: "590",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    nameTranslations: {
      "sk": "Svätá Helena",
      "se": "Saint Helena",
      "pl": "Wyspa Świętej Heleny",
      "no": "St. Helena",
      "ja": "セントヘレナ",
      "it": "Sant'Elena",
      "zh": "圣赫勒拿",
      "nl": "Sint-Helena",
      "de": "St. Helena",
      "fr": "Sainte-Hélène",
      "es": "Santa Elena",
      "en": "St. Helena",
      "pt_BR": "Santa Helena",
      "sr-Cyrl": "Света Јелена, Асенсион и Тристан да Куња",
      "sr-Latn": "Sveta Jelena, Asension i Tristan de Kunja",
      "zh_TW": "聖凱倫拿島",
      "tr": "Saint Helena",
      "ro": "Sfânta Elena",
      "ar": "سانت هيلانة وأسينشين وتريستان دا كونا",
      "fa": "سنت هلن",
      "yue": "圣赫勒拿、阿森松同特里斯坦·达库尼亚"
    },
    flag: "🇸🇭",
    code: "SH",
    dialCode: "290",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: "Saint Kitts and Nevis",
    nameTranslations: {
      "sk": "Svätý Krištof a Nevis",
      "se": "Saint Kitts ja Nevis",
      "pl": "Saint Kitts i Nevis",
      "no": "Saint Kitts og Nevis",
      "ja": "セントクリストファー・ネーヴィス",
      "it": "Saint Kitts e Nevis",
      "zh": "圣基茨和尼维斯",
      "nl": "Saint Kitts en Nevis",
      "de": "St. Kitts und Nevis",
      "fr": "Saint-Christophe-et-Niévès",
      "es": "San Cristóbal y Nieves",
      "en": "St. Kitts & Nevis",
      "pt_BR": "São Cristóvão e Nevis",
      "sr-Cyrl": "Сент Китс и Невис",
      "sr-Latn": "Sent Kits i Nevis",
      "zh_TW": "聖克里斯多福及尼維斯",
      "tr": "Saint Kitts ve Nevis",
      "ro": "Sfântul Kitts și Nevis",
      "ar": "سانت كيتس ونيفيس",
      "fa": "سنت کیتس و نویس",
      "yue": "圣基茨同尼维斯"
    },
    flag: "🇰🇳",
    code: "KN",
    dialCode: "1869",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Saint Lucia",
    nameTranslations: {
      "sk": "Svätá Lucia",
      "se": "Saint Lucia",
      "pl": "Saint Lucia",
      "no": "St. Lucia",
      "ja": "セントルシア",
      "it": "Saint Lucia",
      "zh": "圣卢西亚",
      "nl": "Saint Lucia",
      "de": "St. Lucia",
      "fr": "Sainte-Lucie",
      "es": "Santa Lucía",
      "en": "St. Lucia",
      "pt_BR": "Santa Lúcia",
      "sr-Cyrl": "Света Луција",
      "sr-Latn": "Sveta Lucija",
      "zh_TW": "聖露西亞",
      "tr": "Saint Lucia",
      "ro": "Sfânta Elena",
      "ar": "سانت لوسيا",
      "fa": "سنت لوسیا",
      "yue": "聖盧西亞"
    },
    flag: "🇱🇨",
    code: "LC",
    dialCode: "1758",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Saint Martin",
    nameTranslations: {
      "sk": "Svätý Martin (fr.)",
      "se": "Frankriikka Saint Martin",
      "pl": "Saint-Martin",
      "no": "Saint-Martin",
      "ja": "サン・マルタン",
      "it": "Saint Martin",
      "zh": "法属圣马丁",
      "nl": "Saint-Martin",
      "de": "St. Martin",
      "fr": "Saint-Martin",
      "es": "San Martín",
      "en": "St. Martin",
      "pt_BR": "São Martinho",
      "sr-Cyrl": "Свети Мартин",
      "sr-Latn": "Sveti Martin",
      "zh_TW": "聖馬丁",
      "tr": "Saint Martin",
      "ro": "Sfântul Martin",
      "ar": "تجمع سان مارتين",
      "fa": "سن مارتن",
      "yue": "聖馬丁（法國部分）"
    },
    flag: "🇲🇫",
    code: "MF",
    dialCode: "590",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Saint Pierre and Miquelon",
    nameTranslations: {
      "sk": "Saint Pierre a Miquelon",
      "se": "Saint Pierre ja Miquelon",
      "pl": "Saint-Pierre i Miquelon",
      "no": "Saint-Pierre-et-Miquelon",
      "ja": "サンピエール島・ミクロン島",
      "it": "Saint-Pierre e Miquelon",
      "zh": "圣皮埃尔和密克隆群岛",
      "nl": "Saint-Pierre en Miquelon",
      "de": "St. Pierre und Miquelon",
      "fr": "Saint-Pierre-et-Miquelon",
      "es": "San Pedro y Miquelón",
      "en": "St. Pierre & Miquelon",
      "pt_BR": "São Pedro e Miquelon",
      "sr-Cyrl": "Сен Пјер и Микелон",
      "sr-Latn": "Sen Pjer i Mikelon",
      "zh_TW": "聖皮埃與密克隆群島",
      "tr": "Saint Pierre ve Miquelon",
      "ro": "Saint Pierre și Miquelon",
      "ar": "سان بيير وميكلون",
      "fa": "سن-پیر و میکلون",
      "yue": "聖皮埃尔同米克隆"
    },
    flag: "🇵🇲",
    code: "PM",
    dialCode: "508",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Saint Vincent and the Grenadines",
    nameTranslations: {
      "sk": "Svätý Vincent a Grenadíny",
      "se": "Saint Vincent ja Grenadine",
      "pl": "Saint Vincent i Grenadyny",
      "no": "St. Vincent og Grenadinene",
      "ja": "セントビンセント及びグレナディーン諸島",
      "it": "Saint Vincent e Grenadine",
      "zh": "圣文森特和格林纳丁斯",
      "nl": "Saint Vincent en de Grenadines",
      "de": "St. Vincent und die Grenadinen",
      "fr": "Saint-Vincent-et-les-Grenadines",
      "es": "San Vicente y las Granadinas",
      "en": "St. Vincent & Grenadines",
      "pt_BR": "São Vicente e Granadinas",
      "sr-Cyrl": "Свети Винсент и Гренадини",
      "sr-Latn": "Sveti Vinsent i Grenadini",
      "zh_TW": "聖文森及格瑞那丁",
      "tr": "Saint Vincent ve Grenadinler",
      "ro": "Sfântul Vincențiu și Grenadinele",
      "ar": "سانت فينسنت والغرينادين",
      "fa": "سنت وینسنت و گرنادین‌ها",
      "yue": "聖文森特同格林纳丁斯"
    },
    flag: "🇻🇨",
    code: "VC",
    dialCode: "1784",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Samoa",
    nameTranslations: {
      "sk": "Samoa",
      "se": "Samoa",
      "pl": "Samoa",
      "no": "Samoa",
      "ja": "サモア",
      "it": "Samoa",
      "zh": "萨摩亚",
      "nl": "Samoa",
      "de": "Samoa",
      "fr": "Samoa",
      "es": "Samoa",
      "en": "Samoa",
      "pt_BR": "Samoa",
      "sr-Cyrl": "Самоа",
      "sr-Latn": "Samoa",
      "zh_TW": "薩摩亞",
      "tr": "Samoa",
      "ro": "Samoa",
      "ar": "ساموا",
      "fa": "ساموآ",
      "yue": "薩摩亞"
    },
    flag: "🇼🇸",
    code: "WS",
    dialCode: "685",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "San Marino",
    nameTranslations: {
      "sk": "San Maríno",
      "se": "San Marino",
      "pl": "San Marino",
      "no": "San Marino",
      "ja": "サンマリノ",
      "it": "San Marino",
      "zh": "圣马力诺",
      "nl": "San Marino",
      "de": "San Marino",
      "fr": "Saint-Marin",
      "es": "San Marino",
      "en": "San Marino",
      "pt_BR": "San Marino",
      "sr-Cyrl": "Сан Марино",
      "sr-Latn": "San Marino",
      "zh_TW": "聖馬利諾",
      "tr": "San Marino",
      "ro": "San Marino",
      "ar": "سان مارينو",
      "fa": "سان مارینو",
      "yue": "聖馬力諾"
    },
    flag: "🇸🇲",
    code: "SM",
    dialCode: "378",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Sao Tome and Principe",
    nameTranslations: {
      "sk": "Svätý Tomáš a Princov ostrov",
      "se": "São Tomé ja Príncipe",
      "pl": "Wyspy Świętego Tomasza i Książęca",
      "no": "São Tomé og Príncipe",
      "ja": "サントメ・プリンシペ",
      "it": "São Tomé e Príncipe",
      "zh": "圣多美和普林西比",
      "nl": "Sao Tomé en Principe",
      "de": "São Tomé und Príncipe",
      "fr": "Sao Tomé-et-Principe",
      "es": "Santo Tomé y Príncipe",
      "en": "São Tomé & Príncipe",
      "pt_BR": "São Tomé e Príncipe",
      "sr-Cyrl": "Сао Томе и Принсипе",
      "sr-Latn": "Sao Tome i Prinsipe",
      "zh_TW": "聖多美普林西比",
      "tr": "São Tomé ve Príncipe",
      "ro": "Sao Tome şi Principe",
      "ar": "ساو تومي وبرينسيب",
      "fa": "سائوتومه و پرنسیپ",
      "yue": "聖多美和普林西比"
    },
    flag: "🇸🇹",
    code: "ST",
    dialCode: "239",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Saudi Arabia",
    nameTranslations: {
      "sk": "Saudská Arábia",
      "se": "Saudi-Arábia",
      "pl": "Arabia Saudyjska",
      "no": "Saudi-Arabia",
      "ja": "サウジアラビア",
      "it": "Arabia Saudita",
      "zh": "沙特阿拉伯",
      "nl": "Saoedi-Arabië",
      "de": "Saudi-Arabien",
      "fr": "Arabie saoudite",
      "es": "Arabia Saudí",
      "en": "Saudi Arabia",
      "pt_BR": "Arábia Saudita",
      "sr-Cyrl": "Саудијска Арабија",
      "sr-Latn": "Saudijska Arabija",
      "zh_TW": "沙烏地阿拉",
      "tr": "Suudi Arabistan",
      "ro": "Arabia Saudită",
      "ar": "السعودية",
      "fa": "عربستان سعودی",
      "yue": "沙地阿拉伯"
    },
    flag: "🇸🇦",
    code: "SA",
    dialCode: "966",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Senegal",
    nameTranslations: {
      "sk": "Senegal",
      "se": "Senegal",
      "pl": "Senegal",
      "no": "Senegal",
      "ja": "セネガル",
      "it": "Senegal",
      "zh": "塞内加尔",
      "nl": "Senegal",
      "de": "Senegal",
      "fr": "Sénégal",
      "es": "Senegal",
      "en": "Senegal",
      "pt_BR": "Senegal",
      "sr-Cyrl": "Сенегал",
      "sr-Latn": "Senegal",
      "zh_TW": "塞內加爾",
      "tr": "Senegal",
      "ro": "Senegal",
      "ar": "السنغال",
      "fa": "سنگال",
      "yue": "塞內加爾"
    },
    flag: "🇸🇳",
    code: "SN",
    dialCode: "221",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Serbia",
    nameTranslations: {
      "sk": "Srbsko",
      "se": "Serbia",
      "pl": "Serbia",
      "no": "Serbia",
      "ja": "セルビア",
      "it": "Serbia",
      "zh": "塞尔维亚",
      "nl": "Servië",
      "de": "Serbien",
      "fr": "Serbie",
      "es": "Serbia",
      "en": "Serbia",
      "pt_BR": "Sérvia",
      "sr-Cyrl": "Србија",
      "sr-Latn": "Srbija",
      "zh_TW": "塞爾維亞",
      "tr": "Sırbistan",
      "ro": "Serbia",
      "ar": "صربيا",
      "fa": "صربستان",
      "yue": "塞爾維亞"
    },
    flag: "🇷🇸",
    code: "RS",
    dialCode: "381",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Seychelles",
    nameTranslations: {
      "sk": "Seychely",
      "se": "Seychellsullot",
      "pl": "Seszele",
      "no": "Seychellene",
      "ja": "セーシェル",
      "it": "Seychelles",
      "zh": "塞舌尔",
      "nl": "Seychellen",
      "de": "Seychellen",
      "fr": "Seychelles",
      "es": "Seychelles",
      "en": "Seychelles",
      "pt_BR": "Seychelles",
      "sr-Cyrl": "Сејшели",
      "sr-Latn": "Sejšeli",
      "zh_TW": "塞席爾",
      "tr": "Seyşeller",
      "ro": "Seychelles",
      "ar": "سيشل",
      "fa": "سیشل",
      "yue": "塞舌爾"
    },
    flag: "🇸🇨",
    code: "SC",
    dialCode: "248",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Sierra Leone",
    nameTranslations: {
      "sk": "Sierra Leone",
      "se": "Sierra Leone",
      "pl": "Sierra Leone",
      "no": "Sierra Leone",
      "ja": "シエラレオネ",
      "it": "Sierra Leone",
      "zh": "塞拉利昂",
      "nl": "Sierra Leone",
      "de": "Sierra Leone",
      "fr": "Sierra Leone",
      "es": "Sierra Leona",
      "en": "Sierra Leone",
      "pt_BR": "Serra Leoa",
      "sr-Cyrl": "Сијера Леоне",
      "sr-Latn": "Sijera Leone",
      "zh_TW": "獅子山",
      "tr": "Sierra Leone",
      "ro": "Sierra Leone",
      "ar": "سيراليون",
      "fa": "سیرالئون",
      "yue": "塞拉利昂"
    },
    flag: "🇸🇱",
    code: "SL",
    dialCode: "232",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Singapore",
    nameTranslations: {
      "sk": "Singapur",
      "se": "Singapore",
      "pl": "Singapur",
      "no": "Singapore",
      "ja": "シンガポール",
      "it": "Singapore",
      "zh": "新加坡",
      "nl": "Singapore",
      "de": "Singapur",
      "fr": "Singapour",
      "es": "Singapur",
      "en": "Singapore",
      "pt_BR": "Cingapura",
      "sr-Cyrl": "Сингапур",
      "sr-Latn": "Singapur",
      "zh_TW": "新加坡",
      "tr": "Singapur",
      "ro": "Singapore",
      "ar": "سنغافورة",
      "fa": "سنگاپور",
      "yue": "星架坡"
    },
    flag: "🇸🇬",
    code: "SG",
    dialCode: "65",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Slovakia",
    nameTranslations: {
      "sk": "Slovensko",
      "se": "Slovákia",
      "pl": "Słowacja",
      "no": "Slovakia",
      "ja": "スロバキア",
      "it": "Slovacchia",
      "zh": "斯洛伐克",
      "nl": "Slowakije",
      "de": "Slowakei",
      "fr": "Slovaquie",
      "es": "Eslovaquia",
      "en": "Slovakia",
      "pt_BR": "Eslováquia",
      "sr-Cyrl": "Словачка",
      "sr-Latn": "Slovačka",
      "zh_TW": "斯洛伐克",
      "tr": "Slovakya",
      "ro": "Slovacia",
      "ar": "سلوفاكيا",
      "fa": "اسلواکی",
      "yue": "斯洛伐克"
    },
    flag: "🇸🇰",
    code: "SK",
    dialCode: "421",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Slovenia",
    nameTranslations: {
      "sk": "Slovinsko",
      "se": "Slovenia",
      "pl": "Słowenia",
      "no": "Slovenia",
      "ja": "スロベニア",
      "it": "Slovenia",
      "zh": "斯洛文尼亚",
      "nl": "Slovenië",
      "de": "Slowenien",
      "fr": "Slovénie",
      "es": "Eslovenia",
      "en": "Slovenia",
      "pt_BR": "Eslovênia",
      "sr-Cyrl": "Словеније",
      "sr-Latn": "Slovenija",
      "zh_TW": "斯洛維尼亞",
      "tr": "Slovenya",
      "ro": "Slovenia",
      "ar": "سلوفينيا",
      "fa": "اسلوونی",
      "yue": "斯洛文尼亞"
    },
    flag: "🇸🇮",
    code: "SI",
    dialCode: "386",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Solomon Islands",
    nameTranslations: {
      "sk": "Šalamúnove ostrovy",
      "se": "Salomon-sullot",
      "pl": "Wyspy Salomona",
      "no": "Salomonøyene",
      "ja": "ソロモン諸島",
      "it": "Isole Salomone",
      "zh": "所罗门群岛",
      "nl": "Salomonseilanden",
      "de": "Salomonen",
      "fr": "Îles Salomon",
      "es": "Islas Salomón",
      "en": "Solomon Islands",
      "pt_BR": "Ilhas Salomão",
      "sr-Cyrl": "Соломонска Острва",
      "sr-Latn": "Solomonska Ostrva",
      "zh_TW": "所羅門群島",
      "tr": "Solomon Adaları",
      "ro": "Insulele Solomon",
      "ar": "جزر سليمان",
      "fa": "جزایر سلیمان",
      "yue": "所羅門群島"
    },
    flag: "🇸🇧",
    code: "SB",
    dialCode: "677",
    minLength: 5,
    maxLength: 5,
  ),
];
