/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_9.dart
/// Purpose: Country reference data, part 9 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart9 = <Country>[
  Country(
    name: "Somalia",
    nameTranslations: {
      "sk": "Somálsko",
      "se": "Somália",
      "pl": "Somalia",
      "no": "Somalia",
      "ja": "ソマリア",
      "it": "Somalia",
      "zh": "索马里",
      "nl": "Somalië",
      "de": "Somalia",
      "fr": "Somalie",
      "es": "Somalia",
      "en": "Somalia",
      "pt_BR": "Somália",
      "sr-Cyrl": "Сомалија",
      "sr-Latn": "Somalija",
      "zh_TW": "索馬利亞",
      "tr": "Somali",
      "ro": "Somalia",
      "ar": "الصومال",
      "fa": "سومالی",
      "yue": "索馬里"
    },
    flag: "🇸🇴",
    code: "SO",
    dialCode: "252",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "South Africa",
    nameTranslations: {
      "sk": "Južná Afrika",
      "se": "Mátta-Afrihká",
      "pl": "Republika Południowej Afryki",
      "no": "Sør-Afrika",
      "ja": "南アフリカ",
      "it": "Sudafrica",
      "zh": "南非",
      "nl": "Zuid-Afrika",
      "de": "Südafrika",
      "fr": "Afrique du Sud",
      "es": "Sudáfrica",
      "en": "South Africa",
      "pt_BR": "África do Sul",
      "sr-Cyrl": "Јужноафричка Република",
      "sr-Latn": "Južnoafrička Republika",
      "zh_TW": "南非",
      "tr": "Güney Afrika",
      "ro": "Africa de Sud",
      "ar": "جنوب أفريقيا",
      "fa": "آفریقای جنوبی",
      "yue": "南非"
    },
    flag: "🇿🇦",
    code: "ZA",
    dialCode: "27",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "South Sudan",
    nameTranslations: {
      "sk": "Južný Sudán",
      "se": "Máttasudan",
      "pl": "Sudan Południowy",
      "no": "Sør-Sudan",
      "ja": "南スーダン",
      "it": "Sud Sudan",
      "zh": "南苏丹",
      "nl": "Zuid-Soedan",
      "de": "Südsudan",
      "fr": "Soudan du Sud",
      "es": "Sudán del Sur",
      "en": "South Sudan",
      "pt_BR": "Sudão do Sul",
      "sr-Cyrl": "Јужни Судан",
      "sr-Latn": "Južni Sudan",
      "zh_TW": "南蘇丹",
      "tr": "Güney Sudan",
      "ro": "Sudanul de Sud",
      "ar": "جنوب السودان",
      "fa": "سودان جنوبی",
      "yue": "南蘇丹"
    },
    flag: "🇸🇸",
    code: "SS",
    dialCode: "211",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "South Georgia and the South Sandwich Islands",
    nameTranslations: {
      "sk": "Južná Georgia a Južné Sandwichove ostrovy",
      "se": "Lulli Georgia ja Lulli Sandwich-sullot",
      "pl": "Georgia Południowa i Sandwich Południowy",
      "no": "Sør-Georgia og Sør-Sandwichøyene",
      "ja": "サウスジョージア・サウスサンドウィッチ諸島",
      "it": "Georgia del Sud e Sandwich australi",
      "zh": "南乔治亚和南桑威奇群岛",
      "nl": "Zuid-Georgia en Zuidelijke Sandwicheilanden",
      "de": "Südgeorgien und die Südlichen Sandwichinseln",
      "fr": "Géorgie du Sud et îles Sandwich du Sud",
      "es": "Islas Georgia del Sur y Sandwich del Sur",
      "en": "South Georgia & South Sandwich Islands",
      "pt_BR": "Geórgia do Sul e Ilhas Sandwich do Sul",
      "sr-Cyrl": "Јужна Џорџија и Јужна Сендвичка Острва",
      "sr-Latn": "Južna Džordžija i Južna Sendvička Ostrva",
      "zh_TW": "南喬治亞與南三明治群島 ",
      "tr": "Güney Georgia ve Güney Sandwich Adaları",
      "ro": "Georgia de Sud și Insulele Sandwich de Sud",
      "ar": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
      "fa": "جزایر جورجیای جنوبی و ساندویچ جنوبی",
      "yue": "南喬治亞州同南桑威奇群島"
    },
    flag: "🇬🇸",
    code: "GS",
    dialCode: "500",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Spain",
    nameTranslations: {
      "sk": "Španielsko",
      "se": "Spánia",
      "pl": "Hiszpania",
      "no": "Spania",
      "ja": "スペイン",
      "it": "Spagna",
      "zh": "西班牙",
      "nl": "Spanje",
      "de": "Spanien",
      "fr": "Espagne",
      "es": "España",
      "en": "Spain",
      "pt_BR": "Espanha",
      "sr-Cyrl": "Шпанија",
      "sr-Latn": "Španija",
      "zh_TW": "西班牙",
      "tr": "İspanya",
      "ro": "Spania",
      "ar": "إسبانيا",
      "fa": "اسپانیا",
      "yue": "西班牙"
    },
    flag: "🇪🇸",
    code: "ES",
    dialCode: "34",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Sri Lanka",
    nameTranslations: {
      "sk": "Srí Lanka",
      "se": "Sri Lanka",
      "pl": "Sri Lanka",
      "no": "Sri Lanka",
      "ja": "スリランカ",
      "it": "Sri Lanka",
      "zh": "斯里兰卡",
      "nl": "Sri Lanka",
      "de": "Sri Lanka",
      "fr": "Sri Lanka",
      "es": "Sri Lanka",
      "en": "Sri Lanka",
      "pt_BR": "Sri Lanka",
      "sr-Cyrl": "Шри Ланка",
      "sr-Latn": "Šri Lanka",
      "zh_TW": "斯里蘭卡",
      "tr": "Sri Lanka",
      "ro": "Sri Lanka",
      "ar": "سريلانكا",
      "fa": "سریلانکا",
      "yue": "斯里蘭卡"
    },
    flag: "🇱🇰",
    code: "LK",
    dialCode: "94",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Sudan",
    nameTranslations: {
      "sk": "Sudán",
      "se": "Davvisudan",
      "pl": "Sudan",
      "no": "Sudan",
      "ja": "スーダン",
      "it": "Sudan",
      "zh": "苏丹",
      "nl": "Soedan",
      "de": "Sudan",
      "fr": "Soudan",
      "es": "Sudán",
      "en": "Sudan",
      "pt_BR": "Sudão",
      "sr-Cyrl": "Судан",
      "sr-Latn": "Sudan",
      "zh_TW": "蘇丹",
      "tr": "Sudan",
      "ro": "Sudan",
      "ar": "السودان",
      "fa": "سودان",
      "yue": "蘇丹"
    },
    flag: "🇸🇩",
    code: "SD",
    dialCode: "249",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Suriname",
    nameTranslations: {
      "sk": "Surinam",
      "se": "Surinam",
      "pl": "Surinam",
      "no": "Surinam",
      "ja": "スリナム",
      "it": "Suriname",
      "zh": "苏里南",
      "nl": "Suriname",
      "de": "Suriname",
      "fr": "Suriname",
      "es": "Surinam",
      "en": "Suriname",
      "pt_BR": "Suriname",
      "sr-Cyrl": "Суринам",
      "sr-Latn": "Surinam",
      "zh_TW": "蘇利南",
      "tr": "Surinam",
      "ro": "Surinam",
      "ar": "سورينام",
      "fa": "سورینام",
      "yue": "蘇里南"
    },
    flag: "🇸🇷",
    code: "SR",
    dialCode: "597",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Svalbard and Jan Mayen",
    nameTranslations: {
      "sk": "Svalbard a Jan Mayen",
      "se": "Svalbárda ja Jan Mayen",
      "pl": "Svalbard i Jan Mayen",
      "no": "Svalbard og Jan Mayen",
      "ja": "スバールバル諸島・ヤンマイエン島",
      "it": "Svalbard e Jan Mayen",
      "zh": "斯瓦尔巴和扬马延",
      "nl": "Spitsbergen en Jan Mayen",
      "de": "Spitzbergen und Jan Mayen",
      "fr": "Svalbard et Jan Mayen",
      "es": "Svalbard y Jan Mayen",
      "en": "Svalbard & Jan Mayen",
      "pt_BR": "Svalbard e Jan Mayen",
      "sr-Cyrl": "Свалбард",
      "sr-Latn": "Svalbard",
      "zh_TW": "斯瓦巴及尖棉",
      "tr": "Svalbard ve Jan Mayen",
      "ro": "Svalbard și Jan Mayen",
      "ar": "سفالبارد ويان ماين",
      "fa": "سوالبارد و یان ماین",
      "yue": "斯瓦尔巴德同扬·马延"
    },
    flag: "🇸🇯",
    code: "SJ",
    dialCode: "47",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Eswatini",
    nameTranslations: {
      "sk": "Eswatini",
      "se": "Svazieana",
      "pl": "Eswatini",
      "no": "Eswatini",
      "ja": "エスワティニ",
      "it": "Swaziland",
      "zh": "斯威士兰",
      "nl": "eSwatini",
      "de": "Eswatini",
      "fr": "Eswatini",
      "es": "Esuatini",
      "en": "Eswatini",
      "pt_BR": "Eswatini",
      "sr-Cyrl": "Свазиланд",
      "sr-Latn": "Svaziland",
      "zh_TW": "史瓦帝尼",
      "tr": "Esvatini",
      "ro": "Eswatini",
      "ar": "إسواتيني",
      "fa": "اسواتینی",
      "yue": "斯威士蘭"
    },
    flag: "🇸🇿",
    code: "SZ",
    dialCode: "268",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Sweden",
    nameTranslations: {
      "sk": "Švédsko",
      "se": "Ruoŧŧa",
      "pl": "Szwecja",
      "no": "Sverige",
      "ja": "スウェーデン",
      "it": "Svezia",
      "zh": "瑞典",
      "nl": "Zweden",
      "de": "Schweden",
      "fr": "Suède",
      "es": "Suecia",
      "en": "Sweden",
      "pt_BR": "Suécia",
      "sr-Cyrl": "Шведска",
      "sr-Latn": "Švedska",
      "zh_TW": "瑞典",
      "tr": "İsveç",
      "ro": "Suedia",
      "ar": "السويد",
      "fa": "سوئد",
      "yue": "瑞典"
    },
    flag: "🇸🇪",
    code: "SE",
    dialCode: "46",
    minLength: 7,
    maxLength: 13,
  ),
  Country(
    name: "Switzerland",
    nameTranslations: {
      "sk": "Švajčiarsko",
      "se": "Šveica",
      "pl": "Szwajcaria",
      "no": "Sveits",
      "ja": "スイス",
      "it": "Svizzera",
      "zh": "瑞士",
      "nl": "Zwitserland",
      "de": "Schweiz",
      "fr": "Suisse",
      "es": "Suiza",
      "en": "Switzerland",
      "pt_BR": "Suíça",
      "sr-Cyrl": "Швајцарска",
      "sr-Latn": "Švajcarska",
      "zh_TW": "瑞士",
      "tr": "İsviçre",
      "ro": "Elveţia",
      "ar": "سويسرا",
      "fa": "سوئیس",
      "yue": "瑞士"
    },
    flag: "🇨🇭",
    code: "CH",
    dialCode: "41",
    minLength: 9,
    maxLength: 12,
  ),
  Country(
    name: "Syrian Arab Republic",
    nameTranslations: {
      "sk": "Sýria",
      "se": "Syria",
      "pl": "Syria",
      "no": "Syria",
      "ja": "シリア",
      "it": "Siria",
      "zh": "叙利亚",
      "nl": "Syrië",
      "de": "Syrien",
      "fr": "Syrie",
      "es": "Siria",
      "en": "Syria",
      "pt_BR": "Síria",
      "sr-Cyrl": "Сирија",
      "sr-Latn": "Sirija",
      "zh_TW": "敘利亞",
      "tr": "Suriye",
      "ro": "Siria",
      "ar": "سوريا",
      "fa": "سوریه",
      "yue": "阿拉伯敘利亞共和國"
    },
    flag: "🇸🇾",
    code: "SY",
    dialCode: "963",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Taiwan",
    nameTranslations: {
      "sk": "Taiwan",
      "se": "Taiwan",
      "pl": "Tajwan",
      "no": "Taiwan",
      "ja": "台湾",
      "it": "Taiwan",
      "zh": "台湾",
      "nl": "Taiwan",
      "de": "Taiwan",
      "fr": "Taïwan",
      "es": "Taiwán",
      "en": "Taiwan",
      "pt_BR": "Taiwan",
      "sr-Cyrl": "Тајван",
      "sr-Latn": "Tajvan",
      "zh_TW": "台灣",
      "tr": "Tayvan",
      "ro": "Taiwan",
      "ar": "تايوان",
      "fa": "تایوان",
      "yue": "台灣"
    },
    flag: "🇹🇼",
    code: "TW",
    dialCode: "886",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Tajikistan",
    nameTranslations: {
      "sk": "Tadžikistan",
      "se": "Tažikistan",
      "pl": "Tadżykistan",
      "no": "Tadsjikistan",
      "ja": "タジキスタン",
      "it": "Tagikistan",
      "zh": "塔吉克斯坦",
      "nl": "Tadzjikistan",
      "de": "Tadschikistan",
      "fr": "Tadjikistan",
      "es": "Tayikistán",
      "en": "Tajikistan",
      "pt_BR": "Tajiquistão",
      "sr-Cyrl": "Таџикистан",
      "sr-Latn": "Tadžikistan",
      "zh_TW": "塔吉克",
      "tr": "Tacikistan",
      "ro": "Tadiquistão",
      "ar": "طاجيكستان",
      "fa": "تاجیکستان",
      "yue": "塔吉克斯坦"
    },
    flag: "🇹🇯",
    code: "TJ",
    dialCode: "992",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Tanzania, United Republic of Tanzania",
    nameTranslations: {
      "sk": "Tanzánia",
      "se": "Tanzánia",
      "pl": "Tanzania",
      "no": "Tanzania",
      "ja": "タンザニア",
      "it": "Tanzania",
      "zh": "坦桑尼亚",
      "nl": "Tanzania",
      "de": "Tansania",
      "fr": "Tanzanie",
      "es": "Tanzania",
      "en": "Tanzania",
      "pt_BR": "Tanzânia",
      "sr-Cyrl": "Танзанија",
      "sr-Latn": "Tanzanija",
      "zh_TW": "坦尚尼亞",
      "tr": "Tanzanya",
      "ro": "Tanzania",
      "ar": "تنزانيا",
      "fa": "تانزانیا",
      "yue": "坦桑尼亞，聯合共和國"
    },
    flag: "🇹🇿",
    code: "TZ",
    dialCode: "255",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Thailand",
    nameTranslations: {
      "sk": "Thajsko",
      "se": "Thaieana",
      "pl": "Tajlandia",
      "no": "Thailand",
      "ja": "タイ",
      "it": "Thailandia",
      "zh": "泰国",
      "nl": "Thailand",
      "de": "Thailand",
      "fr": "Thaïlande",
      "es": "Tailandia",
      "en": "Thailand",
      "pt_BR": "Tailândia",
      "sr-Cyrl": "Тајланд",
      "sr-Latn": "Tajland",
      "zh_TW": "泰國",
      "tr": "Tayland",
      "ro": "Tailanda",
      "ar": "تايلاند",
      "fa": "تایلند",
      "yue": "泰國"
    },
    flag: "🇹🇭",
    code: "TH",
    dialCode: "66",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Timor-Leste",
    nameTranslations: {
      "sk": "Východný Timor",
      "se": "Nuorta-Timor",
      "pl": "Timor Wschodni",
      "no": "Øst-Timor",
      "ja": "東ティモール",
      "it": "Timor Est",
      "zh": "东帝汶",
      "nl": "Oost-Timor",
      "de": "Timor-Leste",
      "fr": "Timor oriental",
      "es": "Timor-Leste",
      "en": "Timor-Leste",
      "pt_BR": "Timor-Leste",
      "sr-Cyrl": "Источни Тимор",
      "sr-Latn": "Istočni Timor",
      "zh_TW": "東帝汶",
      "tr": "Doğu Timor",
      "ro": "Timorul de Est",
      "ar": "تيمور الشرقية",
      "fa": "تیمور شرقی",
      "yue": "東帝汶"
    },
    flag: "🇹🇱",
    code: "TL",
    dialCode: "670",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Togo",
    nameTranslations: {
      "sk": "Togo",
      "se": "Togo",
      "pl": "Togo",
      "no": "Togo",
      "ja": "トーゴ",
      "it": "Togo",
      "zh": "多哥",
      "nl": "Togo",
      "de": "Togo",
      "fr": "Togo",
      "es": "Togo",
      "en": "Togo",
      "pt_BR": "Ir",
      "sr-Cyrl": "Того",
      "sr-Latn": "Togo",
      "zh_TW": "多哥",
      "tr": "Togo",
      "ro": "Togo",
      "ar": "توغو",
      "fa": "توگو",
      "yue": "多哥"
    },
    flag: "🇹🇬",
    code: "TG",
    dialCode: "228",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Tokelau",
    nameTranslations: {
      "sk": "Tokelau",
      "se": "Tokelau",
      "pl": "Tokelau",
      "no": "Tokelau",
      "ja": "トケラウ",
      "it": "Tokelau",
      "zh": "托克劳",
      "nl": "Tokelau",
      "de": "Tokelau",
      "fr": "Tokelau",
      "es": "Tokelau",
      "en": "Tokelau",
      "pt_BR": "Tokelau",
      "sr-Cyrl": "Токелау",
      "sr-Latn": "Tokelau",
      "zh_TW": "托克勞",
      "tr": "Tokelau",
      "ro": "Tokelau",
      "ar": "توكيلاو",
      "fa": "توکلائو",
      "yue": "托克劳"
    },
    flag: "🇹🇰",
    code: "TK",
    dialCode: "690",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: "Tonga",
    nameTranslations: {
      "sk": "Tonga",
      "se": "Tonga",
      "pl": "Tonga",
      "no": "Tonga",
      "ja": "トンガ",
      "it": "Tonga",
      "zh": "汤加",
      "nl": "Tonga",
      "de": "Tonga",
      "fr": "Tonga",
      "es": "Tonga",
      "en": "Tonga",
      "pt_BR": "Tonga",
      "sr-Cyrl": "Тонга",
      "sr-Latn": "Tonga",
      "zh_TW": "東加",
      "tr": "Tonga",
      "ro": "Tonga",
      "ar": "تونغا",
      "fa": "تونگا",
      "yue": "湯加"
    },
    flag: "🇹🇴",
    code: "TO",
    dialCode: "676",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Trinidad and Tobago",
    nameTranslations: {
      "sk": "Trinidad a Tobago",
      "se": "Trinidad ja Tobago",
      "pl": "Trynidad i Tobago",
      "no": "Trinidad og Tobago",
      "ja": "トリニダード・トバゴ",
      "it": "Trinidad e Tobago",
      "zh": "特立尼达和多巴哥",
      "nl": "Trinidad en Tobago",
      "de": "Trinidad und Tobago",
      "fr": "Trinité-et-Tobago",
      "es": "Trinidad y Tobago",
      "en": "Trinidad & Tobago",
      "pt_BR": "Trinidad e Tobago",
      "sr-Cyrl": "Тринидад и Тобаго",
      "sr-Latn": "Trinidad i Tobago",
      "zh_TW": "千里達及托巴哥",
      "tr": "Trinidad ve Tobago",
      "ro": "Trinidad şi Tobago",
      "ar": "ترينيداد وتوباغو",
      "fa": "ترینیداد و توباگو",
      "yue": "特立尼達和多巴哥"
    },
    flag: "🇹🇹",
    code: "TT",
    dialCode: "1868",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Tunisia",
    nameTranslations: {
      "sk": "Tunisko",
      "se": "Tunisia",
      "pl": "Tunezja",
      "no": "Tunisia",
      "ja": "チュニジア",
      "it": "Tunisia",
      "zh": "突尼斯",
      "nl": "Tunesië",
      "de": "Tunesien",
      "fr": "Tunisie",
      "es": "Túnez",
      "en": "Tunisia",
      "pt_BR": "Tunísia",
      "sr-Cyrl": "Тунис",
      "sr-Latn": "Tunis",
      "zh_TW": "突尼西亞",
      "tr": "Tunus",
      "ro": "Tunisia",
      "ar": "تونس",
      "fa": "تونس",
      "yue": "突尼斯"
    },
    flag: "🇹🇳",
    code: "TN",
    dialCode: "216",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Turkey",
    nameTranslations: {
      "sk": "Turecko",
      "se": "Durka",
      "pl": "Turcja",
      "no": "Tyrkia",
      "ja": "トルコ",
      "it": "Turchia",
      "zh": "土耳其",
      "nl": "Turkije",
      "de": "Türkei",
      "fr": "Turquie",
      "es": "Turquía",
      "en": "Turkey",
      "pt_BR": "Peru",
      "sr-Cyrl": "Турска",
      "sr-Latn": "Turska",
      "zh_TW": "土耳其",
      "tr": "Türkiye",
      "ro": "Turcia",
      "ar": "تركيا",
      "fa": "ترکیه",
      "yue": "土耳其"
    },
    flag: "🇹🇷",
    code: "TR",
    dialCode: "90",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Turkmenistan",
    nameTranslations: {
      "sk": "Turkménsko",
      "se": "Turkmenistan",
      "pl": "Turkmenistan",
      "no": "Turkmenistan",
      "ja": "トルクメニスタン",
      "it": "Turkmenistan",
      "zh": "土库曼斯坦",
      "nl": "Turkmenistan",
      "de": "Turkmenistan",
      "fr": "Turkménistan",
      "es": "Turkmenistán",
      "en": "Turkmenistan",
      "pt_BR": "Turcomenistão",
      "sr-Cyrl": "Туркменистан",
      "sr-Latn": "Turkmenistan",
      "zh_TW": "土庫曼",
      "tr": "Türkmenistan",
      "ro": "Turkmenistan",
      "ar": "تركمانستان",
      "fa": "ترکمنستان",
      "yue": "土庫曼斯坦"
    },
    flag: "🇹🇲",
    code: "TM",
    dialCode: "993",
    minLength: 8,
    maxLength: 8,
  ),
];
