/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_2.dart
/// Purpose: Country reference data, part 2 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart2 = <Country>[
  Country(
    name: "Bhutan",
    nameTranslations: {
      "sk": "Bhután",
      "se": "Bhutan",
      "pl": "Bhutan",
      "no": "Bhutan",
      "ja": "ブータン",
      "it": "Bhutan",
      "zh": "不丹",
      "nl": "Bhutan",
      "de": "Bhutan",
      "fr": "Bhoutan",
      "es": "Bután",
      "en": "Bhutan",
      "pt_BR": "Butão",
      "sr-Cyrl": "Бутан",
      "sr-Latn": "Butan",
      "zh_TW": "不丹",
      "tr": "Bhutan",
      "ro": "Bhutan",
      "ar": "بوتان",
      "fa": "بوتان",
      "yue": "不丹"
    },
    flag: "🇧🇹",
    code: "BT",
    dialCode: "975",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bolivia, Plurinational State of bolivia",
    nameTranslations: {
      "sk": "Bolívia",
      "se": "Bolivia",
      "pl": "Boliwia",
      "no": "Bolivia",
      "ja": "ボリビア",
      "it": "Bolivia",
      "zh": "玻利维亚",
      "nl": "Bolivia",
      "de": "Bolivien",
      "fr": "Bolivie",
      "es": "Bolivia",
      "en": "Bolivia",
      "pt_BR": "Bolívia",
      "sr-Cyrl": "Боливија",
      "sr-Latn": "Bolivija",
      "zh_TW": "玻利維亞",
      "tr": "Bolivya",
      "ro": "Bolivia",
      "ar": "بوليفيا",
      "fa": "بولیوی",
      "yue": "玻利維亞（多民族國家）"
    },
    flag: "🇧🇴",
    code: "BO",
    dialCode: "591",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bosnia and Herzegovina",
    nameTranslations: {
      "sk": "Bosna a Hercegovina",
      "se": "Bosnia-Hercegovina",
      "pl": "Bośnia i Hercegowina",
      "no": "Bosnia-Hercegovina",
      "ja": "ボスニア・ヘルツェゴビナ",
      "it": "Bosnia ed Erzegovina",
      "zh": "波斯尼亚和黑塞哥维那",
      "nl": "Bosnië en Herzegovina",
      "de": "Bosnien und Herzegowina",
      "fr": "Bosnie-Herzégovine",
      "es": "Bosnia y Herzegovina",
      "en": "Bosnia & Herzegovina",
      "pt_BR": "Bósnia e Herzegovina",
      "sr-Cyrl": "Босна и Херцеговина",
      "sr-Latn": "Bosna i Hercegovina",
      "zh_TW": "波士尼亞和黑塞哥維那",
      "tr": "Bosna Hersek",
      "ro": "Bosnia și Herțegovina",
      "ar": "البوسنة والهرسك",
      "fa": "بوسنی و هرزگوین",
      "yue": "波斯尼亞黑塞哥維那"
    },
    flag: "🇧🇦",
    code: "BA",
    dialCode: "387",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Botswana",
    nameTranslations: {
      "sk": "Botswana",
      "se": "Botswana",
      "pl": "Botswana",
      "no": "Botswana",
      "ja": "ボツワナ",
      "it": "Botswana",
      "zh": "博茨瓦纳",
      "nl": "Botswana",
      "de": "Botsuana",
      "fr": "Botswana",
      "es": "Botsuana",
      "en": "Botswana",
      "pt_BR": "Botswana",
      "sr-Cyrl": "Боцвана",
      "sr-Latn": "Bocvana",
      "zh_TW": "博茨瓦納",
      "tr": "Botsvana",
      "ro": "Botswana",
      "ar": "بوتسوانا",
      "fa": "بوتسوانا",
      "yue": "博茨瓦納"
    },
    flag: "🇧🇼",
    code: "BW",
    dialCode: "267",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bouvet Island",
    nameTranslations: {
      "sk": "Bouvetov ostrov",
      "se": "Bouvet-sullot",
      "pl": "Wyspa Bouveta",
      "no": "Bouvetøya",
      "ja": "ブーベ島",
      "it": "Isola Bouvet",
      "zh": "布韦岛",
      "nl": "Bouveteiland",
      "de": "Bouvetinsel",
      "fr": "Île Bouvet",
      "es": "Isla Bouvet",
      "en": "Bouvet Island",
      "pt_BR": "Ilha Bouvet",
      "sr-Cyrl": "Острво Буве",
      "sr-Latn": "Ostrvo Buve",
      "zh_TW": "布維特島",
      "tr": "Bouvet Adası",
      "ro": "Insula Bouvet",
      "ar": "جزيرة بوفيه",
      "fa": "جزیره بووه",
      "yue": "布维特岛"
    },
    flag: "🇧🇻",
    code: "BV",
    dialCode: "47",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Brazil",
    nameTranslations: {
      "sk": "Brazília",
      "se": "Brasil",
      "pl": "Brazylia",
      "no": "Brasil",
      "ja": "ブラジル",
      "it": "Brasile",
      "zh": "巴西",
      "nl": "Brazilië",
      "de": "Brasilien",
      "fr": "Brésil",
      "es": "Brasil",
      "en": "Brazil",
      "pt_BR": "Brasil",
      "sr-Cyrl": "Бразил",
      "sr-Latn": "Brazil",
      "zh_TW": "巴西",
      "tr": "Brezilya",
      "ro": "Brazilia",
      "ar": "البرازيل",
      "fa": "برزیل",
      "yue": "巴西"
    },
    flag: "🇧🇷",
    code: "BR",
    dialCode: "55",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "British Indian Ocean Territory",
    nameTranslations: {
      "sk": "Britské indickooceánske územie",
      "se": "British Indian Ocean Territory",
      "pl": "Brytyjskie Terytorium Oceanu Indyjskiego",
      "no": "Det britiske territoriet i Indiahavet",
      "ja": "英領インド洋地域",
      "it": "Territorio britannico dell'Oceano Indiano",
      "zh": "英属印度洋领地",
      "nl": "Brits Indische Oceaanterritorium",
      "de": "Britisches Territorium im Indischen Ozean",
      "fr": "Territoire britannique de l'océan Indien",
      "es": "Territorio Británico del Océano Índico",
      "en": "British Indian Ocean Territory",
      "pt_BR": "Território Britânico do Oceano Índico",
      "sr-Cyrl": "Британска територија Индијског океана",
      "sr-Latn": "Britanska teritorija Indijskog okeana",
      "zh_TW": "英屬印度洋領地",
      "tr": "Britanya Hint Okyanusu Toprakları",
      "ro": "Teritoriul Britanic din Oceanul Indian",
      "ar": "إقليم المحيط الهندي البريطاني",
      "fa": "سرزمین دریایی هند - بریتانیا",
      "yue": "英屬印度洋領土"
    },
    flag: "🇮🇴",
    code: "IO",
    dialCode: "246",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Brunei Darussalam",
    nameTranslations: {
      "sk": "Brunej",
      "se": "Brunei",
      "pl": "Brunei",
      "no": "Brunei",
      "ja": "ブルネイ",
      "it": "Brunei",
      "zh": "文莱",
      "nl": "Brunei",
      "de": "Brunei Darussalam",
      "fr": "Brunéi Darussalam",
      "es": "Brunéi",
      "en": "Brunei",
      "pt_BR": "Brunei",
      "sr-Cyrl": "Брунеј",
      "sr-Latn": "Brunej",
      "zh_TW": "汶萊",
      "tr": "Bruney",
      "ro": "Brunei",
      "ar": "بروناي",
      "fa": "برونئی",
      "yue": "文萊達魯薩蘭國"
    },
    flag: "🇧🇳",
    code: "BN",
    dialCode: "673",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Bulgaria",
    nameTranslations: {
      "sk": "Bulharsko",
      "se": "Bulgária",
      "pl": "Bułgaria",
      "no": "Bulgaria",
      "ja": "ブルガリア",
      "it": "Bulgaria",
      "zh": "保加利亚",
      "nl": "Bulgarije",
      "de": "Bulgarien",
      "fr": "Bulgarie",
      "es": "Bulgaria",
      "en": "Bulgaria",
      "pt_BR": "Bulgária",
      "sr-Cyrl": "Бугарска",
      "sr-Latn": "Bugarska",
      "zh_TW": "保加利亞",
      "tr": "Bulgaristan",
      "ro": "Bulgaria",
      "ar": "بلغاريا",
      "fa": "بلغارستان",
      "yue": "保加利亞"
    },
    flag: "🇧🇬",
    code: "BG",
    dialCode: "359",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Burkina Faso",
    nameTranslations: {
      "sk": "Burkina Faso",
      "se": "Burkina Faso",
      "pl": "Burkina Faso",
      "no": "Burkina Faso",
      "ja": "ブルキナファソ",
      "it": "Burkina Faso",
      "zh": "布基纳法索",
      "nl": "Burkina Faso",
      "de": "Burkina Faso",
      "fr": "Burkina Faso",
      "es": "Burkina Faso",
      "en": "Burkina Faso",
      "pt_BR": "Burkina Faso",
      "sr-Cyrl": "Буркина Фасо",
      "sr-Latn": "Burkina Faso",
      "zh_TW": "布吉納法索",
      "tr": "Burkina Faso",
      "ro": "Burkina Faso",
      "ar": "بوركينا فاسو",
      "fa": "بورکینافاسو",
      "yue": "布基納法索"
    },
    flag: "🇧🇫",
    code: "BF",
    dialCode: "226",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Burundi",
    nameTranslations: {
      "sk": "Burundi",
      "se": "Burundi",
      "pl": "Burundi",
      "no": "Burundi",
      "ja": "ブルンジ",
      "it": "Burundi",
      "zh": "布隆迪",
      "nl": "Burundi",
      "de": "Burundi",
      "fr": "Burundi",
      "es": "Burundi",
      "en": "Burundi",
      "pt_BR": "Burundi",
      "sr-Cyrl": "Бурунди",
      "sr-Latn": "Burundi",
      "zh_TW": "蒲隆地",
      "tr": "Burundi",
      "ro": "Burundi",
      "ar": "بوروندي",
      "fa": "بوروندی",
      "yue": "蒲隆地"
    },
    flag: "🇧🇮",
    code: "BI",
    dialCode: "257",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Cambodia",
    nameTranslations: {
      "sk": "Kambodža",
      "se": "Kambodža",
      "pl": "Kambodża",
      "no": "Kambodsja",
      "ja": "カンボジア",
      "it": "Cambogia",
      "zh": "柬埔寨",
      "nl": "Cambodja",
      "de": "Kambodscha",
      "fr": "Cambodge",
      "es": "Camboya",
      "en": "Cambodia",
      "pt_BR": "Camboja",
      "sr-Cyrl": "Камбоџа",
      "sr-Latn": "Kambodža",
      "zh_TW": "柬埔寨",
      "tr": "Kamboçya",
      "ro": "Cambogia",
      "ar": "كمبوديا",
      "fa": "کامبوج",
      "yue": "柬埔寨"
    },
    flag: "🇰🇭",
    code: "KH",
    dialCode: "855",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Cameroon",
    nameTranslations: {
      "sk": "Kamerun",
      "se": "Kamerun",
      "pl": "Kamerun",
      "no": "Kamerun",
      "ja": "カメルーン",
      "it": "Camerun",
      "zh": "喀麦隆",
      "nl": "Kameroen",
      "de": "Kamerun",
      "fr": "Cameroun",
      "es": "Camerún",
      "en": "Cameroon",
      "pt_BR": "Camarões",
      "sr-Cyrl": "Камерун",
      "sr-Latn": "Kamerun",
      "zh_TW": "喀麥隆",
      "tr": "Kamerun",
      "ro": "Camerun",
      "ar": "الكاميرون",
      "fa": "کامرون",
      "yue": "喀 麥 隆"
    },
    flag: "🇨🇲",
    code: "CM",
    dialCode: "237",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Canada",
    nameTranslations: {
      "sk": "Kanada",
      "se": "Kanáda",
      "pl": "Kanada",
      "no": "Canada",
      "ja": "カナダ",
      "it": "Canada",
      "zh": "加拿大",
      "nl": "Canada",
      "de": "Kanada",
      "fr": "Canada",
      "es": "Canadá",
      "en": "Canada",
      "pt_BR": "Canadá",
      "sr-Cyrl": "Канада",
      "sr-Latn": "Kanada",
      "zh_TW": "加拿大",
      "tr": "Kanada",
      "ro": "Canada",
      "ar": "كندا",
      "fa": "کانادا",
      "yue": "加拿大"
    },
    flag: "🇨🇦",
    code: "CA",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Cayman Islands",
    nameTranslations: {
      "sk": "Kajmanie ostrovy",
      "se": "Cayman-sullot",
      "pl": "Kajmany",
      "no": "Caymanøyene",
      "ja": "ケイマン諸島",
      "it": "Isole Cayman",
      "zh": "开曼群岛",
      "nl": "Kaaimaneilanden",
      "de": "Kaimaninseln",
      "fr": "Îles Caïmans",
      "es": "Islas Caimán",
      "en": "Cayman Islands",
      "pt_BR": "Ilhas Cayman",
      "sr-Cyrl": "Кајманска Острва",
      "sr-Latn": "Kajmanska Ostrva",
      "zh_TW": "開曼群島",
      "tr": "Cayman Adaları",
      "ro": "Insulele Cayman",
      "ar": "جزر كايمان",
      "fa": "جزایر کیمن",
      "yue": "開曼群島"
    },
    flag: "🇰🇾",
    code: "KY",
    dialCode: "345",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Central African Republic",
    nameTranslations: {
      "sk": "Stredoafrická republika",
      "se": "Gaska-Afrihká dásseváldi",
      "pl": "Republika Środkowoafrykańska",
      "no": "Den sentralafrikanske republikk",
      "ja": "中央アフリカ共和国",
      "it": "Repubblica Centrafricana",
      "zh": "中非共和国",
      "nl": "Centraal-Afrikaanse Republiek",
      "de": "Zentralafrikanische Republik",
      "fr": "République centrafricaine",
      "es": "República Centroafricana",
      "en": "Central African Republic",
      "pt_BR": "República Centro-Africana",
      "sr-Cyrl": "Централноафричка Република",
      "sr-Latn": "Centralnoafrička Republika",
      "zh_TW": "中非共和國",
      "tr": "Orta Afrika Cumhuriyeti",
      "ro": "Republica Centrafricană",
      "ar": "جمهورية أفريقيا الوسطى",
      "fa": "جمهوری افریقای مرکزی",
      "yue": "中非共和國"
    },
    flag: "🇨🇫",
    code: "CF",
    dialCode: "236",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Chad",
    nameTranslations: {
      "sk": "Čad",
      "se": "Tčad",
      "pl": "Czad",
      "no": "Tsjad",
      "ja": "チャド",
      "it": "Ciad",
      "zh": "乍得",
      "nl": "Tsjaad",
      "de": "Tschad",
      "fr": "Tchad",
      "es": "Chad",
      "en": "Chad",
      "pt_BR": "Chade",
      "sr-Cyrl": "Чад",
      "sr-Latn": "Čad",
      "zh_TW": "查德",
      "tr": "Çad",
      "ro": "Ciad",
      "ar": "تشاد",
      "fa": "چاد",
      "yue": "乍得"
    },
    flag: "🇹🇩",
    code: "TD",
    dialCode: "235",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Chile",
    nameTranslations: {
      "sk": "Čile",
      "se": "Čiile",
      "pl": "Chile",
      "no": "Chile",
      "ja": "チリ",
      "it": "Cile",
      "zh": "智利",
      "nl": "Chili",
      "de": "Chile",
      "fr": "Chili",
      "es": "Chile",
      "en": "Chile",
      "pt_BR": "Chile",
      "sr-Cyrl": "Чиле",
      "sr-Latn": "Čile",
      "zh_TW": "智利",
      "tr": "Şili",
      "ro": "Chile",
      "ar": "تشيلي",
      "fa": "شیلی",
      "yue": "智利"
    },
    flag: "🇨🇱",
    code: "CL",
    dialCode: "56",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "China",
    nameTranslations: {
      "sk": "Čína",
      "se": "Kiinná",
      "pl": "Chiny",
      "no": "Kina",
      "ja": "中国",
      "it": "Cina",
      "zh": "中国",
      "nl": "China",
      "de": "China",
      "fr": "Chine",
      "es": "China",
      "en": "China",
      "pt_BR": "China",
      "sr-Cyrl": "Кина",
      "sr-Latn": "Kina",
      "zh_TW": "中國",
      "tr": "Çin",
      "ro": "China",
      "ar": "الصين",
      "fa": "چین",
      "yue": "中國"
    },
    flag: "🇨🇳",
    code: "CN",
    dialCode: "86",
    minLength: 11,
    maxLength: 12,
  ),
  Country(
    name: "Christmas Island",
    nameTranslations: {
      "sk": "Vianočný ostrov",
      "se": "Juovllat-sullot",
      "pl": "Wyspa Bożego Narodzenia",
      "no": "Christmasøya",
      "ja": "クリスマス島",
      "it": "Isola Christmas",
      "zh": "圣诞岛",
      "nl": "Christmaseiland",
      "de": "Weihnachtsinsel",
      "fr": "Île Christmas",
      "es": "Isla de Navidad",
      "en": "Christmas Island",
      "pt_BR": "Ilha do Natal",
      "sr-Cyrl": "Ускршња Острва",
      "sr-Latn": "Uskršnja Ostrva",
      "zh_TW": "聖誕島",
      "tr": "Christmas Adası",
      "ro": "Insula Crăciunului",
      "ar": "جزيرة عيد الميلاد",
      "fa": "جزیره کریسمس",
      "yue": "聖誕島"
    },
    flag: "🇨🇽",
    code: "CX",
    dialCode: "61",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Cocos (Keeling) Islands",
    nameTranslations: {
      "sk": "Kokosové ostrovy",
      "se": "Cocos-sullot",
      "pl": "Wyspy Kokosowe",
      "no": "Kokosøyene",
      "ja": "ココス(キーリング)諸島",
      "it": "Isole Cocos (Keeling)",
      "zh": "科科斯（基林）群岛",
      "nl": "Cocoseilanden",
      "de": "Kokosinseln",
      "fr": "Îles Cocos",
      "es": "Islas Cocos",
      "en": "Cocos (Keeling) Islands",
      "pt_BR": "Ilhas Cocos (Keeling)",
      "sr-Cyrl": "Кокосова Острва",
      "sr-Latn": "Kokosova Ostrva",
      "zh_TW": "科科斯（基林）群島",
      "tr": "Cocos (Keyling) Adaları",
      "ro": "Insulele Cocos",
      "ar": "جزر كوكوس",
      "fa": "جزایر کوکوس",
      "yue": "可可島（基林）群島"
    },
    flag: "🇨🇨",
    code: "CC",
    dialCode: "61",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Colombia",
    nameTranslations: {
      "sk": "Kolumbia",
      "se": "Kolombia",
      "pl": "Kolumbia",
      "no": "Colombia",
      "ja": "コロンビア",
      "it": "Colombia",
      "zh": "哥伦比亚",
      "nl": "Colombia",
      "de": "Kolumbien",
      "fr": "Colombie",
      "es": "Colombia",
      "en": "Colombia",
      "pt_BR": "Colômbia",
      "sr-Cyrl": "Колумбија",
      "sr-Latn": "Kolumbija",
      "zh_TW": "哥倫比亞",
      "tr": "Kolombiya",
      "ro": "Columbia",
      "ar": "كولومبيا",
      "fa": "کلمبیا",
      "yue": "哥倫比亞"
    },
    flag: "🇨🇴",
    code: "CO",
    dialCode: "57",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Comoros",
    nameTranslations: {
      "sk": "Komory",
      "se": "Komoros",
      "pl": "Komory",
      "no": "Komorene",
      "ja": "コモロ",
      "it": "Comore",
      "zh": "科摩罗",
      "nl": "Comoren",
      "de": "Komoren",
      "fr": "Comores",
      "es": "Comoras",
      "en": "Comoros",
      "pt_BR": "Comores",
      "sr-Cyrl": "Комори",
      "sr-Latn": "Komori",
      "zh_TW": "科摩羅",
      "tr": "Komor Adaları",
      "ro": "Comore",
      "ar": "جزر القمر",
      "fa": "جزیره کومور",
      "yue": "科摩羅"
    },
    flag: "🇰🇲",
    code: "KM",
    dialCode: "269",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Congo",
    nameTranslations: {
      "sk": "Konžská republika",
      "se": "Kongo-Brazzaville",
      "pl": "Kongo",
      "no": "Kongo-Brazzaville",
      "ja": "コンゴ共和国(ブラザビル)",
      "it": "Congo-Brazzaville",
      "zh": "刚果（布）",
      "nl": "Congo-Brazzaville",
      "de": "Kongo-Brazzaville",
      "fr": "Congo-Brazzaville",
      "es": "Congo",
      "en": "Congo - Brazzaville",
      "pt_BR": "República do Congo",
      "sr-Cyrl": "Република Конго",
      "sr-Latn": "Republika Kongo",
      "zh_TW": "剛果共和國（布拉柴維爾）",
      "tr": "Kongo Cumhuriyeti",
      "ro": "Republica Congo",
      "ar": "جمهورية الكونغو",
      "fa": "جمهوری کنگو",
      "yue": "剛果（共和國）"
    },
    flag: "🇨🇬",
    code: "CG",
    dialCode: "242",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Congo, The Democratic Republic of the Congo",
    nameTranslations: {
      "sk": "Konžská demokratická republika",
      "se": "Kongo-Kinshasa",
      "pl": "Demokratyczna Republika Konga",
      "no": "Kongo-Kinshasa",
      "ja": "コンゴ民主共和国(キンシャサ)",
      "it": "Congo - Kinshasa",
      "zh": "刚果（金）",
      "nl": "Congo-Kinshasa",
      "de": "Kongo-Kinshasa",
      "fr": "Congo-Kinshasa",
      "es": "República Democrática del Congo",
      "en": "Congo - Kinshasa",
      "pt_BR": "República Democrática do Congo",
      "sr-Cyrl": "Демократска Република Конго",
      "sr-Latn": "Demokratska Republika Kongo",
      "zh_TW": "剛果民主共和國（金沙薩）",
      "tr": "Kongo Demokratik Cumhuriyeti",
      "ro": "Republica Democrată Congo",
      "ar": "جمهورية الكونغو الديمقراطية",
      "fa": "جمهوری دموکراتیک کنگو",
      "yue": "剛果（金）"
    },
    flag: "🇨🇩",
    code: "CD",
    dialCode: "243",
    minLength: 9,
    maxLength: 9,
  ),
];
