/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_6.dart
/// Purpose: Country reference data, part 6 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart6 = <Country>[
  Country(
    name: "Lithuania",
    nameTranslations: {
      "sk": "Litva",
      "se": "Lietuva",
      "pl": "Litwa",
      "no": "Litauen",
      "ja": "リトアニア",
      "it": "Lituania",
      "zh": "立陶宛",
      "nl": "Litouwen",
      "de": "Litauen",
      "fr": "Lituanie",
      "es": "Lituania",
      "en": "Lithuania",
      "pt_BR": "Lituânia",
      "sr-Cyrl": "Литванија",
      "sr-Latn": "Litvanija",
      "zh_TW": "立陶宛",
      "tr": "Litvanya",
      "ro": "Lituania",
      "ar": "ليتوانيا",
      "fa": "لیتوانی",
      "yue": "立陶宛"
    },
    flag: "🇱🇹",
    code: "LT",
    dialCode: "370",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Luxembourg",
    nameTranslations: {
      "sk": "Luxembursko",
      "se": "Luxembourg",
      "pl": "Luksemburg",
      "no": "Luxemburg",
      "ja": "ルクセンブルク",
      "it": "Lussemburgo",
      "zh": "卢森堡",
      "nl": "Luxemburg",
      "de": "Luxemburg",
      "fr": "Luxembourg",
      "es": "Luxemburgo",
      "en": "Luxembourg",
      "pt_BR": "Luxemburgo",
      "sr-Cyrl": "Луксенбург",
      "sr-Latn": "Luksenburg",
      "zh_TW": "盧森堡",
      "tr": "Lüksemburg",
      "ro": "Luxemburg",
      "ar": "لوكسمبورغ",
      "fa": "لوکزامبورگ",
      "yue": "盧森堡"
    },
    flag: "🇱🇺",
    code: "LU",
    dialCode: "352",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Macao",
    nameTranslations: {
      "sk": "Macao – OAO Číny",
      "se": "Makáo",
      "pl": "SRA Makau (Chiny)",
      "no": "Macao S.A.R. Kina",
      "ja": "中華人民共和国マカオ特別行政区",
      "it": "RAS di Macao",
      "zh": "中国澳门特别行政区",
      "nl": "Macau SAR van China",
      "de": "Sonderverwaltungsregion Macau",
      "fr": "R.A.S. chinoise de Macao",
      "es": "RAE de Macao (China)",
      "en": "Macao SAR China",
      "pt_BR": "RAE de Macau China",
      "sr-Cyrl": "Макао",
      "sr-Latn": "Makao",
      "zh_TW": "澳門",
      "tr": "Makao",
      "ro": "Macao",
      "ar": "ماكاو",
      "fa": "ماكائو",
      "yue": "澳門"
    },
    flag: "🇲🇴",
    code: "MO",
    dialCode: "853",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Macedonia",
    nameTranslations: {
      "sk": "Severné Macedónsko",
      "se": "North Macedonia",
      "pl": "Macedonia Północna",
      "no": "Nord-Makedonia",
      "ja": "北マケドニア",
      "it": "Macedonia del Nord",
      "zh": "北马其顿",
      "nl": "Noord-Macedonië",
      "de": "Nordmazedonien",
      "fr": "Macédoine du Nord",
      "es": "Macedonia del Norte",
      "en": "North Macedonia",
      "pt_BR": "Macedônia do Norte",
      "sr-Cyrl": "Северна Македонија",
      "sr-Latn": "Severna Makedonija",
      "zh_TW": "北馬其頓",
      "tr": "Kuzey Makedonya",
      "ro": "Macedonia de Nord",
      "ar": "مقدونيا",
      "fa": "مقدونیه",
      "yue": "馬其頓（前南斯拉夫共和國）"
    },
    flag: "🇲🇰",
    code: "MK",
    dialCode: "389",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Madagascar",
    nameTranslations: {
      "sk": "Madagaskar",
      "se": "Madagaskar",
      "pl": "Madagaskar",
      "no": "Madagaskar",
      "ja": "マダガスカル",
      "it": "Madagascar",
      "zh": "马达加斯加",
      "nl": "Madagaskar",
      "de": "Madagaskar",
      "fr": "Madagascar",
      "es": "Madagascar",
      "en": "Madagascar",
      "pt_BR": "Madagáscar",
      "sr-Cyrl": "Мадагаскар",
      "sr-Latn": "Madagaskar",
      "zh_TW": "馬達加斯加",
      "tr": "Madagaskar",
      "ro": "Madagascar",
      "ar": "مدغشقر",
      "fa": "ماداگاسکار",
      "yue": "馬達加斯加"
    },
    flag: "🇲🇬",
    code: "MG",
    dialCode: "261",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Malawi",
    nameTranslations: {
      "sk": "Malawi",
      "se": "Malawi",
      "pl": "Malawi",
      "no": "Malawi",
      "ja": "マラウイ",
      "it": "Malawi",
      "zh": "马拉维",
      "nl": "Malawi",
      "de": "Malawi",
      "fr": "Malawi",
      "es": "Malaui",
      "en": "Malawi",
      "pt_BR": "Malawi",
      "sr-Cyrl": "Малави",
      "sr-Latn": "Malavi",
      "zh_TW": "馬拉威",
      "tr": "Malavi",
      "ro": "Malawi",
      "ar": "مالاوي",
      "fa": "مالاوی",
      "yue": "馬拉維"
    },
    flag: "🇲🇼",
    code: "MW",
    dialCode: "265",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "Malaysia",
    nameTranslations: {
      "sk": "Malajzia",
      "se": "Malesia",
      "pl": "Malezja",
      "no": "Malaysia",
      "ja": "マレーシア",
      "it": "Malaysia",
      "zh": "马来西亚",
      "nl": "Maleisië",
      "de": "Malaysia",
      "fr": "Malaisie",
      "es": "Malasia",
      "en": "Malaysia",
      "pt_BR": "Malásia",
      "sr-Cyrl": "Малезија",
      "sr-Latn": "Malezija",
      "zh_TW": "馬來西亞",
      "tr": "Malezya",
      "ro": "Malaezia",
      "ar": "ماليزيا",
      "fa": "مالزی",
      "yue": "馬來西亞"
    },
    flag: "🇲🇾",
    code: "MY",
    dialCode: "60",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Maldives",
    nameTranslations: {
      "sk": "Maldivy",
      "se": "Malediivvat",
      "pl": "Malediwy",
      "no": "Maldivene",
      "ja": "モルディブ",
      "it": "Maldive",
      "zh": "马尔代夫",
      "nl": "Maldiven",
      "de": "Malediven",
      "fr": "Maldives",
      "es": "Maldivas",
      "en": "Maldives",
      "pt_BR": "Maldivas",
      "sr-Cyrl": "Малдиви",
      "sr-Latn": "Maldivi",
      "zh_TW": "馬爾地夫",
      "tr": "Maldivler",
      "ro": "Maldive",
      "ar": "جزر المالديف",
      "fa": "مالدیو",
      "yue": "馬爾代夫"
    },
    flag: "🇲🇻",
    code: "MV",
    dialCode: "960",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Mali",
    nameTranslations: {
      "sk": "Mali",
      "se": "Mali",
      "pl": "Mali",
      "no": "Mali",
      "ja": "マリ",
      "it": "Mali",
      "zh": "马里",
      "nl": "Mali",
      "de": "Mali",
      "fr": "Mali",
      "es": "Mali",
      "en": "Mali",
      "pt_BR": "Mali",
      "sr-Cyrl": "Мали",
      "sr-Latn": "Mali",
      "zh_TW": "馬里",
      "tr": "Mali",
      "ro": "Mali",
      "ar": "مالي",
      "fa": "مالی",
      "yue": "馬里"
    },
    flag: "🇲🇱",
    code: "ML",
    dialCode: "223",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Malta",
    nameTranslations: {
      "sk": "Malta",
      "se": "Málta",
      "pl": "Malta",
      "no": "Malta",
      "ja": "マルタ",
      "it": "Malta",
      "zh": "马耳他",
      "nl": "Malta",
      "de": "Malta",
      "fr": "Malte",
      "es": "Malta",
      "en": "Malta",
      "pt_BR": "Malta",
      "sr-Cyrl": "Малта",
      "sr-Latn": "Malta",
      "zh_TW": "馬爾他",
      "tr": "Malta",
      "ro": "Malta",
      "ar": "مالطا",
      "fa": "مالت",
      "yue": "馬耳他"
    },
    flag: "🇲🇹",
    code: "MT",
    dialCode: "356",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Marshall Islands",
    nameTranslations: {
      "sk": "Marshallove ostrovy",
      "se": "Marshallsullot",
      "pl": "Wyspy Marshalla",
      "no": "Marshalløyene",
      "ja": "マーシャル諸島",
      "it": "Isole Marshall",
      "zh": "马绍尔群岛",
      "nl": "Marshalleilanden",
      "de": "Marshallinseln",
      "fr": "Îles Marshall",
      "es": "Islas Marshall",
      "en": "Marshall Islands",
      "pt_BR": "Ilhas Marshall",
      "sr-Cyrl": "Маршалска Острва",
      "sr-Latn": "Maršalska Ostrva",
      "zh_TW": "馬紹爾群島",
      "tr": "Marshall Adaları",
      "ro": "Insulele Marshall",
      "ar": "جزر مارشال",
      "fa": "جزایر مارشال",
      "yue": "馬紹爾群島"
    },
    flag: "🇲🇭",
    code: "MH",
    dialCode: "692",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Martinique",
    nameTranslations: {
      "sk": "Martinik",
      "se": "Martinique",
      "pl": "Martynika",
      "no": "Martinique",
      "ja": "マルティニーク",
      "it": "Martinica",
      "zh": "马提尼克",
      "nl": "Martinique",
      "de": "Martinique",
      "fr": "Martinique",
      "es": "Martinica",
      "en": "Martinique",
      "pt_BR": "Martinica",
      "sr-Cyrl": "Мартиник",
      "sr-Latn": "Martinik",
      "zh_TW": "馬丁尼克",
      "tr": "Martinique",
      "ro": "Martinica",
      "ar": "مارتينيك",
      "fa": "مارتینیک",
      "yue": "马提尼克"
    },
    flag: "🇲🇶",
    code: "MQ",
    dialCode: "596",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Mauritania",
    nameTranslations: {
      "sk": "Mauritánia",
      "se": "Mauretánia",
      "pl": "Mauretania",
      "no": "Mauritania",
      "ja": "モーリタニア",
      "it": "Mauritania",
      "zh": "毛里塔尼亚",
      "nl": "Mauritanië",
      "de": "Mauretanien",
      "fr": "Mauritanie",
      "es": "Mauritania",
      "en": "Mauritania",
      "pt_BR": "Mauritânia",
      "sr-Cyrl": "Мауританија",
      "sr-Latn": "Mauritanija",
      "zh_TW": "茅利塔尼亞",
      "tr": "Moritanya",
      "ro": "Mauritania",
      "ar": "موريتانيا",
      "fa": "موریتانی",
      "yue": "毛里塔尼亞"
    },
    flag: "🇲🇷",
    code: "MR",
    dialCode: "222",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Mauritius",
    nameTranslations: {
      "sk": "Maurícius",
      "se": "Mauritius",
      "pl": "Mauritius",
      "no": "Mauritius",
      "ja": "モーリシャス",
      "it": "Mauritius",
      "zh": "毛里求斯",
      "nl": "Mauritius",
      "de": "Mauritius",
      "fr": "Maurice",
      "es": "Mauricio",
      "en": "Mauritius",
      "pt_BR": "Maurício",
      "sr-Cyrl": "Маурицијус",
      "sr-Latn": "Mauricijus",
      "zh_TW": "模里西斯",
      "tr": "Mauritius",
      "ro": "Mauritius",
      "ar": "موريشيوس",
      "fa": "موریس",
      "yue": "毛里求斯"
    },
    flag: "🇲🇺",
    code: "MU",
    dialCode: "230",
    minLength: 7,
    maxLength: 8,
  ),
  Country(
    name: "Mayotte",
    nameTranslations: {
      "sk": "Mayotte",
      "se": "Mayotte",
      "pl": "Majotta",
      "no": "Mayotte",
      "ja": "マヨット",
      "it": "Mayotte",
      "zh": "马约特",
      "nl": "Mayotte",
      "de": "Mayotte",
      "fr": "Mayotte",
      "es": "Mayotte",
      "en": "Mayotte",
      "pt_BR": "Mayotte",
      "sr-Cyrl": "Мајота",
      "sr-Latn": "Majota",
      "zh_TW": "馬約特",
      "tr": "Mayotte",
      "ro": "Mayotte",
      "ar": "مايوت",
      "fa": "مایوت",
      "yue": "馬約特"
    },
    flag: "🇾🇹",
    code: "YT",
    dialCode: "262",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Mexico",
    nameTranslations: {
      "sk": "Mexiko",
      "se": "Meksiko",
      "pl": "Meksyk",
      "no": "Mexico",
      "ja": "メキシコ",
      "it": "Messico",
      "zh": "墨西哥",
      "nl": "Mexico",
      "de": "Mexiko",
      "fr": "Mexique",
      "es": "México",
      "en": "Mexico",
      "pt_BR": "México",
      "sr-Cyrl": "Мексико",
      "sr-Latn": "Meksiko",
      "zh_TW": "墨西哥",
      "tr": "Meksika",
      "ro": "Mexic",
      "ar": "المكسيك",
      "fa": "مکزیک",
      "yue": "墨西哥"
    },
    flag: "🇲🇽",
    code: "MX",
    dialCode: "52",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Micronesia, Federated States of Micronesia",
    nameTranslations: {
      "sk": "Mikronézia",
      "se": "Mikronesia",
      "pl": "Mikronezja",
      "no": "Mikronesiaføderasjonen",
      "ja": "ミクロネシア連邦",
      "it": "Micronesia",
      "zh": "密克罗尼西亚",
      "nl": "Micronesia",
      "de": "Mikronesien",
      "fr": "États fédérés de Micronésie",
      "es": "Micronesia",
      "en": "Micronesia",
      "pt_BR": "Micronésia",
      "sr-Cyrl": "Микронезија",
      "sr-Latn": "Mikronezija",
      "zh_TW": "密克羅尼西亞",
      "tr": "Mikronezya",
      "ro": "Micronezia",
      "ar": "ولايات ميكرونيسيا المتحدة",
      "fa": "ایالات فدرال میکرونزی",
      "yue": "密克罗尼西亚（聯邦）"
    },
    flag: "🇫🇲",
    code: "FM",
    dialCode: "691",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Moldova",
    nameTranslations: {
      "sk": "Moldavsko",
      "se": "Moldávia",
      "pl": "Mołdawia",
      "no": "Moldova",
      "ja": "モルドバ",
      "it": "Moldavia",
      "zh": "摩尔多瓦",
      "nl": "Moldavië",
      "de": "Republik Moldau",
      "fr": "Moldavie",
      "es": "Moldavia",
      "en": "Moldova",
      "pt_BR": "Moldova",
      "sr-Cyrl": "Молдавија",
      "sr-Latn": "Moldavija",
      "zh_TW": "摩爾多瓦",
      "tr": "Moldova",
      "ro": "Moldova",
      "ar": "مولدوفا",
      "fa": "مولداوی",
      "yue": "摩爾多瓦（共和國）"
    },
    flag: "🇲🇩",
    code: "MD",
    dialCode: "373",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Monaco",
    nameTranslations: {
      "sk": "Monako",
      "se": "Monaco",
      "pl": "Monako",
      "no": "Monaco",
      "ja": "モナコ",
      "it": "Monaco",
      "zh": "摩纳哥",
      "nl": "Monaco",
      "de": "Monaco",
      "fr": "Monaco",
      "es": "Mónaco",
      "en": "Monaco",
      "pt_BR": "Mônaco",
      "sr-Cyrl": "Монако",
      "sr-Latn": "Monako",
      "zh_TW": "摩納哥",
      "tr": "Monako",
      "ro": "Monaco",
      "ar": "موناكو",
      "fa": "موناكو",
      "yue": "摩納哥"
    },
    flag: "🇲🇨",
    code: "MC",
    dialCode: "377",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Mongolia",
    nameTranslations: {
      "sk": "Mongolsko",
      "se": "Mongolia",
      "pl": "Mongolia",
      "no": "Mongolia",
      "ja": "モンゴル",
      "it": "Mongolia",
      "zh": "蒙古",
      "nl": "Mongolië",
      "de": "Mongolei",
      "fr": "Mongolie",
      "es": "Mongolia",
      "en": "Mongolia",
      "pt_BR": "Mongólia",
      "sr-Cyrl": "Монголија",
      "sr-Latn": "Mongolija",
      "zh_TW": "蒙古",
      "tr": "Moğolistan",
      "ro": "Mongolia",
      "ar": "منغوليا",
      "fa": "مغولستان",
      "yue": "蒙古"
    },
    flag: "🇲🇳",
    code: "MN",
    dialCode: "976",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Montenegro",
    nameTranslations: {
      "sk": "Čierna Hora",
      "se": "Montenegro",
      "pl": "Czarnogóra",
      "no": "Montenegro",
      "ja": "モンテネグロ",
      "it": "Montenegro",
      "zh": "黑山",
      "nl": "Montenegro",
      "de": "Montenegro",
      "fr": "Monténégro",
      "es": "Montenegro",
      "en": "Montenegro",
      "pt_BR": "Montenegro",
      "sr-Cyrl": "Црна Гора",
      "sr-Latn": "Crna Gora",
      "zh_TW": "蒙特內哥羅",
      "tr": "Karadağ",
      "ro": "Muntenegru",
      "ar": "الجبل الأسود",
      "fa": "مونته‌نگرو",
      "yue": "黑山"
    },
    flag: "🇲🇪",
    code: "ME",
    dialCode: "382",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Montserrat",
    nameTranslations: {
      "sk": "Montserrat",
      "se": "Montserrat",
      "pl": "Montserrat",
      "no": "Montserrat",
      "ja": "モントセラト",
      "it": "Montserrat",
      "zh": "蒙特塞拉特",
      "nl": "Montserrat",
      "de": "Montserrat",
      "fr": "Montserrat",
      "es": "Montserrat",
      "en": "Montserrat",
      "pt_BR": "Montserrat",
      "sr-Cyrl": "Монтсерат",
      "sr-Latn": "Montserat",
      "zh_TW": "蒙哲臘",
      "tr": "Montserrat",
      "ro": "Montserrat",
      "ar": "مونتسرات",
      "fa": "مونتسرات",
      "yue": "蒙特塞拉特"
    },
    flag: "🇲🇸",
    code: "MS",
    dialCode: "1664",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Morocco",
    nameTranslations: {
      "sk": "Maroko",
      "se": "Marokko",
      "pl": "Maroko",
      "no": "Marokko",
      "ja": "モロッコ",
      "it": "Marocco",
      "zh": "摩洛哥",
      "nl": "Marokko",
      "de": "Marokko",
      "fr": "Maroc",
      "es": "Marruecos",
      "en": "Morocco",
      "pt_BR": "Marrocos",
      "sr-Cyrl": "Мароко",
      "sr-Latn": "Maroko",
      "zh_TW": "摩洛哥",
      "tr": "Fas",
      "ro": "Maroc",
      "ar": "المغرب",
      "fa": "مراکش",
      "yue": "摩洛哥"
    },
    flag: "🇲🇦",
    code: "MA",
    dialCode: "212",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Mozambique",
    nameTranslations: {
      "sk": "Mozambik",
      "se": "Mosambik",
      "pl": "Mozambik",
      "no": "Mosambik",
      "ja": "モザンビーク",
      "it": "Mozambico",
      "zh": "莫桑比克",
      "nl": "Mozambique",
      "de": "Mosambik",
      "fr": "Mozambique",
      "es": "Mozambique",
      "en": "Mozambique",
      "pt_BR": "Moçambique",
      "sr-Cyrl": "Мозамбик",
      "sr-Latn": "Mozambik",
      "zh_TW": "莫三比克",
      "tr": "Mozambik",
      "ro": "Mozambic",
      "ar": "موزمبيق",
      "fa": "موزامبیک",
      "yue": "莫桑比克"
    },
    flag: "🇲🇿",
    code: "MZ",
    dialCode: "258",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Myanmar",
    nameTranslations: {
      "sk": "Mjanmarsko",
      "se": "Burma",
      "pl": "Mjanma (Birma)",
      "no": "Myanmar (Burma)",
      "ja": "ミャンマー (ビルマ)",
      "it": "Myanmar (Birmania)",
      "zh": "缅甸",
      "nl": "Myanmar (Birma)",
      "de": "Myanmar",
      "fr": "Myanmar (Birmanie)",
      "es": "Myanmar (Birmania)",
      "en": "Myanmar (Burma)",
      "pt_BR": "Mianmar (Birmânia)",
      "sr-Cyrl": "Мјанмар (Бурма)",
      "sr-Latn": "Mjanmar (Burma)",
      "zh_TW": "緬甸",
      "tr": "Myanmar",
      "ro": "Myanmar",
      "ar": "ميانمار",
      "fa": "میانمار",
      "yue": "緬甸"
    },
    flag: "🇲🇲",
    code: "MM",
    dialCode: "95",
    minLength: 9,
    maxLength: 9,
  ),
];
