/// Module: core/constants
///
///*************************** FILE INFO ****************************///
/// File Name: countries_part_1.dart
/// Purpose: Country reference data, part 1 of 10.
/// Author: Knowticed Plus team
/// Updated: 11/8/2026 - Split out of the 7,574-LOC countries.dart (~5x the
///          hard cap). Data only, and still `const`, so every existing call
///          site stays synchronous and unchanged.

import 'package:grc_module/core/helper/main_helper/country.dart';

const List<Country> countriesPart1 = <Country>[
  Country(
    name: "Afghanistan",
    nameTranslations: {
      "sk": "Afganistan",
      "se": "Afghanistan",
      "pl": "Afganistan",
      "no": "Afghanistan",
      "ja": "アフガニスタン",
      "it": "Afghanistan",
      "zh": "阿富汗",
      "nl": "Afghanistan",
      "de": "Afghanistan",
      "fr": "Afghanistan",
      "es": "Afganistán",
      "en": "Afghanistan",
      "pt_BR": "Afeganistão",
      "sr-Cyrl": "Авганистан",
      "sr-Latn": "Avganistan",
      "zh_TW": "阿富汗",
      "tr": "Afganistan",
      "ro": "Afganistan",
      "ar": "أفغانستان",
      "fa": "افغانستان",
      "yue": "阿富汗"
    },
    flag: "🇦🇫",
    code: "AF",
    dialCode: "93",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Åland Islands",
    nameTranslations: {
      "sk": "Alandy",
      "se": "Ålánda",
      "pl": "Wyspy Alandzkie",
      "no": "Åland",
      "ja": "オーランド諸島",
      "it": "Isole Åland",
      "zh": "奥兰群岛",
      "nl": "Åland",
      "de": "Ålandinseln",
      "fr": "Îles Åland",
      "es": "Islas Åland",
      "en": "Åland Islands",
      "pt_BR": "Ilhas Aland",
      "sr-Cyrl": "Аландска Острва",
      "sr-Latn": "Alandska Ostrva",
      "zh_TW": "奧蘭群島",
      "tr": "Åland",
      "ro": "Insulele Åland",
      "ar": "جزر أولاند",
      "fa": "جزیره اولاند",
      "yue": "奧蘭群島"
    },
    flag: "🇦🇽",
    code: "AX",
    dialCode: "358",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Albania",
    nameTranslations: {
      "sk": "Albánsko",
      "se": "Albánia",
      "pl": "Albania",
      "no": "Albania",
      "ja": "アルバニア",
      "it": "Albania",
      "zh": "阿尔巴尼亚",
      "nl": "Albanië",
      "de": "Albanien",
      "fr": "Albanie",
      "es": "Albania",
      "en": "Albania",
      "pt_BR": "Albânia",
      "sr-Cyrl": "Албанија",
      "sr-Latn": "Albanija",
      "zh_TW": "阿爾巴尼亞",
      "tr": "Arnavutluk",
      "ro": "Albania",
      "ar": "ألبانيا",
      "fa": "آلبانی",
      "yue": "阿爾巴尼亞"
    },
    flag: "🇦🇱",
    code: "AL",
    dialCode: "355",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Algeria",
    nameTranslations: {
      "sk": "Alžírsko",
      "se": "Algeria",
      "pl": "Algieria",
      "no": "Algerie",
      "ja": "アルジェリア",
      "it": "Algeria",
      "zh": "阿尔及利亚",
      "nl": "Algerije",
      "de": "Algerien",
      "fr": "Algérie",
      "es": "Argelia",
      "en": "Algeria",
      "pt_BR": "Argélia",
      "sr-Cyrl": "Аргентина",
      "sr-Latn": "Argentina",
      "zh_TW": "阿爾及利亞",
      "tr": "Cezayir",
      "ro": "Algeria",
      "ar": "الجزائر",
      "fa": "الجزیره",
      "yue": "阿爾及利亞"
    },
    flag: "🇩🇿",
    code: "DZ",
    dialCode: "213",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "American Samoa",
    nameTranslations: {
      "sk": "Americká Samoa",
      "se": "Amerihká Samoa",
      "pl": "Samoa Amerykańskie",
      "no": "Amerikansk Samoa",
      "ja": "米領サモア",
      "it": "Samoa americane",
      "zh": "美属萨摩亚",
      "nl": "Amerikaans-Samoa",
      "de": "Amerikanisch-Samoa",
      "fr": "Samoa américaines",
      "es": "Samoa Americana",
      "en": "American Samoa",
      "pt_BR": "Samoa Americana",
      "sr-Cyrl": "Америчка Самоа",
      "sr-Latn": "Američka Samoa",
      "zh_TW": "美屬薩摩亞",
      "tr": "Amerikan Samoası",
      "ro": "Samoa Americană",
      "ar": "ساموا الأمريكية",
      "fa": "ساموا آمریکا",
      "yue": "美屬薩摩亞"
    },
    flag: "🇦🇸",
    code: "AS",
    dialCode: "1684",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Andorra",
    nameTranslations: {
      "sk": "Andorra",
      "se": "Andorra",
      "pl": "Andora",
      "no": "Andorra",
      "ja": "アンドラ",
      "it": "Andorra",
      "zh": "安道尔",
      "nl": "Andorra",
      "de": "Andorra",
      "fr": "Andorre",
      "es": "Andorra",
      "en": "Andorra",
      "pt_BR": "Andorra",
      "sr-Cyrl": "Андора",
      "sr-Latn": "Andora",
      "zh_TW": "安道爾",
      "tr": "Andora",
      "ro": "Andorra",
      "ar": "أندورا",
      "fa": "آندورا",
      "yue": "安道爾"
    },
    flag: "🇦🇩",
    code: "AD",
    dialCode: "376",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Angola",
    nameTranslations: {
      "sk": "Angola",
      "se": "Angola",
      "pl": "Angola",
      "no": "Angola",
      "ja": "アンゴラ",
      "it": "Angola",
      "zh": "安哥拉",
      "nl": "Angola",
      "de": "Angola",
      "fr": "Angola",
      "es": "Angola",
      "en": "Angola",
      "pt_BR": "Angola",
      "sr-Cyrl": "Ангола",
      "sr-Latn": "Angola",
      "zh_TW": "安哥拉",
      "tr": "Angola",
      "ro": "Angola",
      "ar": "أنغولا",
      "fa": "آنگولا",
      "yue": "安哥拉"
    },
    flag: "🇦🇴",
    code: "AO",
    dialCode: "244",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Anguilla",
    nameTranslations: {
      "sk": "Anguilla",
      "se": "Anguilla",
      "pl": "Anguilla",
      "no": "Anguilla",
      "ja": "アンギラ",
      "it": "Anguilla",
      "zh": "安圭拉",
      "nl": "Anguilla",
      "de": "Anguilla",
      "fr": "Anguilla",
      "es": "Anguila",
      "en": "Anguilla",
      "pt_BR": "Anguilla",
      "sr-Cyrl": "Ангвила",
      "sr-Latn": "Angvila",
      "zh_TW": "安圭拉",
      "tr": "Anguilla",
      "ro": "Anguilla",
      "ar": "أنغويلا",
      "fa": "آنگولیا",
      "yue": "安圭拉"
    },
    flag: "🇦🇮",
    code: "AI",
    dialCode: "1264",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Antarctica",
    nameTranslations: {
      "sk": "Antarktída",
      "se": "Antárktis",
      "pl": "Antarktyda",
      "no": "Antarktis",
      "ja": "南極",
      "it": "Antartide",
      "zh": "南极洲",
      "nl": "Antarctica",
      "de": "Antarktis",
      "fr": "Antarctique",
      "es": "Antártida",
      "en": "Antarctica",
      "pt_BR": "Antártica",
      "sr-Cyrl": "Антарктик",
      "sr-Latn": "Antarktik",
      "zh_TW": "南極",
      "tr": "Antarktika",
      "ro": "Antarctica",
      "ar": "القارة القطبية الجنوبية",
      "fa": "قطب جنوب",
      "yue": "南极洲"
    },
    flag: "🇦🇶",
    code: "AQ",
    dialCode: "672",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Antigua and Barbuda",
    nameTranslations: {
      "sk": "Antigua a Barbuda",
      "se": "Antigua ja Barbuda",
      "pl": "Antigua i Barbuda",
      "no": "Antigua og Barbuda",
      "ja": "アンティグア・バーブーダ",
      "it": "Antigua e Barbuda",
      "zh": "安提瓜和巴布达",
      "nl": "Antigua en Barbuda",
      "de": "Antigua und Barbuda",
      "fr": "Antigua-et-Barbuda",
      "es": "Antigua y Barbuda",
      "en": "Antigua & Barbuda",
      "pt_BR": "Antigua e Barbuda",
      "sr-Cyrl": "Антигва и Барбуда",
      "sr-Latn": "Antigva i Barbuda",
      "zh_TW": "安提瓜和巴布達",
      "tr": "Antigua ve Barbuda",
      "ro": "Antigua şi Barbuda",
      "ar": "أنتيغوا وباربودا",
      "fa": "آنتیگوآ و باربودا",
      "yue": "安提瓜同巴布达"
    },
    flag: "🇦🇬",
    code: "AG",
    dialCode: "1268",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Argentina",
    nameTranslations: {
      "sk": "Argentína",
      "se": "Argentina",
      "pl": "Argentyna",
      "no": "Argentina",
      "ja": "アルゼンチン",
      "it": "Argentina",
      "zh": "阿根廷",
      "nl": "Argentinië",
      "de": "Argentinien",
      "fr": "Argentine",
      "es": "Argentina",
      "en": "Argentina",
      "pt_BR": "Argentina",
      "sr-Cyrl": "Аргентина",
      "sr-Latn": "Argentina",
      "zh_TW": "阿根廷",
      "tr": "Arjantin",
      "ro": "Argentina",
      "ar": "الأرجنتين",
      "fa": "آرژانتین",
      "yue": "阿根廷"
    },
    flag: "🇦🇷",
    code: "AR",
    dialCode: "54",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Armenia",
    nameTranslations: {
      "sk": "Arménsko",
      "se": "Armenia",
      "pl": "Armenia",
      "no": "Armenia",
      "ja": "アルメニア",
      "it": "Armenia",
      "zh": "亚美尼亚",
      "nl": "Armenië",
      "de": "Armenien",
      "fr": "Arménie",
      "es": "Armenia",
      "en": "Armenia",
      "pt_BR": "Armênia",
      "sr-Cyrl": "Јерменија",
      "sr-Latn": "Jermenija",
      "zh_TW": "亞美尼亞",
      "tr": "Ermenistan",
      "ro": "Armenia",
      "ar": "أرمينيا",
      "fa": "ارمنستان",
      "yue": "亞美尼亞"
    },
    flag: "🇦🇲",
    code: "AM",
    dialCode: "374",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Aruba",
    nameTranslations: {
      "sk": "Aruba",
      "se": "Aruba",
      "pl": "Aruba",
      "no": "Aruba",
      "ja": "アルバ",
      "it": "Aruba",
      "zh": "阿鲁巴",
      "nl": "Aruba",
      "de": "Aruba",
      "fr": "Aruba",
      "es": "Aruba",
      "en": "Aruba",
      "pt_BR": "Aruba",
      "sr-Cyrl": "Аруба",
      "sr-Latn": "Aruba",
      "zh_TW": "阿魯巴",
      "tr": "Aruba",
      "ro": "Aruba",
      "ar": "أروبا",
      "fa": "آروبا",
      "yue": "阿魯巴島"
    },
    flag: "🇦🇼",
    code: "AW",
    dialCode: "297",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Australia",
    nameTranslations: {
      "sk": "Austrália",
      "se": "Austrália",
      "pl": "Australia",
      "no": "Australia",
      "ja": "オーストラリア",
      "it": "Australia",
      "zh": "澳大利亚",
      "nl": "Australië",
      "de": "Australien",
      "fr": "Australie",
      "es": "Australia",
      "en": "Australia",
      "pt_BR": "Austrália",
      "sr-Cyrl": "Аустралија",
      "sr-Latn": "Australija",
      "zh_TW": "澳州",
      "tr": "Avustralya",
      "ro": "Australia",
      "ar": "أستراليا",
      "fa": "استرالیا",
      "yue": "澳洲"
    },
    flag: "🇦🇺",
    code: "AU",
    dialCode: "61",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Austria",
    nameTranslations: {
      "sk": "Rakúsko",
      "se": "Nuortariika",
      "pl": "Austria",
      "no": "Østerrike",
      "ja": "オーストリア",
      "it": "Austria",
      "zh": "奥地利",
      "nl": "Oostenrijk",
      "de": "Österreich",
      "fr": "Autriche",
      "es": "Austria",
      "en": "Austria",
      "pt_BR": "Áustria",
      "sr-Cyrl": "Аустрија",
      "sr-Latn": "Austrija",
      "zh_TW": "奥地利",
      "tr": "Avusturya",
      "ro": "Austria",
      "ar": "النمسا",
      "fa": "اتریش",
      "yue": "奧地利"
    },
    flag: "🇦🇹",
    code: "AT",
    dialCode: "43",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: "Azerbaijan",
    nameTranslations: {
      "sk": "Azerbajdžan",
      "se": "Aserbaižan",
      "pl": "Azerbejdżan",
      "no": "Aserbajdsjan",
      "ja": "アゼルバイジャン",
      "it": "Azerbaigian",
      "zh": "阿塞拜疆",
      "nl": "Azerbeidzjan",
      "de": "Aserbaidschan",
      "fr": "Azerbaïdjan",
      "es": "Azerbaiyán",
      "en": "Azerbaijan",
      "pt_BR": "Azerbaijão",
      "sr-Cyrl": "Азербејџан",
      "sr-Latn": "Azerbejdžan",
      "zh_TW": "亞塞拜然",
      "tr": "Azerbaycan",
      "ro": "Azerbaidjan",
      "ar": "أذربيجان",
      "fa": "آذربایجان",
      "yue": "阿塞拜疆"
    },
    flag: "🇦🇿",
    code: "AZ",
    dialCode: "994",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Bahamas",
    nameTranslations: {
      "sk": "Bahamy",
      "se": "Bahamas",
      "pl": "Bahamy",
      "no": "Bahamas",
      "ja": "バハマ",
      "it": "Bahamas",
      "zh": "巴哈马",
      "nl": "Bahama's",
      "de": "Bahamas",
      "fr": "Bahamas",
      "es": "Bahamas",
      "en": "Bahamas",
      "pt_BR": "Bahamas",
      "sr-Cyrl": "Бахаме",
      "sr-Latn": "Bahame",
      "zh_TW": "巴哈馬",
      "tr": "Bahama",
      "ro": "Bahamas",
      "ar": "باهاماس",
      "fa": "باهاماس",
      "yue": "巴哈馬"
    },
    flag: "🇧🇸",
    code: "BS",
    dialCode: "1242",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Bahrain",
    nameTranslations: {
      "sk": "Bahrajn",
      "se": "Bahrain",
      "pl": "Bahrajn",
      "no": "Bahrain",
      "ja": "バーレーン",
      "it": "Bahrein",
      "zh": "巴林",
      "nl": "Bahrein",
      "de": "Bahrain",
      "fr": "Bahreïn",
      "es": "Baréin",
      "en": "Bahrain",
      "pt_BR": "Bahrain",
      "sr-Cyrl": "Бахреин",
      "sr-Latn": "Bahrein",
      "zh_TW": "巴林",
      "tr": "Bahreyn",
      "ro": "Bahrein",
      "ar": "البحرين",
      "fa": "بحرین",
      "yue": "巴林"
    },
    flag: "🇧🇭",
    code: "BH",
    dialCode: "973",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bangladesh",
    nameTranslations: {
      "sk": "Bangladéš",
      "se": "Bangladesh",
      "pl": "Bangladesz",
      "no": "Bangladesh",
      "ja": "バングラデシュ",
      "it": "Bangladesh",
      "zh": "孟加拉国",
      "nl": "Bangladesh",
      "de": "Bangladesch",
      "fr": "Bangladesh",
      "es": "Bangladés",
      "en": "Bangladesh",
      "pt_BR": "Bangladesh",
      "sr-Cyrl": "Бангладеш",
      "sr-Latn": "Bangladeš",
      "zh_TW": "孟加拉",
      "tr": "Bangladeş",
      "ro": "Bangladesh",
      "ar": "بنغلاديش",
      "fa": "بنگلادش",
      "yue": "孟加拉囯"
    },
    flag: "🇧🇩",
    code: "BD",
    dialCode: "880",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Barbados",
    nameTranslations: {
      "sk": "Barbados",
      "se": "Barbados",
      "pl": "Barbados",
      "no": "Barbados",
      "ja": "バルバドス",
      "it": "Barbados",
      "zh": "巴巴多斯",
      "nl": "Barbados",
      "de": "Barbados",
      "fr": "Barbade",
      "es": "Barbados",
      "en": "Barbados",
      "pt_BR": "Barbados",
      "sr-Cyrl": "Барбадос",
      "sr-Latn": "Barbados",
      "zh_TW": "巴巴多斯",
      "tr": "Barbados",
      "ro": "Barbados",
      "ar": "باربادوس",
      "fa": "باربادوس",
      "yue": "巴巴多斯"
    },
    flag: "🇧🇧",
    code: "BB",
    dialCode: "1246",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Belarus",
    nameTranslations: {
      "sk": "Bielorusko",
      "se": "Vilges-Ruošša",
      "pl": "Białoruś",
      "no": "Hviterussland",
      "ja": "ベラルーシ",
      "it": "Bielorussia",
      "zh": "白俄罗斯",
      "nl": "Belarus",
      "de": "Belarus",
      "fr": "Biélorussie",
      "es": "Bielorrusia",
      "en": "Belarus",
      "pt_BR": "Bielo-Rússia",
      "sr-Cyrl": "Белорусија",
      "sr-Latn": "Belorusija",
      "zh_TW": "白俄羅斯",
      "tr": "Belarus",
      "ro": "Belarus",
      "ar": "بيلاروس",
      "fa": "بلاروس",
      "yue": "白俄羅斯"
    },
    flag: "🇧🇾",
    code: "BY",
    dialCode: "375",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Belgium",
    nameTranslations: {
      "sk": "Belgicko",
      "se": "Belgia",
      "pl": "Belgia",
      "no": "Belgia",
      "ja": "ベルギー",
      "it": "Belgio",
      "zh": "比利时",
      "nl": "België",
      "de": "Belgien",
      "fr": "Belgique",
      "es": "Bélgica",
      "en": "Belgium",
      "pt_BR": "Bélgica",
      "sr-Cyrl": "Белгија",
      "sr-Latn": "Belgija",
      "zh_TW": "比利時",
      "tr": "Belçika",
      "ro": "Belgia",
      "ar": "بلجيكا",
      "fa": "بلژیک",
      "yue": "比利時"
    },
    flag: "🇧🇪",
    code: "BE",
    dialCode: "32",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Belize",
    nameTranslations: {
      "sk": "Belize",
      "se": "Belize",
      "pl": "Belize",
      "no": "Belize",
      "ja": "ベリーズ",
      "it": "Belize",
      "zh": "伯利兹",
      "nl": "Belize",
      "de": "Belize",
      "fr": "Belize",
      "es": "Belice",
      "en": "Belize",
      "pt_BR": "Belize",
      "sr-Cyrl": "Белизе",
      "sr-Latn": "Belize",
      "zh_TW": "伯利茲",
      "tr": "Belize",
      "ro": "Belize",
      "ar": "بليز",
      "fa": "بليز",
      "yue": "伯利茲"
    },
    flag: "🇧🇿",
    code: "BZ",
    dialCode: "501",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Benin",
    nameTranslations: {
      "sk": "Benin",
      "se": "Benin",
      "pl": "Benin",
      "no": "Benin",
      "ja": "ベナン",
      "it": "Benin",
      "zh": "贝宁",
      "nl": "Benin",
      "de": "Benin",
      "fr": "Bénin",
      "es": "Benín",
      "en": "Benin",
      "pt_BR": "Benin",
      "sr-Cyrl": "Бенин",
      "sr-Latn": "Benin",
      "zh_TW": "貝南",
      "tr": "Benin",
      "ro": "Benin",
      "ar": "بنين",
      "fa": "بنين",
      "yue": "貝寧"
    },
    flag: "🇧🇯",
    code: "BJ",
    dialCode: "229",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bermuda",
    nameTranslations: {
      "sk": "Bermudy",
      "se": "Bermuda",
      "pl": "Bermudy",
      "no": "Bermuda",
      "ja": "バミューダ",
      "it": "Bermuda",
      "zh": "百慕大",
      "nl": "Bermuda",
      "de": "Bermuda",
      "fr": "Bermudes",
      "es": "Bermudas",
      "en": "Bermuda",
      "pt_BR": "Bermudas",
      "sr-Cyrl": "Бермуда",
      "sr-Latn": "Bermuda",
      "zh_TW": "百慕達",
      "tr": "Bermuda",
      "ro": "Insulele Bermude",
      "ar": "برمودا",
      "fa": "برمودا",
      "yue": "百慕大"
    },
    flag: "🇧🇲",
    code: "BM",
    dialCode: "1441",
    minLength: 7,
    maxLength: 7,
  ),
];
