/// ************************* FILE INFO *************************
/// File Name: grc_events.dart
/// Module:    GRC
/// Purpose:   Every notification this module can raise, with its default
///            bilingual title/body exactly as specified in
///            "Knowticed Plus — Notification & Validation".
///
/// The enum is the DEFAULT / RESET source only. At runtime
/// AppNotificationSender reads `notification_templates/<module>_<key>`
/// from Firestore first, so any text an admin edits in Notification
/// Control still wins. Editing this file changes the fallback + the
/// "Reset to default" value.
///
/// RULE: never write an event key as a raw string. Use this enum.

import '../notification_event.dart';
import 'package:grc_module/core/enums/app_module.dart';
import 'package:grc_module/core/enums/template_variable.dart';

enum GrcNotificationEvent implements NotificationEvent {
  moduleCreated(
    key: 'module_created',
    group: '',
    titleEn: 'New GRC Module Created',
    titleAr: 'تم إنشاء وحدة جديدة',
    bodyEn: 'The GRC module {{moduleName}} has been successfully created and is now available in the Governance, Risk, and Compliance repository.',
    bodyAr: 'تم إنشاء وحدة الحوكمة والمخاطر والامتثال {{moduleName}} بنجاح، وهي متاحة الآن ضمن وحدات النظام.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleOwnerAssigned(
    key: 'module_owner_assigned',
    group: '',
    titleEn: 'Module Ownership Assigned',
    titleAr: 'تم تعيين مالك للوحدة',
    bodyEn: 'You have been assigned as the Module Owner for {{moduleName}}. Please review the module information.',
    bodyAr: 'تم تعيينك كمالك لوحدة {{moduleName}}، وأصبحت مسؤولاً عن إدارتها وصيانتها.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleOwnerChanged(
    key: 'module_owner_changed',
    group: '',
    titleEn: 'Module Ownership Updated',
    titleAr: 'تم تغيير مالك الوحدة',
    bodyEn: 'Module ownership for {{moduleName}} has been reassigned to {{newOwnerName}}. Previous ownership records have been updated accordingly.',
    bodyAr: 'تم إعادة تعيين ملكية وحدة {{moduleName}} إلى {{newOwnerName}}، وتم تحديث سجلات الملكية وفقًا لذلك.',
    variables: {TemplateVariable.moduleName, TemplateVariable.newOwnerName},
  ),
  activationDateUpdated(
    key: 'activation_date_updated',
    group: '',
    titleEn: 'Module Activation Date Updated',
    titleAr: 'تم تحديث تاريخ التفعيل',
    bodyEn: 'The activation date for {{moduleName}} has been updated from {{oldDate}} to {{newDate}}. Please review your planned activities accordingly.',
    bodyAr: 'تم تحديث تاريخ تفعيل وحدة {{moduleName}} من {{oldDate}} إلى {{newDate}}. يرجى مراجعة خطط العمل وفقًا للتاريخ الجديد.',
    variables: {TemplateVariable.moduleName, TemplateVariable.oldDate, TemplateVariable.newDate},
  ),
  activationDateToday(
    key: 'activation_date_today',
    group: '',
    titleEn: 'Module Activation Due Today',
    titleAr: 'موعد التفعيل اليوم',
    bodyEn: 'Today is the scheduled activation date for {{moduleName}}.',
    bodyAr: 'اليوم هو تاريخ التفعيل المجدول للوحدة {{moduleName}}.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleUpdatedEdited(
    key: 'module_updated_edited',
    group: '',
    titleEn: 'GRC Module Updated',
    titleAr: 'تم تحديث الوحدة',
    bodyEn: 'The information for {{moduleName}} has been updated.',
    bodyAr: 'تم تحديث بيانات وحدة {{moduleName}} بنجاح، وأصبحت أحدث المعلومات متاحة للمستخدمين المخولين.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleStatusChangedActivated(
    key: 'module_status_changed_activated',
    group: '',
    titleEn: 'GRC Module Activated',
    titleAr: 'تم تفعيل الوحدة',
    bodyEn: 'The status of {{moduleName}} has been changed to Active. The activation has been completed successfully.',
    bodyAr: 'تم تغيير حالة الوحدة {{moduleName}} إلى نشطة، وتم إكمال عملية التفعيل بنجاح.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleStatusChangedDeactivated(
    key: 'module_status_changed_deactivated',
    group: '',
    titleEn: 'GRC Module Deactivated',
    titleAr: 'تم إيقاف الوحدة',
    bodyEn: 'The status of {{moduleName}} has been changed to Inactive. Users can no longer perform activities within this module until it is reactivated.',
    bodyAr: 'تم تغيير حالة وحدة {{moduleName}} إلى غير نشطة، ولن يتمكن المستخدمون من استخدامها حتى يتم إعادة تفعيلها.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleDeleted(
    key: 'module_deleted',
    group: '',
    titleEn: 'GRC Module Removed',
    titleAr: 'تم حذف الوحدة',
    bodyEn: 'The GRC module {{moduleName}} has been moved to the Removed Modules section. It can be restored if required.',
    bodyAr: 'تم نقل وحدة {{moduleName}} إلى قسم الوحدات المحذوفة، ويمكن استعادتها عند الحاجة.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleRestored(
    key: 'module_restored',
    group: '',
    titleEn: 'GRC Module Restored',
    titleAr: 'تم استعادة الوحدة',
    bodyEn: 'The GRC module {{moduleName}} has been successfully restored and is now available again in the system.',
    bodyAr: 'تم استعادة وحدة {{moduleName}} بنجاح، وأصبحت متاحة مرة أخرى داخل النظام.',
    variables: {TemplateVariable.moduleName},
  ),
  moduleRemovedFromDepartment(
    key: 'module_removed_from_department',
    group: '',
    titleEn: 'Module Removed from Your Department',
    titleAr: 'تم نقل الوحدة من إدارتك',
    bodyEn: 'The GRC module {{moduleName}} has been removed from {{departmentName}} . It is no longer under your department\'s responsibility',
    bodyAr: 'تم حذف وحدة الحوكمة والمخاطر والامتثال {{moduleName}} من إدارة {{departmentName}}. لم تعد هذه الوحدة ضمن مسؤولية إدارتك.',
    variables: {TemplateVariable.moduleName, TemplateVariable.departmentName},
  ),
  policyCreated(
    key: 'policy_created',
    group: 'Policy & Control',
    titleEn: 'New Policy Created Successfully',
    titleAr: 'تم إنشاء سياسة جديدة',
    bodyEn: 'The policy {{policyName}} has been successfully created under the GRC module {{moduleName}}.',
    bodyAr: 'تم إنشاء السياسة {{policyName}} بنجاح ضمن وحدة الحوكمة {{moduleName}}، وأصبحت متاحة الآن للإدارة والتعيين.',
    variables: {TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  newPoliciesAddedBulkUpload(
    key: 'new_policies_added_bulk_upload',
    group: 'Policy & Control',
    titleEn: 'New Policies Added (Bulk Upload)',
    titleAr: 'تمت إضافة سياسات جديدة',
    bodyEn: 'New policies have been added through a bulk upload by {{uploadedByUserName}} under module {{moduleName}}.',
    bodyAr: 'تمت إضافة سياسات جديدة من خلال استيراد جماعي بواسطة {{uploadedByUserName}} ضمن الوحدة {{moduleName}}.',
    variables: {TemplateVariable.uploadedByUserName, TemplateVariable.moduleName},
  ),
  policyUpdatedEdited(
    key: 'policy_updated_edited',
    group: 'Policy & Control',
    titleEn: 'Policy Updated',
    titleAr: 'تم تحديث السياسة',
    bodyEn: 'The policy {{policyName}} has been updated under module {{moduleName}}.',
    bodyAr: 'تم تحديث السياسة {{policyName}} ضمن الوحدة {{moduleName}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  policyScheduledForActivation(
    key: 'policy_scheduled_for_activation',
    group: 'Policy & Control',
    titleEn: 'Policy Activation Scheduled',
    titleAr: 'تم جدولة تفعيل السياسة',
    bodyEn: 'The policy {{policyName}} has been scheduled to become active on {{startDate}}.',
    bodyAr: 'تم جدولة تفعيل السياسة {{policyName}} بتاريخ {{startDate}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.startDate},
  ),
  policyActivationDateUpdated(
    key: 'policy_activation_date_updated',
    group: 'Policy & Control',
    titleEn: 'Policy Activation Date Updated',
    titleAr: 'تم تحديث تاريخ التفعيل',
    bodyEn: 'The activation date of {{policyName}} has been changed from {{oldStartDate}} to {{newStartDate}}.',
    bodyAr: 'تم تحديث تاريخ تفعيل السياسة {{policyName}} من {{oldStartDate}} إلى {{newStartDate}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.oldStartDate, TemplateVariable.newStartDate},
  ),
  e14DaysBeforePolicyStartDate(
    key: '14_days_before_policy_start_date',
    group: 'Policy & Control',
    titleEn: 'Upcoming Policy Activation Reminder',
    titleAr: 'تذكير باقتراب تفعيل السياسة',
    bodyEn: 'The policy {{policyName}} is scheduled to become active in 14 days on {{startDate}}. Please review the policy details and ensure everything is ready before the activation date.',
    bodyAr: 'سيتم تفعيل السياسة {{policyName}} بعد 14 يومًا بتاريخ {{startDate}}. يرجى مراجعة تفاصيل السياسة ، والتأكد من جاهزية جميع المتطلبات قبل موعد التفعيل.',
    variables: {TemplateVariable.policyName, TemplateVariable.startDate},
  ),
  policyActivationDateToday(
    key: 'policy_activation_date_today',
    group: 'Policy & Control',
    titleEn: 'Policy Activation Due Today',
    titleAr: 'موعد تفعيل السياسة اليوم',
    bodyEn: 'Today is the scheduled activation date for {{policyName}}.',
    bodyAr: 'اليوم هو موعد تفعيل السياسة {{policyName}}.',
    variables: {TemplateVariable.policyName},
  ),
  e14DaysBeforePolicyExpirationDate(
    key: '14_days_before_policy_expiration_date',
    group: 'Policy & Control',
    titleEn: 'Policy Expiration Reminder',
    titleAr: 'تذكير باقتراب انتهاء صلاحية السياسة',
    bodyEn: 'The policy {{policyName}} will expire in 14 days on {{endDate}}.',
    bodyAr: 'ستنتهي صلاحية السياسة {{policyName}} بعد 14 يومًا بتاريخ {{endDate}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.endDate},
  ),
  policyEndDateUpdated(
    key: 'policy_end_date_updated',
    group: 'Policy & Control',
    titleEn: 'Policy Expiration Date Updated',
    titleAr: 'تم تحديث تاريخ انتهاء السياسة',
    bodyEn: 'The expiration date for {{policyName}} has been updated from {{oldEndDate}} to {{newEndDate}}.',
    bodyAr: 'تم تحديث تاريخ انتهاء صلاحية السياسة {{policyName}} من {{oldEndDate}} إلى {{newEndDate}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.oldEndDate, TemplateVariable.newEndDate},
  ),
  policyExpired(
    key: 'policy_expired',
    group: 'Policy & Control',
    titleEn: 'Policy Expired',
    titleAr: 'انتهت صلاحية السياسة',
    bodyEn: 'The policy {{policyName}} has reached its expiration date and is now marked as expired. Please review and renew it if required.',
    bodyAr: 'انتهت صلاحية السياسة {{policyName}}، وتم تصنيفها كمنتهية الصلاحية. يرجى مراجعتها وتجديدها أو استبدالها عند الحاجة.',
    variables: {TemplateVariable.policyName},
  ),
  policyWeightUpdated(
    key: 'policy_weight_updated',
    group: 'Policy & Control',
    titleEn: 'Policy Weight Updated',
    titleAr: 'تم تحديث وزن السياسة',
    bodyEn: 'The weight of {{policyName}} has been updated.',
    bodyAr: 'تم تحديث وزن السياسة {{policyName}}.',
    variables: {TemplateVariable.policyName},
  ),
  policyDeleted(
    key: 'policy_deleted',
    group: 'Policy & Control',
    titleEn: 'Policy Removed',
    titleAr: 'تم حذف السياسة',
    bodyEn: 'The policy {{policyName}} has been removed and moved to the removed policies section.',
    bodyAr: 'تم نقل السياسة {{policyName}} إلى قسم السياسات المحذوفة.',
    variables: {TemplateVariable.policyName},
  ),
  policyActivated(
    key: 'policy_activated',
    group: 'Policy & Control',
    titleEn: 'Policy Activated',
    titleAr: 'تم تفعيل السياسة',
    bodyEn: 'The policy {{policyName}} has been activated and is now effective within the organization.',
    bodyAr: 'تم تفعيل السياسة {{policyName}}، وأصبحت سارية داخل المؤسسة.',
    variables: {TemplateVariable.policyName},
  ),
  policyDeactivated(
    key: 'policy_deactivated',
    group: 'Policy & Control',
    titleEn: 'Policy Deactivated',
    titleAr: 'تم إيقاف السياسة',
    bodyEn: 'The policy {{policyName}} has been deactivated. It will no longer be available for operational use until it is activated again.',
    bodyAr: 'تم إيقاف السياسة {{policyName}}، ولن تكون متاحة للاستخدام حتى يتم إعادة تفعيلها.',
    variables: {TemplateVariable.policyName},
  ),
  policyWeightIssueDetected(
    key: 'policy_weight_issue_detected',
    group: 'Policy & Control',
    titleEn: 'Policy Weight Issue Detected',
    titleAr: 'تم اكتشاف مشكلة في وزن السياسة',
    bodyEn: 'A weight issue has been identified for {{policyName}}. Please review the policy weight configuration.',
    bodyAr: 'تم اكتشاف مشكلة في وزن السياسة {{policyName}}. يرجى مراجعة إعدادات الوزن.',
    variables: {TemplateVariable.policyName},
  ),
  policyWeightIssueResolved(
    key: 'policy_weight_issue_resolved',
    group: 'Policy & Control',
    titleEn: 'Policy Weight Issue Resolved',
    titleAr: 'تم حل مشكلة وزن السياسة',
    bodyEn: 'The weight issue affecting {{policyName}} has been resolved.',
    bodyAr: 'تم حل مشكلة وزن السياسة {{policyName}}.',
    variables: {TemplateVariable.policyName},
  ),
  controlAddedToPolicy(
    key: 'control_added_to_policy',
    group: 'Policy & Control',
    titleEn: 'New Control Added',
    titleAr: 'تمت إضافة ضابط جديد',
    bodyEn: 'A new control {{controlName}} has been added to the policy {{policyName}}. Please review the updated policy configuration if required.',
    bodyAr: 'تمت إضافة الضابط {{controlName}} إلى السياسة {{policyName}}. يرجى مراجعة السياسة المحدثة عند الحاجة.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlAddedToPolicyBulkUpload(
    key: 'control_added_to_policy_bulk_upload',
    group: 'Policy & Control',
    titleEn: 'Control Added to Policy (bulk upload)',
    titleAr: 'تمت إضافة ضوابط جديدة',
    bodyEn: 'New controls have been added to the policy {{policyName}} through a bulk upload by {{userName}}. Please review the newly added controls.',
    bodyAr: 'تمت إضافة ضوابط جديدة  إلى السياسة {{policyName}} من خلال استيراد جماعي بواسطة {{userName}}. يرجى مراجعة الضوابط المضافة حديثًا.',
    variables: {TemplateVariable.policyName, TemplateVariable.userName},
  ),
  departmentAssignedToControl(
    key: 'department_assigned_to_control',
    group: 'Policy & Control',
    titleEn: 'Department Assigned',
    titleAr: 'تم تعيين قسم للضبط',
    bodyEn: 'The department {{departmentName}} has been assigned to control {{controlName}} under policy {{policyName}} in module {{moduleName}}.',
    bodyAr: 'تم تعيين القسم {{departmentName}} للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.departmentName, TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlUpdated(
    key: 'control_updated',
    group: 'Policy & Control',
    titleEn: 'Policy Control Updated',
    titleAr: 'تم تحديث الضابط',
    bodyEn: 'The control {{controlName}} within {{policyName}} has been updated successfully. The latest configuration is now available.',
    bodyAr: 'تم تحديث الضابط {{controlName}} ضمن السياسة {{policyName}} بنجاح، وأصبحت أحدث البيانات متاحة.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlDeleted(
    key: 'control_deleted',
    group: 'Policy & Control',
    titleEn: 'Policy Control Removed',
    titleAr: 'تم حذف الضابط',
    bodyEn: 'The control {{controlName}} has been removed from the policy {{policyName}}. Please ensure this change does not affect compliance requirements.',
    bodyAr: 'تم حذف الضابط {{controlName}} من السياسة {{policyName}}. يرجى التأكد من أن هذا التغيير لا يؤثر على متطلبات الامتثال.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlWeightUpdated(
    key: 'control_weight_updated',
    group: 'Policy & Control',
    titleEn: 'Control Weight Changed',
    titleAr: 'تم تحديث وزن الضابط',
    bodyEn: 'The weight of {{controlName}} has been updated from {{oldWeight}} to {{newWeight}} in {{policyName}}.',
    bodyAr: 'تم تحديث وزن الضابط {{controlName}} من {{oldWeight}} إلى {{newWeight}} ضمن السياسة {{policyName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.oldWeight, TemplateVariable.newWeight, TemplateVariable.policyName},
  ),
  controlAssignedToChampion(
    key: 'control_assigned_to_champion',
    group: 'Policy & Control',
    titleEn: 'Control Assigned',
    titleAr: 'تم تعيين ضابط إليك',
    bodyEn: 'You have been assigned responsibility for the control {{controlName}} within {{policyName}}.',
    bodyAr: 'تم تعيين مسؤولية الضابط {{controlName}} ضمن السياسة {{policyName}} إليك.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlChampionChangedNewChampion(
    key: 'control_champion_changed_new_champion',
    group: 'Policy & Control',
    titleEn: 'New Control Champion Assigned',
    titleAr: 'تم تعيين بطل ضبط جديد',
    bodyEn: 'You have been assigned as the Control Champion for {{controlName}} under policy {{policyName}} in module {{moduleName}}.',
    bodyAr: 'تم تعيينك كبطل الضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlChampionChangedPreviousChampion(
    key: 'control_champion_changed_previous_champion',
    group: 'Policy & Control',
    titleEn: 'Control Champion Assignment Removed',
    titleAr: 'تم إلغاء تعيينك كبطل للضبط',
    bodyEn: 'You are no longer assigned as the Control Champion for {{controlName}} under policy {{policyName}} in module {{moduleName}}.',
    bodyAr: 'لم تعد معينًا كبطل للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlOwnerChangedNewOwner(
    key: 'control_owner_changed_new_owner',
    group: 'Policy & Control',
    titleEn: 'New Control Owner Assigned',
    titleAr: 'تم تعيين مالك جديد للضبط',
    bodyEn: 'You have been assigned as the Control Owner for {{controlName}} under policy {{policyName}} in module {{moduleName}}.',
    bodyAr: 'تم تعيينك كمالك للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlOwnerChangedPreviousOwner(
    key: 'control_owner_changed_previous_owner',
    group: 'Policy & Control',
    titleEn: 'Control Owner Assignment Removed',
    titleAr: 'تم إلغاء تعيينك كمالك للضبط',
    bodyEn: 'You are no longer assigned as the Control Owner for {{controlName}} under policy {{policyName}} in module {{moduleName}}.',
    bodyAr: 'لم تعد معينًا كمالك للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlDeactivated(
    key: 'control_deactivated',
    group: 'Policy & Control',
    titleEn: 'Control Deactivated',
    titleAr: 'تم إيقاف الضابط',
    bodyEn: 'The control {{controlName}} under the policy {{policyName}} has been deactivated. It will no longer be available for operational use until it is reactivated.',
    bodyAr: 'تم إيقاف الضابط {{controlName}} ضمن السياسة {{policyName}}، ولن يكون متاحًا للاستخدام حتى يتم إعادة تفعيله.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlActivated(
    key: 'control_activated',
    group: 'Policy & Control',
    titleEn: 'Control Activated Successfully',
    titleAr: 'تم تفعيل الضابط',
    bodyEn: 'The control {{controlName}} under the policy {{policyName}} has been activated.',
    bodyAr: 'تم تفعيل الضابط {{controlName}} ضمن السياسة {{policyName}} بنجاح، وأصبح متاحًا للاستخدام في أنشطة الامتثال والحوكمة.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlWeightIssueDetected(
    key: 'control_weight_issue_detected',
    group: 'Policy & Control',
    titleEn: 'Control Weight Issue Detected',
    titleAr: 'تم اكتشاف مشكلة في وزن الضابط',
    bodyEn: 'A weight issue has been identified for {{controlName}}. Please review the control weight configuration.',
    bodyAr: 'تم اكتشاف مشكلة في وزن الضابط {{controlName}}. يرجى مراجعة إعدادات الوزن.',
    variables: {TemplateVariable.controlName},
  ),
  controlWeightIssueResolved(
    key: 'control_weight_issue_resolved',
    group: 'Policy & Control',
    titleEn: 'Control Weight Issue Resolved',
    titleAr: 'تم حل مشكلة وزن الضابط',
    bodyEn: 'The weight issue affecting {{controlName}} has been resolved.',
    bodyAr: 'تم حل مشكلة وزن الضابط {{controlName}}.',
    variables: {TemplateVariable.controlName},
  ),
  controlOwnerAssigned(
    key: 'control_owner_assigned',
    group: 'Policy & Control',
    titleEn: 'Control Ownership Assigned',
    titleAr: 'تم تعيينك مالكًا للضابط',
    bodyEn: 'You have been assigned as the Control Owner for {{controlName}} under the policy {{policyName}}. You are now responsible for managing, maintaining, and monitoring this control.',
    bodyAr: 'تم تعيينك مالكًا للضابط {{controlName}} ضمن السياسة {{policyName}}. أصبحت الآن مسؤولًا عن إدارة هذا الضابط وصيانته ومتابعته.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlRejected(
    key: 'control_rejected',
    group: 'Policy & Control',
    titleEn: 'Control Rejected',
    titleAr: 'تم رفض الضابط',
    bodyEn: 'The control {{controlName}} under the policy {{policyName}} has been rejected . Please review the rejection comments, update the control as required, and resubmit it for approval.',
    bodyAr: 'تم رفض الضابط {{controlName}} ضمن السياسة {{policyName}} . يرجى مراجعة ملاحظات الرفض، وإجراء التعديلات المطلوبة، ثم إعادة إرساله للموافقة.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName},
  ),
  controlChampionAdded(
    key: 'control_champion_added',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'New Control Champion Assigned',
    titleAr: 'تم تعيين بطل تحكم جديد',
    bodyEn: 'A new Control Champions  bulk upload has been completed by {{uploadedByUserName}}.',
    bodyAr: 'تم تعيينك كبطل تحكم لعنصر التحكم {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.uploadedByUserName, TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlChampionAddedBulkUpload(
    key: 'control_champion_added_bulk_upload',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'New Control Champions Assigned',
    titleAr: 'تم تعيين أبطال ضوابط جدد',
    bodyEn: 'New Control Champion assignments have been added through a bulk upload by {{userName}} for module {{moduleName}}.',
    bodyAr: 'تمت إضافة تعيينات جديدة لأبطال الضوابط من خلال استيراد جماعي بواسطة {{userName}} للوحدة {{moduleName}}.',
    variables: {TemplateVariable.userName, TemplateVariable.moduleName},
  ),
  controlChampionAssignmentStartDateReached(
    key: 'control_champion_assignment_start_date_reached',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Assignment Started',
    titleAr: 'بدأت مهمة بطل الضبط',
    bodyEn: 'Your assignment as Control Champion for control {{controlName}} under policy {{policyName}} in module {{moduleName}} starts today.',
    bodyAr: 'بدأت اليوم مهمتك كبطل ضبط للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlChampionSubmissionDueIn14Days(
    key: 'control_champion_submission_due_in_14_days',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Submission Due Reminder',
    titleAr: 'تذكير بموعد التسليم',
    bodyEn: 'The submission due date for control {{controlName}} under policy {{policyName}} is on {{dueDate}}. Please complete your submission before the deadline.',
    bodyAr: 'موعد تسليم الضبط {{controlName}} ضمن السياسة {{policyName}} هو {{dueDate}}. يرجى إكمال التسليم قبل الموعد المحدد.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.dueDate},
  ),
  controlChampionSubmissionDueToday(
    key: 'control_champion_submission_due_today',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Submission Due Today',
    titleAr: 'موعد التسليم اليوم',
    bodyEn: 'The submission for control {{controlName}} under policy {{policyName}} is due today ({{dueDate}}).',
    bodyAr: 'موعد تسليم الضبط {{controlName}} ضمن السياسة {{policyName}} هو اليوم ({{dueDate}}).',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.dueDate},
  ),
  controlChampionSubmissionOverdue(
    key: 'control_champion_submission_overdue',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Submission Overdue',
    titleAr: 'تجاوز موعد التسليم',
    bodyEn: 'The submission deadline for control {{controlName}} under policy {{policyName}} has passed on {{dueDate}}.',
    bodyAr: 'انتهى موعد تسليم الضبط {{controlName}} ضمن السياسة {{policyName}} بتاريخ {{dueDate}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.dueDate},
  ),
  controlChampionRemoved(
    key: 'control_champion_removed',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Assignment Removed',
    titleAr: 'تم إلغاء تعيين بطل التحكم',
    bodyEn: 'You are no longer assigned as the Control Champion for {{controlName}}.',
    bodyAr: 'لم تعد معينًا كبطل تحكم لعنصر التحكم {{controlName}}.',
    variables: {TemplateVariable.controlName},
  ),
  reassignmentRequested(
    key: 'reassignment_requested',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Reassignment Requested',
    titleAr: 'تم إرسال طلب إعادة تعيين',
    bodyEn: 'A request has been submitted to reassign the Control Champion for {{controlName}} from {{currentChampionName}} to {{newChampionName}}.',
    bodyAr: 'تم إرسال طلب لإعادة تعيين بطل التحكم لعنصر التحكم {{controlName}} من {{currentChampionName}} إلى {{newChampionName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.currentChampionName, TemplateVariable.newChampionName},
  ),
  controlChampionReassignmentRequestSubmitted(
    key: 'control_champion_reassignment_request_submitted',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Reassignment Approval Required',
    titleAr: 'طلب إعادة تعيين بطل الضبط بانتظار الموافقة',
    bodyEn: '{{requesterName}} has submitted a request to reassign Control Champion responsibilities for module {{moduleName}}. Please review the request.',
    bodyAr: 'قام {{requesterName}} بإرسال طلب لإعادة تعيين بطل الضبط في الوحدة {{moduleName}}. يرجى مراجعة الطلب واتخاذ الإجراء المناسب.',
    variables: {TemplateVariable.requesterName, TemplateVariable.moduleName},
  ),
  controlChampionReassignmentRequestUpdated(
    key: 'control_champion_reassignment_request_updated',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Reassignment Request Updated',
    titleAr: 'تم تحديث طلب إعادة التعيين',
    bodyEn: 'The reassignment request submitted by {{requesterName}} for module {{moduleName}} has been updated. Please review the latest changes.',
    bodyAr: 'تم تحديث طلب إعادة تعيين بطل الضبط المقدم من {{requesterName}} في الوحدة {{moduleName}}. يرجى مراجعة آخر التحديثات.',
    variables: {TemplateVariable.requesterName, TemplateVariable.moduleName},
  ),
  controlChampionReassignmentApproved(
    key: 'control_champion_reassignment_approved',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Reassignment Approved',
    titleAr: 'تمت الموافقة على إعادة التعيين',
    bodyEn: 'The reassignment request for module {{moduleName}} has been approved. {{newChampionName}} has been assigned as the new Control Champion.',
    bodyAr: 'تمت الموافقة على طلب إعادة تعيين بطل الضبط في الوحدة {{moduleName}}. وتم تعيين {{newChampionName}} كبطل الضبط الجديد.',
    variables: {TemplateVariable.moduleName, TemplateVariable.newChampionName},
  ),
  controlChampionReassignmentRejected(
    key: 'control_champion_reassignment_rejected',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Reassignment Rejected',
    titleAr: 'تم رفض طلب إعادة التعيين',
    bodyEn: 'The reassignment request for module {{moduleName}} has been rejected by {{approverName}}. Reason: {{rejectionReason}}.',
    bodyAr: 'تم رفض طلب إعادة تعيين بطل الضبط في الوحدة {{moduleName}} بواسطة {{approverName}}. سبب الرفض: {{rejectionReason}}.',
    variables: {TemplateVariable.moduleName, TemplateVariable.approverName, TemplateVariable.rejectionReason},
  ),
  controlChampionReassignmentApprovedOldChampion(
    key: 'control_champion_reassignment_approved_old_champion',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Assignment Removed',
    titleAr: 'تم إنهاء تعيينك كبطل ضبط',
    bodyEn: 'Your Control Champion assignment for control {{controlName}} under policy {{policyName}} in module {{moduleName}} has ended. Responsibility has been reassigned to {{newChampionName}}.',
    bodyAr: 'تم إنهاء تعيينك كبطل ضبط للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}. وتمت إعادة تعيين المسؤولية إلى {{newChampionName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName, TemplateVariable.newChampionName},
  ),
  policyAssignmentChangedControlChampion(
    key: 'policy_assignment_changed_control_champion',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Policy Assignment Updated',
    titleAr: 'تم تحديث تعيين السياسة',
    bodyEn: 'Your policy assignment has been updated. You are now assigned to {{policyName}} for {{controlName}} in {{moduleName}}.',
    bodyAr: 'تم تحديث تعيين السياسة الخاصة بك. أصبحت معينًا على السياسة {{policyName}} لعنصر التحكم {{controlName}} ضمن الوحدة {{moduleName}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.controlName, TemplateVariable.moduleName},
  ),
  controlAssignmentChangedControlChampion(
    key: 'control_assignment_changed_control_champion',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Champion Control Assignment Updated',
    titleAr: 'تم تحديث تعيين عنصر التحكم',
    bodyEn: 'Your Control Champion assignment has been changed from {{oldControlName}} to {{newControlName}} under {{policyName}}.',
    bodyAr: 'تم تحديث تعيينك كبطل تحكم من {{oldControlName}} إلى {{newControlName}} ضمن السياسة {{policyName}}.',
    variables: {TemplateVariable.oldControlName, TemplateVariable.newControlName, TemplateVariable.policyName},
  ),
  approvalRequired(
    key: 'approval_required',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control champion Reassignment Approval Required',
    titleAr: 'طلب موافقة جديد',
    bodyEn: 'A request to reassign {{controlName}} has been submitted by {{requesterName}} and requires your approval.',
    bodyAr: 'تم إرسال طلب من {{requesterName}} لإعادة تعيين عنصر التحكم {{controlName}} ويحتاج إلى موافقتك.',
    variables: {TemplateVariable.controlName, TemplateVariable.requesterName},
  ),
  requestApproved(
    key: 'request_approved',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control champion Reassignment Approved',
    titleAr: 'تمت الموافقة على الطلب',
    bodyEn: 'Your reassignment request for {{controlName}} has been approved.',
    bodyAr: 'تمت الموافقة على طلب إعادة تعيين عنصر التحكم {{controlName}}.',
    variables: {TemplateVariable.controlName},
  ),
  requestRejected(
    key: 'request_rejected',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control champion Reassignment Rejected',
    titleAr: 'تم رفض الطلب',
    bodyEn: 'Your reassignment request for {{controlName}} has been rejected.',
    bodyAr: 'تم رفض طلب إعادة تعيين عنصر التحكم {{controlName}}.',
    variables: {TemplateVariable.controlName},
  ),
  controlOwnerAssigned2(
    key: 'control_owner_assigned_2',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'New Control Owner Assigned',
    titleAr: 'تم تعيين مالك تحكم جديد',
    bodyEn: 'You have been assigned as the Control Owner for {{controlName}} under {{policyName}} in {{moduleName}}.',
    bodyAr: 'تم تعيينك كمالك لعنصر التحكم {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlOwnerAddedBulkUpload(
    key: 'control_owner_added_bulk_upload',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'New Control Owners Assigned',
    titleAr: 'تم تعيين ملاك ضوابط جدد',
    bodyEn: 'New Control Owner assignments have been added through a bulk upload by {{userName}} for module {{moduleName}}.',
    bodyAr: 'تمت إضافة تعيينات جديدة لملاك الضوابط من خلال استيراد جماعي بواسطة {{userName}} للوحدة {{moduleName}}.',
    variables: {TemplateVariable.userName, TemplateVariable.moduleName},
  ),
  controlOwnerReassignmentRequestSubmitted(
    key: 'control_owner_reassignment_request_submitted',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Reassignment Approval Required',
    titleAr: 'طلب إعادة تعيين مالك الضبط بانتظار الموافقة',
    bodyEn: '{{requesterName}} has submitted a request to reassign Control Owner responsibilities for module {{moduleName}}. Please review the request.',
    bodyAr: 'قام {{requesterName}} بإرسال طلب لإعادة تعيين مالك الضبط في الوحدة {{moduleName}}. يرجى مراجعة الطلب واتخاذ الإجراء المناسب.',
    variables: {TemplateVariable.requesterName, TemplateVariable.moduleName},
  ),
  controlOwnerReassignmentRequestUpdated(
    key: 'control_owner_reassignment_request_updated',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Reassignment Request Updated',
    titleAr: 'تم تحديث طلب إعادة تعيين مالك الضبط',
    bodyEn: 'The reassignment request submitted by {{requesterName}} for module {{moduleName}} has been updated. Please review the latest changes.',
    bodyAr: 'تم تحديث طلب إعادة تعيين مالك الضبط المقدم من {{requesterName}} في الوحدة {{moduleName}}. يرجى مراجعة آخر التحديثات.',
    variables: {TemplateVariable.requesterName, TemplateVariable.moduleName},
  ),
  controlOwnerReassignmentApproved(
    key: 'control_owner_reassignment_approved',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Reassignment Approved',
    titleAr: 'تمت الموافقة على إعادة تعيين مالك الضبط',
    bodyEn: 'Your request to reassign the Control Owner for module {{moduleName}} has been approved. {{newOwnerName}} has been assigned as the new Control Owner.',
    bodyAr: 'تمت الموافقة على طلب إعادة تعيين مالك الضبط في الوحدة {{moduleName}}. وتم تعيين {{newOwnerName}} كمالك الضبط الجديد.',
    variables: {TemplateVariable.moduleName, TemplateVariable.newOwnerName},
  ),
  controlOwnerReassignmentRejected(
    key: 'control_owner_reassignment_rejected',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Reassignment Rejected',
    titleAr: 'تم رفض طلب إعادة تعيين مالك الضبط',
    bodyEn: 'Your request to reassign the Control Owner for module {{moduleName}} has been rejected by {{approverName}}. Reason: {{rejectionReason}}.',
    bodyAr: 'تم رفض طلب إعادة تعيين مالك الضبط في الوحدة {{moduleName}} بواسطة {{approverName}}. سبب الرفض: {{rejectionReason}}.',
    variables: {TemplateVariable.moduleName, TemplateVariable.approverName, TemplateVariable.rejectionReason},
  ),
  controlOwnerReassignmentApprovedNewOwner(
    key: 'control_owner_reassignment_approved_new_owner',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'New Control Owner Assigned',
    titleAr: 'تم تعيينك كمالك ضبط جديد',
    bodyEn: 'You have been assigned as the Control Owner for control {{controlName}} under policy {{policyName}} in module {{moduleName}}.',
    bodyAr: 'تم تعيينك كمالك للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName},
  ),
  controlOwnerReassignmentApprovedOldOwner(
    key: 'control_owner_reassignment_approved_old_owner',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Assignment Removed',
    titleAr: 'تم إنهاء تعيينك كمالك ضبط',
    bodyEn: 'Your Control Owner assignment for control {{controlName}} under policy {{policyName}} in module {{moduleName}} has ended. Responsibility has been reassigned to {{newOwnerName}}.',
    bodyAr: 'تم إنهاء تعيينك كمالك للضبط {{controlName}} ضمن السياسة {{policyName}} في الوحدة {{moduleName}}. وتمت إعادة تعيين المسؤولية إلى {{newOwnerName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.policyName, TemplateVariable.moduleName, TemplateVariable.newOwnerName},
  ),
  policyAssignmentChangedControlOwner(
    key: 'policy_assignment_changed_control_owner',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Policy Assignment Updated',
    titleAr: 'تم تحديث تعيين السياسة',
    bodyEn: 'Your policy assignment has been updated. You are now assigned to {{policyName}} for {{controlName}} in {{moduleName}}.',
    bodyAr: 'تم تحديث تعيين السياسة الخاصة بك. أصبحت معينًا على السياسة {{policyName}} لعنصر التحكم {{controlName}} ضمن الوحدة {{moduleName}}.',
    variables: {TemplateVariable.policyName, TemplateVariable.controlName, TemplateVariable.moduleName},
  ),
  controlAssignmentChangedControlOwner(
    key: 'control_assignment_changed_control_owner',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Control Assignment Updated',
    titleAr: 'تم تحديث تعيين عنصر التحكم',
    bodyEn: 'Your Control Owner assignment has been changed from {{oldControlName}} to {{newControlName}} under {{policyName}}.',
    bodyAr: 'تم تحديث تعيينك كمالك تحكم من {{oldControlName}} إلى {{newControlName}} ضمن السياسة {{policyName}}.',
    variables: {TemplateVariable.oldControlName, TemplateVariable.newControlName, TemplateVariable.policyName},
  ),
  controlOwnerRemoved(
    key: 'control_owner_removed',
    group: 'Add Champion Officers & Assign Controls To Their Compliance Officers',
    titleEn: 'Control Owner Assignment Removed',
    titleAr: 'تم إلغاء تعيين مالك التحكم',
    bodyEn: 'You are no longer assigned as the Control Owner for {{controlName}}.',
    bodyAr: 'لم تعد معينًا كمالك لعنصر التحكم {{controlName}}.',
    variables: {TemplateVariable.controlName},
  ),
  evidenceSubmitted(
    key: 'evidence_submitted',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Evidence Submitted Successfully',
    titleAr: 'تم إرسال الدليل بنجاح',
    bodyEn: 'Your evidence for control {{controlName}} has been submitted successfully and is awaiting Department Manager approval.',
    bodyAr: 'تم إرسال الدليل الخاص بالضبط {{controlName}} بنجاح، وهو الآن بانتظار موافقة مدير الإدارة.',
    variables: {TemplateVariable.controlName},
  ),
  departmentManagerApproved(
    key: 'department_manager_approved',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Department Manager Approved',
    titleAr: 'تمت موافقة مدير الإدارة',
    bodyEn: 'Your evidence for control {{controlName}} has been approved by {{departmentManagerName}} and has been forwarded to {{controlOwnerName}} for final review.',
    bodyAr: 'تمت الموافقة على الدليل الخاص بالضبط {{controlName}} بواسطة {{departmentManagerName}} وتم إرساله إلى {{controlOwnerName}} للمراجعة النهائية.',
    variables: {TemplateVariable.controlName, TemplateVariable.departmentManagerName, TemplateVariable.controlOwnerName},
  ),
  departmentManagerRejected(
    key: 'department_manager_rejected',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Department Manager Rejected',
    titleAr: 'تم رفض الدليل بواسطة مدير الإدارة',
    bodyEn: 'Your evidence for control {{controlName}} has been rejected by {{departmentManagerName}}. Please review the comments and resubmit.',
    bodyAr: 'تم رفض الدليل الخاص بالضبط {{controlName}} بواسطة {{departmentManagerName}}. يرجى مراجعة الملاحظات وإعادة الإرسال.',
    variables: {TemplateVariable.controlName, TemplateVariable.departmentManagerName},
  ),
  controlOwnerApproved(
    key: 'control_owner_approved',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Control Approved',
    titleAr: 'تمت الموافقة على الضبط',
    bodyEn: 'Your evidence for control {{controlName}} has been approved by {{controlOwnerName}}.',
    bodyAr: 'تمت الموافقة على الدليل الخاص بالضبط {{controlName}} بواسطة {{controlOwnerName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.controlOwnerName},
  ),
  controlOwnerRejected(
    key: 'control_owner_rejected',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Control Owner Rejected',
    titleAr: 'تم رفض الدليل بواسطة مالك الضبط',
    bodyEn: 'Your evidence for control {{controlName}} has been rejected by {{controlOwnerName}}. Please review the comments and resubmit.',
    bodyAr: 'تم رفض الدليل الخاص بالضبط {{controlName}} بواسطة {{controlOwnerName}}. يرجى مراجعة الملاحظات وإعادة الإرسال.',
    variables: {TemplateVariable.controlName, TemplateVariable.controlOwnerName},
  ),
  evidenceWaitingForReview(
    key: 'evidence_waiting_for_review',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Evidence Pending Your Approval',
    titleAr: 'دليل بانتظار موافقتك',
    bodyEn: '{{controlChampionName}} has submitted evidence for control {{controlName}}. Please review and approve or reject it.',
    bodyAr: 'قام {{controlChampionName}} بإرسال دليل للضبط {{controlName}}. يرجى مراجعته واتخاذ قرار بالموافقة أو الرفض.',
    variables: {TemplateVariable.controlChampionName, TemplateVariable.controlName},
  ),
  evidenceWaitingForFinalApproval(
    key: 'evidence_waiting_for_final_approval',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Evidence Pending Final Approval',
    titleAr: 'دليل بانتظار الموافقة النهائية',
    bodyEn: 'The evidence for control {{controlName}}, submitted by {{controlChampionName}} and approved by {{departmentManagerName}}, is awaiting your final review.',
    bodyAr: 'الدليل الخاص بالضبط {{controlName}} والمقدم من {{controlChampionName}} بعد موافقة {{departmentManagerName}} بانتظار مراجعتك النهائية.',
    variables: {TemplateVariable.controlName, TemplateVariable.controlChampionName, TemplateVariable.departmentManagerName},
  ),
  scoreHasBeenAdded(
    key: 'score_has_been_added',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Control Score Added',
    titleAr: 'تمت إضافة درجة للضبط',
    bodyEn: 'A compliance score of {{controlScore}} has been assigned to {{controlName}} by {{controlOwnerName}}.',
    bodyAr: 'تم إضافة درجة امتثال قدرها {{controlScore}} للضبط {{controlName}} بواسطة {{controlOwnerName}}.',
    variables: {TemplateVariable.controlScore, TemplateVariable.controlName, TemplateVariable.controlOwnerName},
  ),
  scoreHasBeenEdited(
    key: 'score_has_been_edited',
    group: 'Assignment Controls & Approvals & Audit',
    titleEn: 'Control Score Updated',
    titleAr: 'تم تحديث درجة الضبط',
    bodyEn: 'The compliance score for {{controlName}} has been updated from {{oldControlScore}} to {{newControlScore}} by {{controlOwnerName}}.',
    bodyAr: 'تم تحديث درجة امتثال الضبط {{controlName}} من {{oldControlScore}} إلى {{newControlScore}} بواسطة {{controlOwnerName}}.',
    variables: {TemplateVariable.controlName, TemplateVariable.oldControlScore, TemplateVariable.newControlScore, TemplateVariable.controlOwnerName},
  );

  const GrcNotificationEvent({
    required this.key,
    required this.group,
    required this.titleEn,
    required this.titleAr,
    required this.bodyEn,
    required this.bodyAr,
    required this.variables,
  });

  @override
  final String key;

  /// Sub-section this event belongs to inside the module (may be empty).
  @override
  final String group;

  @override
  final String titleEn;
  @override
  final String titleAr;
  @override
  final String bodyEn;
  @override
  final String bodyAr;
  @override
  final Set<TemplateVariable> variables;

  @override
  AppModule get module => AppModule.grc;

  /// Firestore template document id: `<module>_<key>`.
  @override
  String get templateId => '${module.key}_$key';

  static GrcNotificationEvent? fromKey(String key) {
    for (final e in values) {
      if (e.key == key) return e;
    }
    return null;
  }
}
