// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpowBpp00U5BmvFZS1MgnIy9mzN8u2fw',
    appId: '1:662885989585:web:2a391b98c985a6166fd9f0',
    messagingSenderId: '662885989585',
    projectId: 'knowticed-v2-scheme',
    authDomain: 'knowticed-v2-scheme.firebaseapp.com',
    storageBucket: 'knowticed-v2-scheme.appspot.com',
    measurementId: 'G-FY0D4CD1PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATnLBmpY-W8tAauU8x-pQGI49azLxYF5k',
    appId: '1:662885989585:android:885a2c29ee9b41a36fd9f0',
    messagingSenderId: '662885989585',
    projectId: 'knowticed-v2-scheme',
    storageBucket: 'knowticed-v2-scheme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Ghu4_EVS0E_lcM6T0f2UBn50fFOKn4A',
    appId: '1:662885989585:ios:f91783e5f55e3d4a6fd9f0',
    messagingSenderId: '662885989585',
    projectId: 'knowticed-v2-scheme',
    storageBucket: 'knowticed-v2-scheme.appspot.com',
    iosBundleId: 'com.example.twoFirebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Ghu4_EVS0E_lcM6T0f2UBn50fFOKn4A',
    appId: '1:662885989585:ios:f91783e5f55e3d4a6fd9f0',
    messagingSenderId: '662885989585',
    projectId: 'knowticed-v2-scheme',
    storageBucket: 'knowticed-v2-scheme.appspot.com',
    iosBundleId: 'com.example.twoFirebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPpowBpp00U5BmvFZS1MgnIy9mzN8u2fw',
    appId: '1:662885989585:web:439b52b9a087b5806fd9f0',
    messagingSenderId: '662885989585',
    projectId: 'knowticed-v2-scheme',
    authDomain: 'knowticed-v2-scheme.firebaseapp.com',
    storageBucket: 'knowticed-v2-scheme.appspot.com',
    measurementId: 'G-XDE7PJY1MN',
  );
}
