// ****************** FILE INFO ******************
// File Name: cities.dart
// Purpose: Major cities per country used to auto-populate CRM address
//          dropdown choices (keys match Country.name in countries.dart)
// Author: Mohand Adel
// Created At: 08/08/2026

/// Major cities keyed by the exact English country name used in
/// `lib/core/helper/main_helper/countries.dart`. Missing countries fall back
/// to manual option entry in the template editor.
const Map<String, List<String>> countryCities = {
  'Egypt': [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra El Kheima',
    'Port Said',
    'Suez',
    'El Mahalla El Kubra',
    'Mansoura',
    'Tanta',
    'Asyut',
    'Ismailia',
    'Faiyum',
    'Zagazig',
    'Aswan',
    'Damietta',
    'Damanhur',
    'Minya',
    'Beni Suef',
    'Qena',
    'Sohag',
    'Hurghada',
    'Luxor',
    'El Arish',
    'Kafr El Sheikh',
    'Banha',
    'Sharm El Sheikh',
    'Marsa Matruh',
    '6th of October City',
    'New Cairo',
    'Obour City',
    'Badr City',
    'Khusus',
    'Dikirnis',
    'New Mansoura',
    'New Alamein',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    'Dhahran',
    'Taif',
    'Tabuk',
    'Buraidah',
    'Khamis Mushait',
    'Abha',
    'Hail',
    'Najran',
    'Jizan',
    'Al Jubail',
    'Yanbu',
    'Sakaka',
    'Arar',
    'Al Bahah',
  ],
  'United Arab Emirates': [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Al Ain',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
    'Khor Fakkan',
    'Dibba Al Fujairah',
  ],
  'Kuwait': [
    'Kuwait City',
    'Hawalli',
    'Salmiya',
    'Farwaniya',
    'Al Ahmadi',
    'Al Jahra',
    'Mubarak Al-Kabeer',
    'Sabah Al-Salem',
    'Fahaheel',
    'Mangaf',
  ],
  'Qatar': [
    'Doha',
    'Al Rayyan',
    'Al Wakrah',
    'Al Khor',
    'Umm Salal',
    'Al Daayen',
    'Madinat ash Shamal',
    'Lusail',
    'Mesaieed',
    'Dukhan',
  ],
  'Bahrain': [
    'Manama',
    'Riffa',
    'Muharraq',
    'Hamad Town',
    'Isa Town',
    'Sitra',
    'Budaiya',
    "A'ali",
    'Jidhafs',
    'Hidd',
  ],
  'Oman': [
    'Muscat',
    'Salalah',
    'Sohar',
    'Nizwa',
    'Sur',
    'Ibri',
    'Seeb',
    'Barka',
    'Rustaq',
    'Khasab',
    'Buraimi',
    'Ibra',
  ],
  'Jordan': [
    'Amman',
    'Zarqa',
    'Irbid',
    'Aqaba',
    'Salt',
    'Madaba',
    'Jerash',
    'Mafraq',
    'Karak',
    'Tafilah',
    'Ajloun',
    'Ma\'an',
  ],
  'Syrian Arab Republic': [
    'Damascus',
    'Aleppo',
    'Homs',
    'Latakia',
    'Hama',
    'Tartus',
    'Idlib',
    'Deir ez-Zor',
    'Raqqa',
    'Daraa',
    'Al Hasakah',
    'Qamishli',
  ],
  'Lebanon': [
    'Beirut',
    'Tripoli',
    'Sidon',
    'Tyre',
    'Jounieh',
    'Zahle',
    'Baalbek',
    'Byblos',
    'Nabatieh',
    'Aley',
    'Batroun',
  ],
  'Iraq': [
    'Baghdad',
    'Basra',
    'Mosul',
    'Erbil',
    'Najaf',
    'Karbala',
    'Sulaymaniyah',
    'Kirkuk',
    'Ramadi',
    'Fallujah',
    'Nasiriyah',
    'Amarah',
    'Duhok',
    'Samarra',
  ],
  'Yemen': [
    'Sana\'a',
    'Aden',
    'Taiz',
    'Hodeidah',
    'Ibb',
    'Mukalla',
    'Dhamar',
    'Saada',
    'Zinjibar',
  ],
  'Palestinian Territory, Occupied': [
    'Gaza',
    'Ramallah',
    'Hebron',
    'Nablus',
    'Jenin',
    'Bethlehem',
    'Jericho',
    'Tulkarm',
    'Qalqilya',
    'Rafah',
    'Khan Yunis',
    'Salfit',
  ],
  'Libyan Arab Jamahiriya': [
    'Tripoli',
    'Benghazi',
    'Misrata',
    'Al Bayda',
    'Zawiya',
    'Tobruk',
    'Sabha',
    'Sirte',
    'Derna',
    'Gharyan',
    'Zliten',
    'Khoms',
  ],
  'Tunisia': [
    'Tunis',
    'Sfax',
    'Sousse',
    'Kairouan',
    'Bizerte',
    'Gabes',
    'Ariana',
    'Monastir',
    'Gafsa',
    'Nabeul',
    'Médenine',
    'La Marsa',
  ],
  'Algeria': [
    'Algiers',
    'Oran',
    'Constantine',
    'Annaba',
    'Blida',
    'Batna',
    'Sétif',
    'Tlemcen',
    'Bejaia',
    'Mostaganem',
    'Skikda',
    'Tizi Ouzou',
    'Ouargla',
  ],
  'Morocco': [
    'Casablanca',
    'Rabat',
    'Marrakesh',
    'Fes',
    'Tangier',
    'Agadir',
    'Meknes',
    'Oujda',
    'Kenitra',
    'Tetouan',
    'Salé',
    'El Jadida',
    'Nador',
  ],
  'Sudan': [
    'Khartoum',
    'Omdurman',
    'Khartoum North',
    'Port Sudan',
    'Kassala',
    'El Obeid',
    'Wad Madani',
    'Nyala',
    'El Fasher',
    'Kosti',
    'Atbara',
  ],
  'Turkey': [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Antalya',
    'Adana',
    'Gaziantep',
    'Konya',
    'Mersin',
    'Trabzon',
    'Kayseri',
    'Diyarbakır',
    'Samsun',
  ],
  'United States': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Boston',
    'Seattle',
    'Denver',
    'Washington',
    'Miami',
    'Atlanta',
    'Las Vegas',
    'Detroit',
    'Portland',
    'Orlando',
  ],
  'United Kingdom': [
    'London',
    'Manchester',
    'Birmingham',
    'Leeds',
    'Liverpool',
    'Glasgow',
    'Edinburgh',
    'Bristol',
    'Sheffield',
    'Newcastle upon Tyne',
    'Nottingham',
    'Leicester',
    'Cardiff',
    'Belfast',
    'Brighton',
  ],
  'Canada': [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Halifax',
    'Victoria',
    'Saskatoon',
  ],
  'France': [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Toulon',
  ],
  'Germany': [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Leipzig',
    'Dortmund',
    'Essen',
    'Bremen',
    'Dresden',
    'Hannover',
    'Nuremberg',
  ],
  'Spain': [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Granada',
  ],
  'Netherlands': [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
  ],
  'Belgium': [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Charleroi',
    'Liège',
    'Bruges',
    'Leuven',
    'Namur',
    'Mons',
  ],
  'Australia': [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Hobart',
    'Darwin',
    'Wollongong',
    'Sunshine Coast',
  ],
  'India': [
    'Mumbai',
    'Delhi',
    'Bengaluru',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Surat',
    'Kochi',
    'Chandigarh',
    'Indore',
    'Bhopal',
    'Nagpur',
    'Patna',
    'Varanasi',
    'Agra',
  ],
  'Pakistan': [
    'Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Islamabad',
    'Multan',
    'Peshawar',
    'Quetta',
    'Sialkot',
    'Hyderabad',
    'Gujranwala',
    'Sargodha',
  ],
  'China': [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Chongqing',
    'Wuhan',
    "Xi'an",
    'Hangzhou',
    'Nanjing',
    'Tianjin',
    'Suzhou',
    'Harbin',
    'Qingdao',
  ],
};
