/// ************************* FILE INFO *************************
/// File Name: grc_calendar_events.dart
/// Module:    GRC
/// Purpose:   Every calendar entry this module can put on the shared
///            calendar, exactly as specified in "Knowticed Plus —
///            Notification & Validation", Section 2 (Calendar Event
///            Triggers).
///
/// Each value carries its bilingual title, the reminder offset (0 = the
/// event day itself, -14 = the two-week-ahead reminder) and the spec's
/// scheduling note, so calendar_data_service never hardcodes a label,
/// a colour or an offset again.
///
/// RULE: never write a calendar event key or title as a raw string.

import '../calendar_event_type.dart';
import 'package:grc_module/core/enums/app_module.dart';
import 'package:grc_module/core/enums/template_variable.dart';

enum GrcCalendarEvent implements CalendarEventType {
  moduleModuleActivationDateDefined(
    key: 'module_module_activation_date_defined',
    scope: 'Module',
    trigger: 'Module Activation Date Defined',
    titleEn: '{{moduleName}} will Activation on {{activationDate}}',
    titleAr: 'سيتم تفعيل الوحدة {{moduleName}} بتاريخ {{activationDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately after saving the Activation Date. Appears on the activation date.',
    variables: {TemplateVariable.moduleName, TemplateVariable.activationDate},
  ),
  moduleModuleActivationIn14Days(
    key: 'module_module_activation_in_14_days',
    scope: 'Module',
    trigger: 'Module Activation in 14 Days',
    titleEn: '{{moduleName}} will be activated on {{activationDate}}.',
    titleAr: 'سيتم تفعيل الوحدة {{moduleName}} بتاريخ {{activationDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: -14,
    schedulingNote: 'Calendar reminder appears 14 days before the activation date.',
    variables: {TemplateVariable.moduleName, TemplateVariable.activationDate},
  ),
  moduleModuleActivationDateUpdated(
    key: 'module_module_activation_date_updated',
    scope: 'Module',
    trigger: 'Module Activation Date Updated',
    titleEn: '{{moduleName}} activation date updated from {{oldActivationDate}} to {{newActivationDate}}.',
    titleAr: 'تم تحديث موعد تفعيل الوحدة {{moduleName}} من {{oldActivationDate}} إلى {{newActivationDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Existing calendar event is updated automatically to reflect the new activation date.',
    variables: {TemplateVariable.moduleName, TemplateVariable.oldActivationDate, TemplateVariable.newActivationDate},
  ),
  policyPolicyStartDateReached(
    key: 'policy_policy_start_date_reached',
    scope: 'Policy',
    trigger: 'Policy Start Date Reached',
    titleEn: '{{policyName}} will become active on {{startDate}}.',
    titleAr: 'سيتم تفعيل السياسة {{policyName}} بتاريخ {{startDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the activation day.',
    variables: {TemplateVariable.policyName, TemplateVariable.startDate},
  ),
  policyPolicyStartDateUpdated(
    key: 'policy_policy_start_date_updated',
    scope: 'Policy',
    trigger: 'Policy Start Date Updated',
    titleEn: '{{policyName}} activation date updated from {{oldStartDate}} to {{newStartDate}}.',
    titleAr: 'تم تحديث موعد تفعيل السياسة {{policyName}} من {{oldStartDate}} إلى {{newStartDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Existing calendar event is updated with the new Start Date.',
    variables: {TemplateVariable.policyName, TemplateVariable.oldStartDate, TemplateVariable.newStartDate},
  ),
  policyPolicyExpiresIn14Days(
    key: 'policy_policy_expires_in_14_days',
    scope: 'Policy',
    trigger: 'Policy Expires in 14 Days',
    titleEn: '{{policyName}} will expire on {{endDate}}.',
    titleAr: 'ستنتهي صلاحية السياسة {{policyName}} بتاريخ {{endDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: -14,
    schedulingNote: 'Reminder generated 14 days before expiration.',
    variables: {TemplateVariable.policyName, TemplateVariable.endDate},
  ),
  policyPolicyEndDateDefined(
    key: 'policy_policy_end_date_defined',
    scope: 'Policy',
    trigger: 'Policy End Date Defined',
    titleEn: '{{policyName}} will expire on {{endDate}}.',
    titleAr: 'ستنتهي صلاحية السياسة {{policyName}} بتاريخ {{endDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately after the End Date is defined.',
    variables: {TemplateVariable.policyName, TemplateVariable.endDate},
  ),
  policyPolicyExpiresToday(
    key: 'policy_policy_expires_today',
    scope: 'Policy',
    trigger: 'Policy Expires Today',
    titleEn: '{{policyName}} expires on {{endDate}}.',
    titleAr: 'تنتهي صلاحية السياسة {{policyName}} بتاريخ {{endDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar highlights the expiration date.',
    variables: {TemplateVariable.policyName, TemplateVariable.endDate},
  ),
  policyPolicyEndDateUpdated(
    key: 'policy_policy_end_date_updated',
    scope: 'Policy',
    trigger: 'Policy End Date Updated',
    titleEn: '{{policyName}} expiration date updated from {{oldEndDate}} to {{newEndDate}}.',
    titleAr: 'تم تحديث موعد انتهاء السياسة {{policyName}} من {{oldEndDate}} إلى {{newEndDate}}.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Existing calendar event is automatically updated.',
    variables: {TemplateVariable.policyName, TemplateVariable.oldEndDate, TemplateVariable.newEndDate},
  ),
  controlControlStartDateReached(
    key: 'control_control_start_date_reached',
    scope: 'Control',
    trigger: 'Control Start Date Reached',
    titleEn: '{{controlName}} has been activated today.',
    titleAr: 'تم تفعيل الضبط {{controlName}} اليوم.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the activation day.',
    variables: {TemplateVariable.controlName},
  ),
  controlChampionControlAssignmentStartDateReached(
    key: 'control_champion_control_assignment_start_date_reached',
    scope: 'Control Champion',
    trigger: 'Control Assignment Start Date Reached',
    titleEn: 'You have been assigned to {{controlName}} today.',
    titleAr: 'تم تعيينك كبطل للضبط {{controlName}} اليوم.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the assignment Start Date.',
    variables: {TemplateVariable.controlName},
  ),
  controlOwnerControlAssignmentStartDateReached(
    key: 'control_owner_control_assignment_start_date_reached',
    scope: 'Control Owner',
    trigger: 'Control Assignment Start Date Reached',
    titleEn: 'You have been assigned to {{controlName}} today.',
    titleAr: 'تم تعيينك كمالك للضبط {{controlName}} اليوم.',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the assignment Start Date.',
    variables: {TemplateVariable.controlName},
  ),
  controlChampionControlChampionStartDateDefined(
    key: 'control_champion_control_champion_start_date_defined',
    scope: 'Control Champion',
    trigger: 'Control Champion Start Date Defined',
    titleEn: 'Control Champion Assignment Scheduled',
    titleAr: 'تمت جدولة تعيين بطل الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately after the Start Date is defined for the Control Champion assignment.',
    variables: const {},
  ),
  controlChampionControlChampionStartDateReached(
    key: 'control_champion_control_champion_start_date_reached',
    scope: 'Control Champion',
    trigger: 'Control Champion Start Date Reached',
    titleEn: 'Control Champion Assignment Starts Today',
    titleAr: 'يبدأ تعيين بطل الضبط اليوم',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the Start Date.',
    variables: const {},
  ),
  controlChampionSubmissionDueDateDefined(
    key: 'control_champion_submission_due_date_defined',
    scope: 'Control Champion',
    trigger: 'Submission Due Date Defined',
    titleEn: 'Control Champion Submission Scheduled',
    titleAr: 'تمت جدولة موعد تسليم بطل الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately after the submission Due Date is defined.',
    variables: const {},
  ),
  controlChampionSubmissionDueIn14Days(
    key: 'control_champion_submission_due_in_14_days',
    scope: 'Control Champion',
    trigger: 'Submission Due in 14 Days',
    titleEn: 'Control Champion Submission Due Soon',
    titleAr: 'اقتراب موعد تسليم بطل الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: -14,
    schedulingNote: 'Reminder appears 14 days before the submission Due Date.',
    variables: const {},
  ),
  controlChampionSubmissionDueDateReached(
    key: 'control_champion_submission_due_date_reached',
    scope: 'Control Champion',
    trigger: 'Submission Due Date Reached',
    titleEn: 'Control Champion Submission Due Today',
    titleAr: 'موعد تسليم بطل الضبط اليوم',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the submission Due Date.',
    variables: const {},
  ),
  controlChampionSubmissionDueDatePassed(
    key: 'control_champion_submission_due_date_passed',
    scope: 'Control Champion',
    trigger: 'Submission Due Date Passed',
    titleEn: 'Control Champion Submission Overdue',
    titleAr: 'تسليم بطل الضبط متأخر',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Triggered when the submission Due Date passes without a submitted status being recorded.',
    variables: const {},
  ),
  controlChampionControlChampionStartDateUpdated(
    key: 'control_champion_control_champion_start_date_updated',
    scope: 'Control Champion',
    trigger: 'Control Champion Start Date Updated',
    titleEn: 'Control Champion Start Date Updated',
    titleAr: 'تم تحديث تاريخ بدء تعيين بطل الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Existing calendar entry is updated automatically with the new Start Date.',
    variables: const {},
  ),
  controlChampionSubmissionDueDateUpdated(
    key: 'control_champion_submission_due_date_updated',
    scope: 'Control Champion',
    trigger: 'Submission Due Date Updated',
    titleEn: 'Control Champion Submission Due Date Updated',
    titleAr: 'تم تحديث موعد تسليم بطل الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Existing calendar entry is updated automatically with the new submission Due Date.',
    variables: const {},
  ),
  controlChampionRequestReassignmentRequestSubmitted(
    key: 'control_champion_request_reassignment_request_submitted',
    scope: 'Control Champion Request',
    trigger: 'Reassignment Request Submitted',
    titleEn: 'Control Champion Reassignment Pending Approval',
    titleAr: 'طلب إعادة تعيين بطل الضبط بانتظار الموافقة',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately for the approver when the reassignment request is submitted.',
    variables: const {},
  ),
  controlChampionRequestReassignmentRequestApproved(
    key: 'control_champion_request_reassignment_request_approved',
    scope: 'Control Champion Request',
    trigger: 'Reassignment Request Approved',
    titleEn: 'Control Champion Assignment Scheduled',
    titleAr: 'تمت جدولة تعيين بطل الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is automatically created for the newly assigned Control Champion using the approved Start Date and End Date.',
    variables: const {},
  ),
  controlChampionRequestControlChampionAssignmentStartDateReached(
    key: 'control_champion_request_control_champion_assignment_start_date_reached',
    scope: 'Control Champion Request',
    trigger: 'Control Champion Assignment Start Date Reached',
    titleEn: 'Control Champion Assignment Starts Today',
    titleAr: 'يبدأ تعيين بطل الضبط اليوم',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar highlights the assignment Start Date.',
    variables: const {},
  ),
  controlChampionRequestControlChampionAssignmentEndsToday(
    key: 'control_champion_request_control_champion_assignment_ends_today',
    scope: 'Control Champion Request',
    trigger: 'Control Champion Assignment Ends Today',
    titleEn: 'Control Champion Assignment Ends Today',
    titleAr: 'ينتهي تعيين بطل الضبط اليوم',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar highlights the assignment End Date.',
    variables: const {},
  ),
  controlOwnerControlOwnerStartDateDefined(
    key: 'control_owner_control_owner_start_date_defined',
    scope: 'Control Owner',
    trigger: 'Control Owner Start Date Defined',
    titleEn: 'Control Owner Assignment Scheduled',
    titleAr: 'تمت جدولة تعيين مالك الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately after the Start Date is defined for the Control Owner assignment.',
    variables: const {},
  ),
  controlOwnerControlOwnerStartDateReached(
    key: 'control_owner_control_owner_start_date_reached',
    scope: 'Control Owner',
    trigger: 'Control Owner Start Date Reached',
    titleEn: 'Control Owner Assignment Starts Today',
    titleAr: 'يبدأ تعيين مالك الضبط اليوم',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar event is highlighted on the Start Date.',
    variables: const {},
  ),
  controlOwnerControlOwnerStartDateUpdated(
    key: 'control_owner_control_owner_start_date_updated',
    scope: 'Control Owner',
    trigger: 'Control Owner Start Date Updated',
    titleEn: 'Control Owner Start Date Updated',
    titleAr: 'تم تحديث تاريخ بدء تعيين مالك الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Existing calendar entry is updated automatically with the new Start Date.',
    variables: const {},
  ),
  controlOwnerRequestReassignmentRequestSubmitted(
    key: 'control_owner_request_reassignment_request_submitted',
    scope: 'Control Owner Request',
    trigger: 'Reassignment Request Submitted',
    titleEn: 'Control Owner Reassignment Pending Approval',
    titleAr: 'طلب إعادة تعيين مالك الضبط بانتظار الموافقة',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is created immediately for the approver when the reassignment request is submitted.',
    variables: const {},
  ),
  controlOwnerRequestReassignmentRequestApproved(
    key: 'control_owner_request_reassignment_request_approved',
    scope: 'Control Owner Request',
    trigger: 'Reassignment Request Approved',
    titleEn: 'Control Owner Assignment Scheduled',
    titleAr: 'تمت جدولة تعيين مالك الضبط',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar entry is automatically created for the newly assigned Control Owner using the approved Start Date and End Date.',
    variables: const {},
  ),
  controlOwnerRequestControlOwnerAssignmentStartDateReached(
    key: 'control_owner_request_control_owner_assignment_start_date_reached',
    scope: 'Control Owner Request',
    trigger: 'Control Owner Assignment Start Date Reached',
    titleEn: 'Control Owner Assignment Starts Today',
    titleAr: 'يبدأ تعيين مالك الضبط اليوم',
    descriptionEn: '',
    descriptionAr: '',
    statusCode: '',
    colorValue: 0xFF9FADAF,
    reminderOffsetDays: 0,
    schedulingNote: 'Calendar highlights the assignment Start Date.',
    variables: const {},
  );

  const GrcCalendarEvent({
    required this.key,
    required this.scope,
    required this.trigger,
    required this.titleEn,
    required this.titleAr,
    required this.descriptionEn,
    required this.descriptionAr,
    required this.statusCode,
    required this.colorValue,
    required this.reminderOffsetDays,
    required this.schedulingNote,
    required this.variables,
  });

  @override
  final String key;

  /// Sub-area inside the module (e.g. 'Policy', 'Control Champion').
  /// Empty when the module has no sub-areas.
  @override
  final String scope;

  @override
  final String trigger;
  @override
  final String titleEn;
  @override
  final String titleAr;
  @override
  final String descriptionEn;
  @override
  final String descriptionAr;
  @override
  final String statusCode;
  @override
  final int colorValue;
  @override
  final int reminderOffsetDays;
  @override
  final String schedulingNote;
  @override
  final Set<TemplateVariable> variables;

  @override
  AppModule get module => AppModule.grc;

  @override
  String get id => '${module.key}_$key';

  static GrcCalendarEvent? fromKey(String key) {
    for (final e in values) {
      if (e.key == key) return e;
    }
    return null;
  }
}
