part of 'languages.dart';

const Map<String, String> _arEG1 = {
          'Published Date': 'تاريخ النشر',
          'Date Requested': 'تاريخ الطلب',
          'Duration': 'المدة',
          'Last Update': 'آخر تحديث',
          "Select Document": "اختر المستند",
          "Type Of Document": "نوع المستند",
          "Uploaded Documents": "المستندات المرفوعة",
          "Cancel": "إلغاء",
          "Set Date": "تعيين التاريخ",
          "No Submission Found": "لا توجد ردود",
          "Editable": "قابل للتعديل",
          "You Can\'t Edit This Form Because It Has Been Submitted":
              "لا يمكنك تعديل هذا النموذج لأنه تم إرساله",
          "Editing Group Details": "تعديل تفاصيل المجموعة",
          "Are You Sure You Want To Edit This Group?":
              "هل أنت متأكد من رغبتك في تعديل هذه المجموعة؟",
          "Edited Group": "تعديل المجموعة",
          "You Successfully Edited This Group": "تم تعديل المجموعة بنجاح",
          'Save': 'حفظ',
          'Edit Group': 'تعديل المجموعة',
          'Group Details': 'تفاصيل المجموعة',
          'Are You Sure You Want To Delete This Group?':
              'هل أنت متأكد من رغبتك في حذف هذه المجموعة؟',
          'Delete Group': 'حذف المجموعة',
          'Deleted Date': 'تاريخ الحذف',
          'NO': 'رقم',

          "messagesPermissions": "صلاحيات الرسائل",
          "morePermissions": "صلاحيات إضافية",
          "seenAndUnseen": "مقروء وغير مقروء",
          "editMessage": "تعديل الرسالة",
          "deleteMessage": "حذف الرسالة",
          "reactions": "التفاعلات",
          "forwardMessage": "إعادة توجيه الرسالة",
          "contact": "جهة الاتصال",
          "poll": "استطلاع",
          "muteNotifications": "كتم الإشعارات",
          "disappearingMessages": "الرسائل المختفية",
          "scheduleMessages": "جدولة الرسائل",

          'Document Details': 'تفاصيل الوثيقة',
          'Total:': 'الإجمالي:',
          'Tabulated': 'جدول',
          'Aggregated': 'مجموع',
          'UnTabulated': 'غير مجدول',
          'UnAggregated': 'غير مجمع',
          'Total Response: ': 'إجمالي الاستجابة: ',
          'Employee Name': 'اسم الموظف',
          'Type Of Media': 'نوع الوسائط',
          'Employees': 'الموظفون',
          'Select Media': 'اختر الوسائط',
          'Uploaded Media': 'الوسائط المرفوعة',
          'th': 'ال',
          '1st': 'الأول',
          '2nd': 'الثاني',
          '3rd': 'الثالث',
          'Group Name Exist': 'اسم المجموعة موجود',
          'You Successfully Create Group': 'تم إنشاء المجموعة بنجاح',
          'You Grant Access Successfully': 'تم منح الوصول بنجاح',
          'Grant Access Successfully': 'تم منح الوصول بنجاح',
          'This allows them the opportunity to review and make any necessary changes to their responses':
              'يتيح لهم الفرصة لمراجعة وإجراء أي تغييرات ضرورية على إجاباتهم',
          'Please enter numbers only more then 0': 'يرجى إدخال الأرقام فقط',
          'Message': 'الرسالة',
          'Submitting Form': 'إرسال النموذج',
          'Are You Sure You Want To Submit This Form ?':
              'هل أنت متأكد من رغبتك في إرسال هذا النموذج؟',
          'Access': 'السماح',
          'Download As Excel': 'تنزيل كملف اكسيل',
          'You Successfully Downloaded This Form as Excel':
              'تم تنزيل النموذج بنجاح كملف اكسيل',
          'Please Enter The valid Phone Number': 'يرجى إدخال رقم هاتف صحيح',
          'Link invalid': 'الرابط غير صالح',
          'Longitude invalid.': 'خط الطول غير صالح.',
          'Latitude invalid.': 'خط العرض غير صالح.',
          'Please enter a valid link': 'يرجى إدخال رابط صالح',
          'Please Enter The valid Email': 'يرجى إدخال البريد الإلكتروني الصحيح',
          'Editing Form Details': 'تعديل تفاصيل النموذج',
          'Deleting Form Details': 'حذف تفاصيل النموذج',
          'Restore Form': 'استعادة النموذج',
          'Are You Sure You Want To Restore The Form?':
              'هل أنت متأكد من رغبتك في استعادة النموذج؟',
          'Details': 'التفاصيل',
          'Group Name': 'اسم المجموعة',
          'scheduled': 'مجدول',
          'Resend Now': 'إعادة الإرسال الآن',
          'Resend In': 'إعادة الإرسال في',
          'Hours': 'ساعات',
          'Minutes': 'دقائق',
          'Are You Sure You Want To Edit This Form ?':
              'هل أنت متأكد من رغبتك في تعديل هذا النموذج؟',
          'Received Date': 'تاريخ الاستلام',
          'Submission Date': 'تاريخ التقديم',
          'Requested By': 'مطلوب بواسطة',
          'AM': 'ص',
          'PM': 'م',
          'Are You Sure You Want To Put This Form In The Draft?':
              'هل أنت متأكد من رغبتك في وضع هذا النموذج في المسودة؟',
          'Are You Sure You Want To Create This Form ?':
              'هل أنت متأكد من رغبتك في إنشاء هذا النموذج؟',
          'Attached Digital Signature': 'التوقيع الرقمي المرفق',
          'Location Type': 'نوع الموقع',
          'Add Options': 'إضافة خيارات',
          'Add Options Or': 'إضافة خيارات أو',
          'Choose Arrangement': 'اختر الترتيب',
          'Maximum Selection': 'الحد الأقصى للاختيار',
          'Upload Attachment': 'تحميل المرفق',
          'Upload eSignature': 'تحميل التوقيع الإلكتروني',
          'Form Builder': 'منشئ النماذج',
          'Publish': 'نشر',
          'Draft': 'مسودة',
          'Requested Form': 'النموذج المطلوب',
          'Search': 'بحث',
          'Used By:': 'مستخدم من قبل:',
          'Privacy:': 'الخصوصية:',
          'Publish:': 'نشر:',
          'Published Date:': 'تاريخ النشر:',
          'Create Form': 'إنشاء نموذج',
          'Form': 'نموذج',
          'Create New Form': 'إنشاء نموذج جديد',
          'Form Title': 'عنوان النموذج',
          'Text Here': 'النص هنا',
          'Access Management': 'إدارة الوصول',
          'Orientation': 'الاتجاه',
          'Horizontal Padding': 'المسافة الأفقية',
          'Vertical Padding': 'المسافة العمودية',
          'Watermark': 'العلامة المائية',
          'Upload Watermark': 'تحميل العلامة المائية',
          'Watermark Size': 'حجم العلامة المائية',
          'Watermark Opacity': 'شفافية العلامة المائية',
          'Next': 'التالي',
          'First Row': 'الصف الأول',
          'Column': 'عمود',
          'No. of Columns': 'عدد الأعمدة',
          'First Column': 'العمود الأول',
          'Choose Field of': 'اختر حقل',
          'Text Field': 'حقل نصي',
          'Add Title': 'إضافة عنوان',
          'First Name': 'الاسم الأول',
          'Add Hint': 'إضافة تلميح',
          'Choose Alignment': 'اختر المحاذاة',
          'Required': 'مطلوب',
          'Row': 'صف',
          'Deleted': 'محذوف',
          'Break Page': 'فاصل صفحة',
          'Save For Later': 'حفظ للاحقاً',
          'Preview': 'معاينة',
          'Personal Information Form': 'نموذج المعلومات الشخصية',
          'Location': 'الموقع',
          'Last Name': 'الاسم الأخير',
          'Gender': 'الجنس',
          'No Group Found': 'لم يتم العثور على مجموعة',
          'Male': 'ذكر',
          'Female': 'أنثى',
          'Birth Date': 'تاريخ الميلاد',
          'Date': 'التاريخ',
          'Website': 'الموقع الإلكتروني',
          'Add link here': 'أضف الرابط هنا',
          'Page': 'صفحة',
          'Hide': 'إخفاء',
          'Form Details': 'تفاصيل النموذج',
          'Second Row': 'الصف الثاني',
          'Third Row': 'الصف الثالث',
          'Fourth Row': 'الصف الرابع',
          'Submit Form': 'إرسال النموذج',
          'Restoring Form': 'استعادة النموذج',
          'You Successfully Restored This Form': 'تم استعادة النموذج بنجاح',
          'Latitude': 'خط العرض',
          'Longitude': 'خط الطول',
          'Feedback': 'التغذية الراجعة',
          'Type here': 'اكتب هنا',
          'Expand': 'توسيع',
          'Photos of Destination (Both Side)': 'صور الوجهة (كلا الجانبين)',
          'Limitation 4 Images': 'الحد الأقصى 4 صور',
          'Additional Attachment': 'مرفق إضافي',
          'Upload Signature': 'تحميل التوقيع',
          'Open Access': 'وصول مفتوح',
          'Landscape': 'أفقي',
          'Edit Permission': 'تعديل الصلاحيات',
          'Access Begins': 'يبدأ الوصول',
          'Access Ends': 'ينتهي الوصول',
          'Department': 'القسم',
          "Document has been successfully rejected": "تم رفض المستند بنجاح.",
          "The document has been rejected successfully": "تم رفض المستند بنجاح.",
          'Choose Depatment': 'اختر القسم',
          'Marketing': 'التسويق',
          'Design': 'التصميم',
          'Finance': 'المالية',
          'Discard': 'تجاهل',
          "Create Group": "إنشاء مجموعة",
          "Create New Group": "إنشاء مجموعة جديدة",
          'Grant Access': 'السماح بالوصول',
          'Data:': 'البيانات:',
          'Duplicate': 'نسخ',
          'Delete': 'حذف',
          'Edit': 'تعديل',
          'Convert to PDF': 'تحويل إلى PDF',
          'Editing Form': 'تعديل النموذج',
          'Download AS PDF': 'تحميل كملف PDF',
          'Delete Form': 'حذف النموذج',
          'Are You Sure You Want To Delete This Form?':
              'هل أنت متأكد من حذف هذا النموذج؟',
          'Deleting Form': 'جاري حذف النموذج',
          'You Successfully Deleted This Form': 'تم حذف النموذج بنجاح',
          'Form Title Details': 'تفاصيل عنوان النموذج',
          'Fill Out Form': 'ملء النموذج',
          'Results': 'النتائج',

          "editQiyasDetails": "تعديل تفاصيل قياس",
          "deleteQiyas": "حذف قياس",
          "visionBadges": "شارات الرؤية",
          "exportTable": "تصدير الجدول",
          "assignChampion": "تعيين بطل",
          "editEvidence": "تعديل الدليل",
          "removeChampion": "إزالة البطل",
          "reassignChampion": "إعادة تعيين البطل",
          "exportChampionTable": "تصدير جدول الأبطال",
          "qiyasPermissionsModule": "وحدة صلاحيات قياس",
          "championsModule": "وحدة الأبطال",
          "approvalsModule": "وحدة الموافقات",
          "changeSubmissionStatusModule": "وحدة تغيير حالة التقديم",
          "assignedEvidence": "الأدلة المُعيَّنة",
          "uploadedDocumentsModule": "وحدة المستندات المرفوعة",
          "approvals": "الموافقات",
          "changeSubmissionStatus": "تغيير حالة التقديم",

          'Users': 'المستخدمون',
          'Analytics': 'التحليلات',
          'Pending': 'قيد الانتظار',
          'Submissions': 'التقديمات',
          'Remind All': 'تذكير الجميع',
          'Job Title:': 'المسمى الوظيفي:',
          'Department:': 'القسم:',
          'Reminders Sent:': 'تم إرسال التذكيرات:',
          'Send Reminder': 'إرسال تذكير',
          'Submission': 'تقديم',
          'Title:': 'العنوان:',
          'Phone Number:': 'رقم الهاتف:',
          'Email:': 'البريد الإلكتروني:',
          'Email': 'البريد الإلكتروني',
          'Review': 'مراجعة',
          'Reminder Sent': 'تم إرسال التذكير',
          'Send': 'إرسال',
          'Dark Mode': 'الوضع الليلي',
          'Language': 'اللغة',
          'Colors': 'الألوان',
          'Primary Color': 'اللون الأساسي',
          'Secondary Color': 'اللون الثانوي',
          'Fonts': 'الخطوط',
          'English Fonts': 'خطوط الإنجليزية',
          'Arabic Fonts': 'خطوط العربية',
          'Back': 'رجوع',
          'Description': 'الوصف',
          'Submission Date:': 'تاريخ التقديم:',
          'Submission Form': 'نموذج التقديم',
          'Download Form': 'تحميل النموذج',
          'Filter': 'تصفية',
          'File Name': 'اسم الملف',
          'Download': 'تحميل',
          'Employee ID': 'رقم الموظف',
          'Submit': 'إرسال',
          'You Successfully Submit This Form': 'تم إرسال النموذج بنجاح',
          'Share': 'مشاركة',
          'Restore': 'استعادة',
          'Employee Information': 'معلومات الموظف',
          'Private: Only admins can view and manage the comment.':
              'خاص: يمكن للمسؤولين فقط عرض وإدارة التعليق.',
          'Yes': 'نعم',
          'No': 'لا',
          'Sorts': 'الترتيب',
          'Sort': 'ترتيب',
          'Share Form': 'مشاركة النموذج',
          'You Successfully Shared This Form': 'تم مشاركة النموذج بنجاح',
          'Select All': 'تحديد الكل',
          'Group Information': 'معلومات المجموعة',
          'Groups': 'المجموعات',
          'Hr': 'الموارد البشرية',
          'Reset': 'إعادة تعيين',
          'Apply': 'تطبيق',
          'Form Name Details': 'تفاصيل اسم النموذج',
          'Time': 'الوقت',
          'Form Title Arabic': 'عنوان النموذج بالعربية',
          'Description Arabic': 'الوصف بالعربية',
          'Horizontal': 'أفقي',
          'Vertical': 'عمودي',
          'Choose Access Management': 'اختر إدارة الوصول',
          'Restricted Access': 'وصول مقيد',
          'Personal Access': 'وصول شخصي',
          'Choose Orientation': 'اختر الاتجاه',
          'Left': 'يسار',
          'Right': 'يمين',
          'Center': 'وسط',
          'Latitude And Longitude': 'خط العرض وخط الطول',
          'Portrait': 'عمودي',
          'Image': 'صورة',
          'Email Address': 'عنوان البريد الإلكتروني',
          'Phone': 'هاتف',
          'Drop Down': 'قائمة منسدلة',
          'Radio': 'زر راديو',
          'Check Box': 'مربع اختيار',
          'Attachment': 'مرفق',
          'Link': 'رابط',
          'Digital Signature': 'التوقيع الرقمي',
          'Date Selector': 'محدد التاريخ',
          'Address': 'عنوان الإقامة',
          'Time Selector': 'محدد الوقت',
          'Title': 'العنوان',
          'File Upload': 'رفع ملف',
          'Radio - Text Field': 'زر راديو - حقل نصي',
          'Choose Here': 'اختر هنا',
          'Result': 'النتيجة',
          'Birth': 'الميلاد',
          'Job Title': 'المسمى الوظيفي',
          'Photo': 'صورة',
          'Limitation': 'حد',
          'Text Formatting Styles': 'أنماط تنسيق النص',
          'Text Size': 'حجم النص',
          'Color': 'اللون',
          'Request Date': 'تاريخ الطلب',
          'Marital Status': 'الحالة الاجتماعية',
          'Single': 'أعزب',
          'Married': 'متزوج',
          'Signature': 'التوقيع',
          'Country': 'الدولة',
          'State Or Province': 'الولاية أو المقاطعة',
          'City': 'المدينة',
          'Postal Code': 'الرمز البريدي',
          'Street Number': 'رقم الشارع',
          'Apartment': 'الشقة',
          'Creating Form': 'إنشاء نموذج',
          'Form Created': 'تم إنشاء النموذج',
          'Privacy': 'الخصوصية',
          'Draft Form': 'نموذج مسودة',
          'Are You Sure You Want To Put This Form In The Draft':
              'هل أنت متأكد من وضع هذا النموذج في المسودة',
          'Are You Sure You Want To Create This Form':
              'هل أنت متأكد من إنشاء هذا النموذج',
          'You Successfully Created This Form': 'تم إنشاء النموذج بنجاح',
          'You Successfully Drafted This Form': 'تم حفظ النموذج كمسودة بنجاح',
          'Summary': 'ملخص',
          'Total Pages': 'إجمالي الصفحات',
          'Choose The Date': 'اختر التاريخ',
          'Experience': 'الخبرة',
          'First': 'الأول',
          'Second': 'الثاني',
          'Third': 'الثالث',
          'Fourth': 'الرابع',
          'Fifth': 'الخامس',
          'Sixth': 'السادس',
          'Seventh': 'السابع',
          'Eighth': 'الثامن',
          'Ninth': 'التاسع',
          'Tenth': 'العاشر',
          'Add Option Or': 'إضافة خيار أو',
          'Add "other"': 'إضافة "أخرى"',
          'Group': 'مجموعة',

          'notificationModule' : 'الاشعارات',
          'viewOnly' : 'للعرض فقط',

          'Are You Sure You Want To Edit This Form':
              'هل أنت متأكد من تعديل هذا النموذج',
          'You Successfully Edited This Form': 'تم تعديل النموذج بنجاح',
          'You Successfully Downloaded This Form as PDF':
              'تم تحميل النموذج كملف PDF بنجاح',
          'Discard Changes': 'تجاهل التغييرات',
          'Form Download As PDF': 'تحميل النموذج كملف PDF',
          'Duplicating Form': 'نسخ النموذج',
          'You Successfully Duplicated This Form': 'تم نسخ النموذج بنجاح',
          'No Form Found': 'لم يتم العثور على نموذج',
          'This Field Is Required': 'هذا الحقل مطلوب',
          'Put An Image Here': 'ضع صورة هنا',
          'Export': 'تصدير',
          'Publish Date': 'تاريخ النشر',
          'Please enter numbers only': 'الرجاء إدخال أرقام فقط',
          'Please select at least one department': 'الرجاء اختيار قسم واحد على الأقل',
          'Please select start date': 'الرجاء اختيار تاريخ البداية',
          'Please select end date': 'الرجاء اختيار تاريخ النهاية',
          'Terms And Condition': 'الشروط والاحكام',
          'I agree to the Privacy Policy and Terms & Conditions': 'أوافق على سياسة الخصوصية والشروط والأحكام',
          // Settings Section
          'Settings': 'الإعدادات',
          'Settings Module': 'وحدة الإعدادات',

          // Social Permissions Section
          'Social Permissions': 'صلاحيات التواصل الاجتماعي',
          'Social Permissions Module': 'وحدة صلاحيات التواصل الاجتماعي',

          // Settings Permissions
          'Take Screen Shot': 'التقاط لقطة الشاشة',
          'Biometrics For Login': 'القياسات الحيوية لتسجيل الدخول',
          'Restricted Location': 'الموقع المقيد',
          'Company Information': 'معلومات الشركة',
          'Animation': 'الرسوم المتحركة',
          'Branding': 'العلامة التجارية',
          'Screen Share': 'مشاركة الشاشة',

          // Social Permissions
          'Share Social Information': 'مشاركة المعلومات الاجتماعية',
};
