part of 'languages.dart';

const Map<String, String> _enUS1 = {
          'Published Date': 'Published Date',
          'Date Requested': 'Date Requested',
          'Duration': 'Duration',
          'Last Update': 'Last Update',
          "Select Document": "Select Document",
          "Document has been successfully rejected": "Document has been successfully rejected",
          "Type Of Document": "Type Of Document",
          "cancel": "Cancel",
          "Uploaded Documents": "Uploaded Documents",
          "Set Date": "Set Date",
          "No Submission Found": "No Submission Found",
          "Editable": "Editable",
          "You Can\'t Edit This Form Because It Has Been Submitted":
              "You Can't Edit This Form Because It Has Been Submitted",
          "Editing Group Details": "Editing Group Details",
          "Are You Sure You Want To Edit This Group?":
              "Are You Sure You Want To Edit This Group?",
          "You Successfully Edited This Group":
              "You Successfully Edited This Group",
          "Edited Group": "Edited Group",
          'Save': 'Save',
          'Edit Group': 'Edit Group',
          'Group Details': 'Group Details',
          'Are You Sure You Want To Delete This Group?':
              'Are You Sure You Want To Delete This Group?',
          'Delete Group': 'Delete Group',
          'NO': 'NO',
          'Document Details': 'Document Details',
          'Total:': 'Total:',
          'Tabulated': 'Tabulated',
          'Aggregated': 'Aggregated',
          'UnTabulated': 'UnTabulated',
          'UnAggregated': 'UnAggregated',
          'Total Response: ': 'Total Response: ',
          // add english translations here
          'Employee Name': 'Employee Name',
          'Type Of Media': 'Type Of Media',
          'Employees': 'Employees',
          'Select Media': 'Select Media',
          'Uploaded Media': 'Uploaded Media',
          'th': 'th',
          '1st': '1st',
          '2nd': '2nd',
          '3rd': '3rd',
          'Group Name Exist': 'Group Name Exist',
          'Group Created Successfully': 'Group Created Successfully',
          'You Successfully Create Group': 'You Successfully Create Group',
          'You Grant Access Successfully': 'You Grant Access Successfully',
          'Grant Access Successfully': 'Grant Access Successfully',
          'Form Builder': 'Form Builder',
          'Publish': 'Publish',
          'Draft': 'Draft',
          'Requested Form': 'Requested Form',
          'Search': 'Search',
          'Used By:': 'Used By:',
          'Privacy:': 'Privacy:',
          'Publish:': 'Publish:',
          'Published Date:': 'Published Date:',
          'Create Form': 'Create Form',
          'Form': 'Form',
          'Create New Form': 'Create New Form',
          'Form Title': 'Form Title',
          'Text Here': 'Text Here',
          'Access Management': 'Access Management',
          'Orientation': 'Orientation',
          'Horizontal Padding': 'Horizontal Padding',
          'Vertical Padding': 'Vertical Padding',
          'Watermark': 'Watermark',
          'Upload Watermark': 'Upload Watermark',
          'Watermark Size': 'Watermark Size',
          'Watermark Opacity': 'Watermark Opacity',
          'Next': 'Next',
          'First Row': 'First Row',
          'Column': 'Column',
          'No. of Columns': 'No. of Columns',
          'First Column': 'First Column',
          'Choose Field of': 'Choose Field of',
          'Text Field': 'Text Field',
          'Add Title': 'Add Title',
          'First Name': 'First Name',
          'Add Hint': 'Add Hint',
          'Choose Alignment': 'Choose Alignment',
          'Required': 'Required',
          'Row': 'Row',
          'Deleted': 'Deleted',
          ' Break Page': ' Break Page',
          'Save For Later': 'Save For Later',
          'Preview': 'Preview',
          'Personal Information Form': 'Personal Information Form',
          'Location': 'Location',
          'Last Name': 'Last Name',
          'Gender': 'Gender',
          'Male': 'Male',
          'Female': 'Female',
          'Birth Date': 'Birth Date',
          'Date': 'Date',
          'Website': 'Website',
          'Add link here': 'Add link here',
          'Page ': 'Page ',
          'Hide': 'Hide',
          'Form Details': 'Form Details',
          'Second Row': 'Second Row',
          'Third Row': 'Third Row',
          'Fourth Row': 'Fourth Row',
          'Submit Form': 'Submit Form',
          'Restoring Form': 'Restoring Form',
          'You Successfully Restored This Form':
              'You Successfully Restored This Form',
          'Latitude': 'Latitude',
          'Feedback': 'Feedback',
          'Type here': 'Type here',
          'Expand': 'Expand',
          'Photos of Destination (Both Side)':
              'Photos of Destination (Both Side)',
          'Limitation 4 Images': 'Limitation 4 Images',
          'Additional Attachment': 'Additional Attachment',
          'Upload Signature': 'Upload Signature',
          'Open Access': 'Open Access',
          'Landscape': 'Landscape',
          'Edit Permission': 'Edit Permission',
          'Access Begins': 'Access Begins',
          'Access Ends': 'Access Ends',
          'Department': 'Department',
          'Choose Depatment': 'Choose Depatment',
          'Marketing ': 'Marketing ',
          'Design': 'Design',
          'Finance': 'Finance',
          'The document has been rejected successfully': 'The document has been rejected successfully.',
          'Discard': 'Discard',
          'Grant Access': 'Grant Access',
          'Data:': 'Data:',
          'Duplicate': 'Duplicate',
          'Delete': 'Delete',
          'Edit': 'Edit',
          'Convert to PDF': 'Convert to PDF',
          'Editing Form': 'Editing Form',
          'Download As PDF': 'Download AS PDF',
          'Delete Form': 'Delete Form',
          'Are You Sure You Want To Delete This Form?':
              'Are You Sure You Want To Delete This Form?',
          'Deleting Form': 'Deleting Form',
          'You Successfully Deleted This Form':
              'You Successfully Deleted This Form',
          'Form Title Details': 'Form Title Details',
          'Fill Out Form': 'Fill Out Form',
          'Results': 'Results',
          'Users': 'Users',
          'Analytics': 'Analytics',
          'Pending': 'Pending',
          'Submissions': 'Submissions',
          'Remind All': 'Remind All',
          'Job Title:': 'Job Title:',
          'Department: ': 'Department: ',
          'Reminders Sent:': 'Reminders Sent:',
          'Send Reminder': 'Send Reminder',
          'Submission': 'Submission',
          'Title: ': 'Title: ',
          'Department:': 'Department:',
          'Phone Number: ': 'Phone Number: ',
          'Email: ': 'Email: ',
          'Review': 'Review',
          'Reminder Sent': 'Reminder Sent',
          'Send': 'Send',
          'Back': 'Back',
          'Description': 'Description',
          'Submission Date:': 'Submission Date:',
          'Submission Form': 'Submission Form',
          'Download Form': 'Download Form',
          'Filter': 'Filter',
          'File Name': 'File Name',
          'Download': 'Download',
          'Employee ID': 'Employee ID',
          'Submit': 'Submit',
          'You Successfully Submit This Form':
              'You Successfully Submit This Form',
          'Share': 'Share',
          'Restore': 'Restore',
          'Employee Information': 'Employee Information',
          'Private: Only admins can view and manage the comment.':
              'Private: Only admins can view and manage the comment.',
          'Yes': 'Yes',
          'No': 'No',
          'Sorts': 'Sorts',
          'Sort': 'Sort',
          'Share Form': 'Share Form',
          'You Successfully Shared This Form ':
              'You Successfully Shared This Form ',
          'Select All': 'Select All',
          'Group Information': 'Group Information',
          'Groups': 'Groups',
          'Hr': 'Hr',
          'Reset': 'Reset',
          'Apply': 'Apply',
          'Form Name Details': 'Form Name Details',
          // Added missing strings from static constants
          'Time': 'Time',
          'Form Title Arabic': 'Form Title Arabic',
          'Description Arabic': 'Description Arabic',
          'Horizontal': 'Horizontal',
          'Vertical': 'Vertical',
          'Choose Access Management': 'Choose Access Management',
          'Restricted Access': 'Restricted Access',
          'Personal Access': 'Personal Access',
          'Choose Orientation': 'Choose Orientation',
          'Left': 'Left',
          'Right': 'Right',
          'Center': 'Center',
          'Latitude And Longitude': 'Latitude And Longitude',
          'Longitude': 'Longitude',
          'Portrait': 'Portrait',
          'Image': 'Image',
          'Email Address': 'Email Address',
          'Email:': 'Email:',
          'Email': 'Email',
          'Phone': 'Phone',
          'Drop Down': 'Drop Down',
          'Radio': 'Radio',
          'Check Box': 'Check Box',
          'Attachment': 'Attachment',
          'Link': 'Link',
          'Digital Signature': 'Digital Signature',
          'Date Selector': 'Date Selector',
          'Address': 'Address',
          'Time Selector': 'Time Selector',
          'Title': 'Title',
          'File Upload': 'File Upload',
          'Radio - Text Field': 'Radio - Text Field',
          'Choose Here': 'Choose Here',
          'Result': 'Result',
          'Birth': 'Birth',
          'Job Title': 'Job Title',
          'Photo': 'Photo',
          'Limitation': 'Limitation',
          'Text Formatting Styles': 'Text Formatting Styles',
          'Text Size': 'Text Size',
          'Color': 'Color',
          'Request Date': 'Request Date',
          'Marital Status': 'Marital Status',
          'Single': 'Single',
          'Married': 'Married',
          'Signature': 'Signature',
          'Country': 'Country',
          'State Or Province': 'State Or Province',
          'City': 'City',
          'Postal Code': 'Postal Code',
          'Street Number': 'Street Number',
          'Apartment': 'Apartment',
          'Creating Form': 'Creating Form',
          'Form Created': 'Form Created',
          'Privacy': 'Privacy',
          'Draft Form': 'Draft Form',
          'Are You Sure You Want To Put This Form In The Draft':
              'Are You Sure You Want To Put This Form In The Draft',
          'Are You Sure You Want To Create This Form':
              'Are You Sure You Want To Create This Form',
          'You Successfully Created This Form':
              'You Successfully Created This Form',
          'You Successfully Drafted This Form':
              'You Successfully Drafted This Form',
          'Summary': 'Summary',
          'Total Pages': 'Total Pages',
          'Choose The Date': 'Choose The Date',
          'Experience': 'Experience',
          'First': 'First',
          'Second': 'Second',
          'Third': 'Third',
          'Fourth': 'Fourth',
          'Fifth': 'Fifth',
          'Sixth': 'Sixth',
          'Seventh': 'Seventh',
          'Eighth': 'Eighth',
          'Ninth': 'Ninth',
          'Tenth': 'Tenth',
          'Page': 'Page',
          'Break Page': 'Break Page',
          'Add Option Or': 'Add Option Or',
          'Add "other"': 'Add "other"',
          'Group': 'Group',
          'Are You Sure You Want To Edit This Form':
              'Are You Sure You Want To Edit This Form',
          'Dark Mode': 'Dark Mode',
          'Language': 'Language',
          'Colors': 'Colors',
          'Primary Color': 'Primary Color',
          'Secondary Color': 'Secondary Color',
          'Fonts': 'Fonts',
          'English Fonts': 'English Fonts',
          'Arabic Fonts': 'Arabic Fonts',
          'You Successfully Edited This Form':
              'You Successfully Edited This Form',
          'You Successfully Downloaded This Form as PDF':
              'You Successfully Downloaded This Form as PDF',
          'Discard Changes': 'Discard Changes',
          'Form Download AS PDF': 'Form Download As PDF',
          'Duplicating Form': 'Duplicating Form',
          'You Successfully Duplicated This Form':
              'You Successfully Duplicated This Form',
          'No Form Found': 'No Form Found',
          'No Group Found': 'No Group Found',
          'This Field Is Required': 'This Field Is Required',
          'Put An Image Here': 'Put An Image Here',
          'Export': 'Export',
          'Publish Date': 'Publish Date',
          'Please enter numbers only': 'Please enter numbers only',
          'Attached Digital Signature': 'Attached Digital Signature',
          'Location Type': 'Location Type',
          'Add Options': 'Add Options',
          'Add Options Or': 'Add Options Or',
          'Choose Arrangement': 'Choose Arrangement',
          'Maximum Selection': 'Maximum Selection',
          'Upload Attachment': 'Upload Attachment',
          'Upload eSignature': 'Upload eSignature',
          'AM': 'AM',
          'PM': 'PM',
          'Are You Sure You Want To Put This Form In The Draft?':
              'Are You Sure You Want To Put This Form In The Draft?',
          'Are You Sure You Want To Create This Form ?':
              'Are You Sure You Want To Create This Form ?',
          'Are You Sure You Want To Edit This Form ?':
              'Are You Sure You Want To Edit This Form ?',
          'Received Date': 'Received Date',
          'Submission Date': 'Submission Date',
          'Requested By': 'Requested By',
          'Create Group': 'Create Group',
          'Create New Group': 'Create New Group',
          'Details': 'Details',
          'Group Name': 'Group Name',
          'Resend Now': 'Resend Now',
          'Resend In': 'Resend In',
          'Hours': 'Hours',
          'Minutes': 'Minutes',
          'Editing Form Details': 'Editing Form Details',
          'Deleting Form Details': 'Deleting Form Details',
          'Restore Form': 'Restore Form',
          'Are You Sure You Want To Restore The Form?':
              'Are You Sure You Want To Restore The Form?',
          'Please Enter The valid Email': 'Please Enter The valid Email',
          'Please Enter The valid Phone Number':
              'Please Enter The valid Phone Number',
          'Link invalid': 'Link invalid',
          'Longitude invalid.': 'Longitude invalid.',
          'Latitude invalid.': 'Latitude invalid.',
          'Please enter a valid link': 'Please enter a valid link',
          'This allows them the opportunity to review and make any necessary changes to their responses':
              'This allows them the opportunity to review and make any necessary changes to their responses',
          'Please enter numbers only more then 0':
              'Please enter numbers only more then 0',
          'Message': 'Message',
          'Access': 'Access',
          'You Successfully Downloaded This Form as Excel':
              'You Successfully Downloaded This Form as Excel',
          'Download As Excel': 'Download As Excel',
          'Submitting Form': 'Submitting Form',
          'Are You Sure You Want To Submit This Form ?':
              'Are You Sure You Want To Submit This Form ?',
          'Deleted Date': 'Deleted Date',
          'Please select at least one department': 'Please select at least one department',
          'Please select start date': 'Please select start date',
          'Please select end date': 'Please select end date',
          'Terms And Condition': 'Terms And Condition',
          'I agree to the Privacy Policy and Terms & Conditions': 'I agree to the Privacy Policy and Terms & Conditions',

              'Settings': 'Settings',
  'Settings Module': 'Settings Module',

  // Social Permissions Section
  'Social Permissions': 'Social Permissions',
  'Social Permissions Module': 'Social Permissions Module',

  // Settings Permissions
  'Take Screen Shot': 'Take Screen Shot',
  'Biometrics For Login': 'Biometrics For Login',
  'Restricted Location': 'Restricted Location',
  'Company Information': 'Company Information',
  'Animation': 'Animation',
  'Branding': 'Branding',
  'Screen Share': 'Screen Share',

          "qiyasPermissionsModule": "Qiyas Permissions Module",
          "championsModule": "Champions Module",
          "approvalsModule": "Approvals Module",
          "changeSubmissionStatusModule": "Change Submission Status Module",
          "assignedEvidence": "Assigned Evidence",
          "uploadedDocumentsModule": "Uploaded Documents Module",
          "approvals": "Approvals",
          "changeSubmissionStatus": "Change Submission Status",
          "editQiyasDetails": "Edit Qiyas Details",
          "deleteQiyas": "Delete Qiyas",
          "visionBadges": "Vision Badges",
          "exportTable": "Export Qiyas Table",
          "assignChampion": "Assign Champion",
          "editEvidence": "Edit Evidence",
          "removeChampion": "Remove Champion",
          "reassignChampion": "Reassign Champion",
          "exportChampionTable": "Export Champion Table",

  // Social Permissions
  'Share Social Information': 'Share Social Information',
};
