import 'package:flutter/material.dart';

extension DateTimeExtension on DateTime {
  int get dayOfYear {
    int dayOfYear = 0;
    for (int month = 1; month < this.month; month++) {
      dayOfYear += DateUtils.getDaysInMonth(year, month);
    }
    dayOfYear += day;
    return dayOfYear;
  }
}

String getQuoteForToday() {
  List<String> quotes = [
    "The only way to do great work is to love what you do.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Don't watch the clock; do what it does. Keep going.",
    "Opportunities don't happen, you create them.",
    "Believe you can and you're halfway there.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It always seems impossible until it’s done.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Don’t be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not in what you have, but who you are.",
    "The way to get started is to quit talking and begin doing.",
    "What you do today can improve all your tomorrows.",
    "Do something today that your future self will thank you for.",
    "The only place where success comes before work is in the dictionary.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t count the days, make the days count.",
    "Act as if what you do makes a difference. It does.",
    "Quality means doing it right when no one is looking.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "If you want to lift yourself up, lift up someone else.",
    "The best way to predict the future is to create it.",
    "You miss 100% of the shots you don’t take.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    "The difference between ordinary and extraordinary is that little extra.",
    "It's not whether you get knocked down, it's whether you get up.",
    "The secret of getting ahead is getting started.",
    "The best preparation for tomorrow is doing your best today.",
    "Dream big and dare to fail.",
    "Success is a journey, not a destination.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Success seems to be connected with action. Successful people keep moving.",
    "You are never too old to set another goal or to dream a new dream.",
    "The difference between who you are and who you want to be is what you do.",
    "Be the change that you wish to see in the world.",
    "If you can dream it, you can achieve it.",
    "Success is how high you bounce when you hit bottom.",
    "Aim for the moon. If you miss, you may hit a star.",
    "Don’t let yesterday take up too much of today.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "The more you praise and celebrate your life, the more there is in life to celebrate.",
    "There are no shortcuts to any place worth going.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "Do what you can with all you have, wherever you are.",
    "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.",
    "Your attitude, not your aptitude, will determine your altitude.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Do what you can, with what you have, where you are.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Your time is limited, don't waste it living someone else's life.",
    "What we achieve inwardly will change outer reality.",
    "The biggest risk is not taking any risk.",
    "In the end, we only regret the chances we didn't take.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't wait for opportunity. Create it.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The key to success is to focus on goals, not obstacles.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Start where you are. Use what you have. Do what you can.",
    "Don't limit your challenges. Challenge your limits.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The secret of success is to do the common thing uncommonly well.",
    "Fall seven times, stand up eight.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "We generate fears while we sit. We overcome them by action.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The way to get started is to quit talking and begin doing.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "If you're going through hell, keep going.",
    "You are never too old to set another goal or to dream a new dream.",
    "Aim for the moon. If you miss, you may hit a star.",
    "Action is the foundational key to all success.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is not in what you have, but who you are.",
    "The only place where success comes before work is in the dictionary.",
    "Believe you can and you're halfway there.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "What you do today can improve all your tomorrows.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The only way to do great work is to love what you do."
  ];

  List<String> authors = [
    "Steve Jobs",
    "Albert Schweitzer",
    "Sam Levenson",
    "Chris Grosser",
    "Theodore Roosevelt",
    "C.S. Lewis",
    "Winston Churchill",
    "Steve Jobs",
    "Franklin D. Roosevelt",
    "Eleanor Roosevelt",
    "Nelson Mandela",
    "William Butler Yeats",
    "John D. Rockefeller",
    "Thomas Jefferson",
    "Bo Bennett",
    "Walt Disney",
    "Ralph Marston",
    "Sean Patrick Flanery",
    "Vidal Sassoon",
    "Henry David Thoreau",
    "Muhammad Ali",
    "William James",
    "Henry Ford",
    "Charles Kingsleigh",
    "Aisha Tyler",
    "Booker T. Washington",
    "Peter Drucker",
    "Wayne Gretzky",
    "Theodore Roosevelt",
    "Vince Lombardi",
    "Jimmy Johnson",
    "Vince Lombardi",
    "Mark Twain",
    "H. Jackson Brown, Jr.",
    "Norman Vaughan",
    "Ben Sweetland",
    "Ralph Waldo Emerson",
    "Conrad Hilton",
    "C.S. Lewis",
    "Unknown",
    "Mahatma Gandhi",
    "Zig Ziglar",
    "George S. Patton",
    "W. Clement Stone",
    "Will Rogers",
    "Mahatma Gandhi",
    "Oprah Winfrey",
    "Beverly Sills",
    "Joshua J. Marine",
    "Theodore Roosevelt",
    "Anatole France",
    "Zig Ziglar",
    "Steve Jobs",
    "Winston Churchill",
    "Ralph Waldo Emerson",
    "Dalai Lama",
    "Theodore Roosevelt",
    "Franklin D. Roosevelt",
    "Roy T. Bennett",
    "Steve Jobs",
    "Plutarch",
    "Mark Zuckerberg",
    "Lewis Carroll",
    "Mark Twain",
    "Roy T. Bennett",
    "Maya Angelou",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Christian D. Larson",
    "Jim Rohn",
    "Charles Kingsleigh",
    "Arthur Ashe",
    "Unknown",
    "Confucius",
    "John D. Rockefeller Jr.",
    "Japanese Proverb",
    "Franklin D. Roosevelt",
    "Dr. Henry Link",
    "Zig Ziglar",
    "Walt Disney",
    "Robert Collier",
    "Winston Churchill",
    "C.S. Lewis",
    "W. Clement Stone",
    "Pablo Picasso",
    "Albert Schweitzer",
    "Unknown",
    "Bo Bennett",
    "Vidal Sassoon",
    "Theodore Roosevelt",
    "Eleanor Roosevelt",
    "Aisha Tyler",
    "Ralph Marston",
    "Henry David Thoreau",
    "Steve Jobs",
    "Unknown",
  ];

  // Use the current day of the year to get a quote (ensuring it's within the range of the list)
  int dayOfYear = DateTime.now().dayOfYear;
  int quoteIndex = dayOfYear % quotes.length;
  return "${quotes[quoteIndex]} - ${authors[quoteIndex]}";
}
